<?php

namespace DCarbone\PHPFHIRGenerated\DSTU1;

/*!
 * This class was generated with the PHPFHIR library (https://github.com/dcarbone/php-fhir) using
 * class definitions from HL7 FHIR (https://www.hl7.org/fhir/)
 * 
 * Class creation date: December 26th, 2019 15:43+0000
 * 
 * PHPFHIR Copyright:
 * 
 * Copyright 2016-2019 Daniel Carbone (daniel.p.carbone@gmail.com)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 *
 * FHIR Copyright Notice:
 *
 *   Copyright (c) 2011-2013, HL7, Inc.
 *   All rights reserved.
 * 
 *   Redistribution and use in source and binary forms, with or without modification,
 *   are permitted provided that the following conditions are met:
 * 
 *    * Redistributions of source code must retain the above copyright notice, this
 *      list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *    * Neither the name of HL7 nor the names of its contributors may be used to
 *      endorse or promote products derived from this software without specific
 *      prior written permission.
 * 
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *   ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 *   IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 *   INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 *   NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 *   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 * 
 * 
 *   Generated on Tue, Sep 30, 2014 18:08+1000 for FHIR v0.0.82
 */

/**
 * Class PHPFHIRTypeMap
 * @package \DCarbone\PHPFHIRGenerated\DSTU1
 */
abstract class PHPFHIRTypeMap
{
    /**
     * This array represents every type known to this lib
     * @var array
     */
    private static $_typeMap = [
        PHPFHIRConstants::TYPE_NAME_ADDRESS => PHPFHIRConstants::TYPE_CLASS_ADDRESS,
        PHPFHIRConstants::TYPE_NAME_ADDRESS_USE => PHPFHIRConstants::TYPE_CLASS_ADDRESS_USE,
        PHPFHIRConstants::TYPE_NAME_ADDRESS_USE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ADDRESS_USE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ADVERSE_REACTION => PHPFHIRConstants::TYPE_CLASS_ADVERSE_REACTION,
        PHPFHIRConstants::TYPE_NAME_ADVERSE_REACTION_DOT_EXPOSURE => PHPFHIRConstants::TYPE_CLASS_ADVERSE_REACTION_DOT_EXPOSURE,
        PHPFHIRConstants::TYPE_NAME_ADVERSE_REACTION_DOT_SYMPTOM => PHPFHIRConstants::TYPE_CLASS_ADVERSE_REACTION_DOT_SYMPTOM,
        PHPFHIRConstants::TYPE_NAME_AGE => PHPFHIRConstants::TYPE_CLASS_AGE,
        PHPFHIRConstants::TYPE_NAME_AGGREGATION_MODE => PHPFHIRConstants::TYPE_CLASS_AGGREGATION_MODE,
        PHPFHIRConstants::TYPE_NAME_AGGREGATION_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_AGGREGATION_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ALERT => PHPFHIRConstants::TYPE_CLASS_ALERT,
        PHPFHIRConstants::TYPE_NAME_ALERT_STATUS => PHPFHIRConstants::TYPE_CLASS_ALERT_STATUS,
        PHPFHIRConstants::TYPE_NAME_ALERT_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ALERT_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE,
        PHPFHIRConstants::TYPE_NAME_ATTACHMENT => PHPFHIRConstants::TYPE_CLASS_ATTACHMENT,
        PHPFHIRConstants::TYPE_NAME_BACKBONE_ELEMENT => PHPFHIRConstants::TYPE_CLASS_BACKBONE_ELEMENT,
        PHPFHIRConstants::TYPE_NAME_BASE_64BINARY => PHPFHIRConstants::TYPE_CLASS_BASE_64BINARY,
        PHPFHIRConstants::TYPE_NAME_BASE_64BINARY_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_BASE_64BINARY_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_BINARY => PHPFHIRConstants::TYPE_CLASS_BINARY,
        PHPFHIRConstants::TYPE_NAME_BINDING_CONFORMANCE => PHPFHIRConstants::TYPE_CLASS_BINDING_CONFORMANCE,
        PHPFHIRConstants::TYPE_NAME_BINDING_CONFORMANCE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_BINDING_CONFORMANCE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_BOOLEAN => PHPFHIRConstants::TYPE_CLASS_BOOLEAN,
        PHPFHIRConstants::TYPE_NAME_BOOLEAN_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_BOOLEAN_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_DOT_ACTIVITY => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_DOT_ACTIVITY,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_DOT_GOAL => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_DOT_GOAL,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_DOT_PARTICIPANT => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_DOT_PARTICIPANT,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_DOT_SIMPLE => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_DOT_SIMPLE,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_ACTIVITY_CATEGORY => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_ACTIVITY_CATEGORY,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_ACTIVITY_CATEGORY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_ACTIVITY_CATEGORY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_ACTIVITY_STATUS => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_ACTIVITY_STATUS,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_ACTIVITY_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_ACTIVITY_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_GOAL_STATUS => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_GOAL_STATUS,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_GOAL_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_GOAL_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_STATUS => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_STATUS,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CAUSALITY_EXPECTATION => PHPFHIRConstants::TYPE_CLASS_CAUSALITY_EXPECTATION,
        PHPFHIRConstants::TYPE_NAME_CAUSALITY_EXPECTATION_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CAUSALITY_EXPECTATION_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CODE => PHPFHIRConstants::TYPE_CLASS_CODE,
        PHPFHIRConstants::TYPE_NAME_CODE_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_CODE_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_CODEABLE_CONCEPT => PHPFHIRConstants::TYPE_CLASS_CODEABLE_CONCEPT,
        PHPFHIRConstants::TYPE_NAME_CODING => PHPFHIRConstants::TYPE_CLASS_CODING,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION => PHPFHIRConstants::TYPE_CLASS_COMPOSITION,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_DOT_ATTESTER => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_DOT_ATTESTER,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_DOT_EVENT => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_DOT_EVENT,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_DOT_SECTION => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_DOT_SECTION,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_ATTESTATION_MODE => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_ATTESTATION_MODE,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_ATTESTATION_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_ATTESTATION_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_STATUS => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_STATUS,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_DOT_CONCEPT => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_DOT_CONCEPT,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_DOT_DEPENDS_ON => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_DOT_DEPENDS_ON,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_DOT_MAP => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_DOT_MAP,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_EQUIVALENCE => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_EQUIVALENCE,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_EQUIVALENCE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_EQUIVALENCE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONDITION => PHPFHIRConstants::TYPE_CLASS_CONDITION,
        PHPFHIRConstants::TYPE_NAME_CONDITION_DOT_EVIDENCE => PHPFHIRConstants::TYPE_CLASS_CONDITION_DOT_EVIDENCE,
        PHPFHIRConstants::TYPE_NAME_CONDITION_DOT_LOCATION => PHPFHIRConstants::TYPE_CLASS_CONDITION_DOT_LOCATION,
        PHPFHIRConstants::TYPE_NAME_CONDITION_DOT_RELATED_ITEM => PHPFHIRConstants::TYPE_CLASS_CONDITION_DOT_RELATED_ITEM,
        PHPFHIRConstants::TYPE_NAME_CONDITION_DOT_STAGE => PHPFHIRConstants::TYPE_CLASS_CONDITION_DOT_STAGE,
        PHPFHIRConstants::TYPE_NAME_CONDITION_RELATIONSHIP_TYPE => PHPFHIRConstants::TYPE_CLASS_CONDITION_RELATIONSHIP_TYPE,
        PHPFHIRConstants::TYPE_NAME_CONDITION_RELATIONSHIP_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONDITION_RELATIONSHIP_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONDITION_STATUS => PHPFHIRConstants::TYPE_CLASS_CONDITION_STATUS,
        PHPFHIRConstants::TYPE_NAME_CONDITION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONDITION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_CERTIFICATE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_CERTIFICATE,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_DOCUMENT => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_DOCUMENT,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_EVENT => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_EVENT,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_IMPLEMENTATION => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_IMPLEMENTATION,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_MESSAGING => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_MESSAGING,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_OPERATION => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_OPERATION,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_OPERATION_1 => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_OPERATION_1,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_QUERY => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_QUERY,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_RESOURCE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_RESOURCE,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_REST => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_REST,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_SEARCH_PARAM => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_SEARCH_PARAM,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_SECURITY => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_SECURITY,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_SOFTWARE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_SOFTWARE,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_EVENT_MODE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_EVENT_MODE,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_EVENT_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_EVENT_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_STATEMENT_STATUS => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_STATEMENT_STATUS,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_STATEMENT_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_STATEMENT_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONSTRAINT_SEVERITY => PHPFHIRConstants::TYPE_CLASS_CONSTRAINT_SEVERITY,
        PHPFHIRConstants::TYPE_NAME_CONSTRAINT_SEVERITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONSTRAINT_SEVERITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONTACT => PHPFHIRConstants::TYPE_CLASS_CONTACT,
        PHPFHIRConstants::TYPE_NAME_CONTACT_SYSTEM => PHPFHIRConstants::TYPE_CLASS_CONTACT_SYSTEM,
        PHPFHIRConstants::TYPE_NAME_CONTACT_SYSTEM_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONTACT_SYSTEM_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONTACT_USE => PHPFHIRConstants::TYPE_CLASS_CONTACT_USE,
        PHPFHIRConstants::TYPE_NAME_CONTACT_USE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONTACT_USE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_COUNT => PHPFHIRConstants::TYPE_CLASS_COUNT,
        PHPFHIRConstants::TYPE_NAME_CRITICALITY => PHPFHIRConstants::TYPE_CLASS_CRITICALITY,
        PHPFHIRConstants::TYPE_NAME_CRITICALITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CRITICALITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DATE => PHPFHIRConstants::TYPE_CLASS_DATE,
        PHPFHIRConstants::TYPE_NAME_DATE_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_DATE_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_DATE_TIME => PHPFHIRConstants::TYPE_CLASS_DATE_TIME,
        PHPFHIRConstants::TYPE_NAME_DATE_TIME_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_DATE_TIME_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_DECIMAL => PHPFHIRConstants::TYPE_CLASS_DECIMAL,
        PHPFHIRConstants::TYPE_NAME_DECIMAL_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_DECIMAL_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_DEVICE => PHPFHIRConstants::TYPE_CLASS_DEVICE,
        PHPFHIRConstants::TYPE_NAME_DEVICE_OBSERVATION_REPORT => PHPFHIRConstants::TYPE_CLASS_DEVICE_OBSERVATION_REPORT,
        PHPFHIRConstants::TYPE_NAME_DEVICE_OBSERVATION_REPORT_DOT_CHANNEL => PHPFHIRConstants::TYPE_CLASS_DEVICE_OBSERVATION_REPORT_DOT_CHANNEL,
        PHPFHIRConstants::TYPE_NAME_DEVICE_OBSERVATION_REPORT_DOT_METRIC => PHPFHIRConstants::TYPE_CLASS_DEVICE_OBSERVATION_REPORT_DOT_METRIC,
        PHPFHIRConstants::TYPE_NAME_DEVICE_OBSERVATION_REPORT_DOT_VIRTUAL_DEVICE => PHPFHIRConstants::TYPE_CLASS_DEVICE_OBSERVATION_REPORT_DOT_VIRTUAL_DEVICE,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_DOT_EVENT => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_DOT_EVENT,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_DOT_ITEM => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_DOT_ITEM,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_PRIORITY => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_PRIORITY,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_PRIORITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_PRIORITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_STATUS => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_STATUS,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_REPORT => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_REPORT,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_REPORT_DOT_IMAGE => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_REPORT_DOT_IMAGE,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_REPORT_STATUS => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_REPORT_STATUS,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_REPORT_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_REPORT_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DISTANCE => PHPFHIRConstants::TYPE_CLASS_DISTANCE,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_MANIFEST => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_MANIFEST,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_MODE => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_MODE,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_CONTEXT => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_CONTEXT,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_PARAMETER => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_PARAMETER,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_RELATES_TO => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_RELATES_TO,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_SERVICE => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_SERVICE,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_STATUS => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_STATUS,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_RELATIONSHIP_TYPE => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_RELATIONSHIP_TYPE,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_RELATIONSHIP_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_RELATIONSHIP_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DURATION => PHPFHIRConstants::TYPE_CLASS_DURATION,
        PHPFHIRConstants::TYPE_NAME_ELEMENT => PHPFHIRConstants::TYPE_CLASS_ELEMENT,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_DOT_ACCOMODATION => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_DOT_ACCOMODATION,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_DOT_HOSPITALIZATION => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_DOT_HOSPITALIZATION,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_DOT_LOCATION => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_DOT_LOCATION,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_DOT_PARTICIPANT => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_DOT_PARTICIPANT,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_CLASS => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_CLASS,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_CLASS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_CLASS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_STATE => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_STATE,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_STATE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_STATE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_EVENT_TIMING => PHPFHIRConstants::TYPE_CLASS_EVENT_TIMING,
        PHPFHIRConstants::TYPE_NAME_EVENT_TIMING_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_EVENT_TIMING_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_EXPOSURE_TYPE => PHPFHIRConstants::TYPE_CLASS_EXPOSURE_TYPE,
        PHPFHIRConstants::TYPE_NAME_EXPOSURE_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_EXPOSURE_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_EXTENSION => PHPFHIRConstants::TYPE_CLASS_EXTENSION,
        PHPFHIRConstants::TYPE_NAME_EXTENSION_CONTEXT => PHPFHIRConstants::TYPE_CLASS_EXTENSION_CONTEXT,
        PHPFHIRConstants::TYPE_NAME_EXTENSION_CONTEXT_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_EXTENSION_CONTEXT_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_FAMILY_HISTORY => PHPFHIRConstants::TYPE_CLASS_FAMILY_HISTORY,
        PHPFHIRConstants::TYPE_NAME_FAMILY_HISTORY_DOT_CONDITION => PHPFHIRConstants::TYPE_CLASS_FAMILY_HISTORY_DOT_CONDITION,
        PHPFHIRConstants::TYPE_NAME_FAMILY_HISTORY_DOT_RELATION => PHPFHIRConstants::TYPE_CLASS_FAMILY_HISTORY_DOT_RELATION,
        PHPFHIRConstants::TYPE_NAME_FILTER_OPERATOR => PHPFHIRConstants::TYPE_CLASS_FILTER_OPERATOR,
        PHPFHIRConstants::TYPE_NAME_FILTER_OPERATOR_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_FILTER_OPERATOR_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_GROUP => PHPFHIRConstants::TYPE_CLASS_GROUP,
        PHPFHIRConstants::TYPE_NAME_GROUP_DOT_CHARACTERISTIC => PHPFHIRConstants::TYPE_CLASS_GROUP_DOT_CHARACTERISTIC,
        PHPFHIRConstants::TYPE_NAME_GROUP_TYPE => PHPFHIRConstants::TYPE_CLASS_GROUP_TYPE,
        PHPFHIRConstants::TYPE_NAME_GROUP_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_GROUP_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_HIERARCHICAL_RELATIONSHIP_TYPE => PHPFHIRConstants::TYPE_CLASS_HIERARCHICAL_RELATIONSHIP_TYPE,
        PHPFHIRConstants::TYPE_NAME_HIERARCHICAL_RELATIONSHIP_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_HIERARCHICAL_RELATIONSHIP_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_HUMAN_NAME => PHPFHIRConstants::TYPE_CLASS_HUMAN_NAME,
        PHPFHIRConstants::TYPE_NAME_ID => PHPFHIRConstants::TYPE_CLASS_ID,
        PHPFHIRConstants::TYPE_NAME_ID_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_ID_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_IDENTIFIER => PHPFHIRConstants::TYPE_CLASS_IDENTIFIER,
        PHPFHIRConstants::TYPE_NAME_IDENTIFIER_USE => PHPFHIRConstants::TYPE_CLASS_IDENTIFIER_USE,
        PHPFHIRConstants::TYPE_NAME_IDENTIFIER_USE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_IDENTIFIER_USE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_IMAGING_MODALITY => PHPFHIRConstants::TYPE_CLASS_IMAGING_MODALITY,
        PHPFHIRConstants::TYPE_NAME_IMAGING_MODALITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_IMAGING_MODALITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_IMAGING_STUDY => PHPFHIRConstants::TYPE_CLASS_IMAGING_STUDY,
        PHPFHIRConstants::TYPE_NAME_IMAGING_STUDY_DOT_INSTANCE => PHPFHIRConstants::TYPE_CLASS_IMAGING_STUDY_DOT_INSTANCE,
        PHPFHIRConstants::TYPE_NAME_IMAGING_STUDY_DOT_SERIES => PHPFHIRConstants::TYPE_CLASS_IMAGING_STUDY_DOT_SERIES,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_DOT_EXPLANATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_DOT_EXPLANATION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_DOT_REACTION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_DOT_REACTION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_DOT_VACCINATION_PROTOCOL => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_DOT_VACCINATION_PROTOCOL,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION_DOT_DATE_CRITERION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION_DOT_DATE_CRITERION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION_DOT_PROTOCOL => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION_DOT_PROTOCOL,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION_DOT_RECOMMENDATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION_DOT_RECOMMENDATION,
        PHPFHIRConstants::TYPE_NAME_INSTANCE_AVAILABILITY => PHPFHIRConstants::TYPE_CLASS_INSTANCE_AVAILABILITY,
        PHPFHIRConstants::TYPE_NAME_INSTANCE_AVAILABILITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_INSTANCE_AVAILABILITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_INSTANT => PHPFHIRConstants::TYPE_CLASS_INSTANT,
        PHPFHIRConstants::TYPE_NAME_INSTANT_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_INSTANT_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_INTEGER => PHPFHIRConstants::TYPE_CLASS_INTEGER,
        PHPFHIRConstants::TYPE_NAME_INTEGER_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_INTEGER_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_ISSUE_SEVERITY => PHPFHIRConstants::TYPE_CLASS_ISSUE_SEVERITY,
        PHPFHIRConstants::TYPE_NAME_ISSUE_SEVERITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ISSUE_SEVERITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_LINK_TYPE => PHPFHIRConstants::TYPE_CLASS_LINK_TYPE,
        PHPFHIRConstants::TYPE_NAME_LINK_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_LINK_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_LIST => PHPFHIRConstants::TYPE_CLASS_LIST,
        PHPFHIRConstants::TYPE_NAME_LIST_DOT_ENTRY => PHPFHIRConstants::TYPE_CLASS_LIST_DOT_ENTRY,
        PHPFHIRConstants::TYPE_NAME_LIST_MODE => PHPFHIRConstants::TYPE_CLASS_LIST_MODE,
        PHPFHIRConstants::TYPE_NAME_LIST_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_LIST_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_LOCATION => PHPFHIRConstants::TYPE_CLASS_LOCATION,
        PHPFHIRConstants::TYPE_NAME_LOCATION_DOT_POSITION => PHPFHIRConstants::TYPE_CLASS_LOCATION_DOT_POSITION,
        PHPFHIRConstants::TYPE_NAME_LOCATION_MODE => PHPFHIRConstants::TYPE_CLASS_LOCATION_MODE,
        PHPFHIRConstants::TYPE_NAME_LOCATION_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_LOCATION_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_LOCATION_STATUS => PHPFHIRConstants::TYPE_CLASS_LOCATION_STATUS,
        PHPFHIRConstants::TYPE_NAME_LOCATION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_LOCATION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MEDIA => PHPFHIRConstants::TYPE_CLASS_MEDIA,
        PHPFHIRConstants::TYPE_NAME_MEDIA_TYPE => PHPFHIRConstants::TYPE_CLASS_MEDIA_TYPE,
        PHPFHIRConstants::TYPE_NAME_MEDIA_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MEDIA_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MEDICATION => PHPFHIRConstants::TYPE_CLASS_MEDICATION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DOT_CONTENT => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DOT_CONTENT,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DOT_INGREDIENT => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DOT_INGREDIENT,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DOT_PACKAGE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DOT_PACKAGE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DOT_PRODUCT => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DOT_PRODUCT,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ADMINISTRATION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ADMINISTRATION_DOT_DOSAGE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION_DOT_DOSAGE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ADMINISTRATION_STATUS => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION_STATUS,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ADMINISTRATION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE_DOT_DISPENSE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE_DOT_DISPENSE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE_DOT_DOSAGE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE_DOT_DOSAGE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE_DOT_SUBSTITUTION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE_DOT_SUBSTITUTION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE_STATUS => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE_STATUS,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_KIND => PHPFHIRConstants::TYPE_CLASS_MEDICATION_KIND,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_KIND_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MEDICATION_KIND_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_PRESCRIPTION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_PRESCRIPTION_DOT_DISPENSE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION_DOT_DISPENSE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_PRESCRIPTION_DOT_DOSAGE_INSTRUCTION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION_DOT_DOSAGE_INSTRUCTION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_PRESCRIPTION_DOT_SUBSTITUTION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION_DOT_SUBSTITUTION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_PRESCRIPTION_STATUS => PHPFHIRConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION_STATUS,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_PRESCRIPTION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_STATEMENT => PHPFHIRConstants::TYPE_CLASS_MEDICATION_STATEMENT,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_STATEMENT_DOT_DOSAGE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_STATEMENT_DOT_DOSAGE,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_HEADER => PHPFHIRConstants::TYPE_CLASS_MESSAGE_HEADER,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_HEADER_DOT_DESTINATION => PHPFHIRConstants::TYPE_CLASS_MESSAGE_HEADER_DOT_DESTINATION,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_HEADER_DOT_RESPONSE => PHPFHIRConstants::TYPE_CLASS_MESSAGE_HEADER_DOT_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_HEADER_DOT_SOURCE => PHPFHIRConstants::TYPE_CLASS_MESSAGE_HEADER_DOT_SOURCE,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_SIGNIFICANCE_CATEGORY => PHPFHIRConstants::TYPE_CLASS_MESSAGE_SIGNIFICANCE_CATEGORY,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_SIGNIFICANCE_CATEGORY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MESSAGE_SIGNIFICANCE_CATEGORY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MODALITY => PHPFHIRConstants::TYPE_CLASS_MODALITY,
        PHPFHIRConstants::TYPE_NAME_MODALITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MODALITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MONEY => PHPFHIRConstants::TYPE_CLASS_MONEY,
        PHPFHIRConstants::TYPE_NAME_NAME_USE => PHPFHIRConstants::TYPE_CLASS_NAME_USE,
        PHPFHIRConstants::TYPE_NAME_NAME_USE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_NAME_USE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_NARRATIVE => PHPFHIRConstants::TYPE_CLASS_NARRATIVE,
        PHPFHIRConstants::TYPE_NAME_NARRATIVE_STATUS => PHPFHIRConstants::TYPE_CLASS_NARRATIVE_STATUS,
        PHPFHIRConstants::TYPE_NAME_NARRATIVE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_NARRATIVE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION => PHPFHIRConstants::TYPE_CLASS_OBSERVATION,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_DOT_REFERENCE_RANGE => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_DOT_REFERENCE_RANGE,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_DOT_RELATED => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_DOT_RELATED,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_RELATIONSHIP_TYPE => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_RELATIONSHIP_TYPE,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_RELATIONSHIP_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_RELATIONSHIP_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_RELIABILITY => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_RELIABILITY,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_RELIABILITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_RELIABILITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_STATUS => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_STATUS,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_OID => PHPFHIRConstants::TYPE_CLASS_OID,
        PHPFHIRConstants::TYPE_NAME_OID_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_OID_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_OPERATION_OUTCOME => PHPFHIRConstants::TYPE_CLASS_OPERATION_OUTCOME,
        PHPFHIRConstants::TYPE_NAME_OPERATION_OUTCOME_DOT_ISSUE => PHPFHIRConstants::TYPE_CLASS_OPERATION_OUTCOME_DOT_ISSUE,
        PHPFHIRConstants::TYPE_NAME_ORDER => PHPFHIRConstants::TYPE_CLASS_ORDER,
        PHPFHIRConstants::TYPE_NAME_ORDER_DOT_WHEN => PHPFHIRConstants::TYPE_CLASS_ORDER_DOT_WHEN,
        PHPFHIRConstants::TYPE_NAME_ORDER_OUTCOME_STATUS => PHPFHIRConstants::TYPE_CLASS_ORDER_OUTCOME_STATUS,
        PHPFHIRConstants::TYPE_NAME_ORDER_OUTCOME_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ORDER_OUTCOME_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ORDER_RESPONSE => PHPFHIRConstants::TYPE_CLASS_ORDER_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_ORGANIZATION => PHPFHIRConstants::TYPE_CLASS_ORGANIZATION,
        PHPFHIRConstants::TYPE_NAME_ORGANIZATION_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_ORGANIZATION_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_OTHER => PHPFHIRConstants::TYPE_CLASS_OTHER,
        PHPFHIRConstants::TYPE_NAME_PATIENT => PHPFHIRConstants::TYPE_CLASS_PATIENT,
        PHPFHIRConstants::TYPE_NAME_PATIENT_DOT_ANIMAL => PHPFHIRConstants::TYPE_CLASS_PATIENT_DOT_ANIMAL,
        PHPFHIRConstants::TYPE_NAME_PATIENT_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_PATIENT_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_PATIENT_DOT_LINK => PHPFHIRConstants::TYPE_CLASS_PATIENT_DOT_LINK,
        PHPFHIRConstants::TYPE_NAME_PERIOD => PHPFHIRConstants::TYPE_CLASS_PERIOD,
        PHPFHIRConstants::TYPE_NAME_PRACTITIONER => PHPFHIRConstants::TYPE_CLASS_PRACTITIONER,
        PHPFHIRConstants::TYPE_NAME_PRACTITIONER_DOT_QUALIFICATION => PHPFHIRConstants::TYPE_CLASS_PRACTITIONER_DOT_QUALIFICATION,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE => PHPFHIRConstants::TYPE_CLASS_PROCEDURE,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_DOT_PERFORMER => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_DOT_PERFORMER,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_DOT_RELATED_ITEM => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_DOT_RELATED_ITEM,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_RELATIONSHIP_TYPE => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_RELATIONSHIP_TYPE,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_RELATIONSHIP_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_RELATIONSHIP_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_PROFILE => PHPFHIRConstants::TYPE_CLASS_PROFILE,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_BINDING => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_BINDING,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_CONSTRAINT => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_CONSTRAINT,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_DEFINITION => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_DEFINITION,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_ELEMENT => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_ELEMENT,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_EXTENSION_DEFN => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_EXTENSION_DEFN,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_MAPPING => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_MAPPING,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_MAPPING_1 => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_MAPPING_1,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_QUERY => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_QUERY,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_SEARCH_PARAM => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_SEARCH_PARAM,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_SLICING => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_SLICING,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_STRUCTURE => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_STRUCTURE,
        PHPFHIRConstants::TYPE_NAME_PROFILE_DOT_TYPE => PHPFHIRConstants::TYPE_CLASS_PROFILE_DOT_TYPE,
        PHPFHIRConstants::TYPE_NAME_PROPERTY_REPRESENTATION => PHPFHIRConstants::TYPE_CLASS_PROPERTY_REPRESENTATION,
        PHPFHIRConstants::TYPE_NAME_PROPERTY_REPRESENTATION_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PROPERTY_REPRESENTATION_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE => PHPFHIRConstants::TYPE_CLASS_PROVENANCE,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE_DOT_AGENT => PHPFHIRConstants::TYPE_CLASS_PROVENANCE_DOT_AGENT,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE_DOT_ENTITY => PHPFHIRConstants::TYPE_CLASS_PROVENANCE_DOT_ENTITY,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE_ENTITY_ROLE => PHPFHIRConstants::TYPE_CLASS_PROVENANCE_ENTITY_ROLE,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE_ENTITY_ROLE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PROVENANCE_ENTITY_ROLE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_QUANTITY => PHPFHIRConstants::TYPE_CLASS_QUANTITY,
        PHPFHIRConstants::TYPE_NAME_QUANTITY_COMPARARATOR => PHPFHIRConstants::TYPE_CLASS_QUANTITY_COMPARARATOR,
        PHPFHIRConstants::TYPE_NAME_QUANTITY_COMPARARATOR_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_QUANTITY_COMPARARATOR_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_QUERY => PHPFHIRConstants::TYPE_CLASS_QUERY,
        PHPFHIRConstants::TYPE_NAME_QUERY_DOT_RESPONSE => PHPFHIRConstants::TYPE_CLASS_QUERY_DOT_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_QUERY_OUTCOME => PHPFHIRConstants::TYPE_CLASS_QUERY_OUTCOME,
        PHPFHIRConstants::TYPE_NAME_QUERY_OUTCOME_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_QUERY_OUTCOME_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_DOT_GROUP => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_DOT_GROUP,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_DOT_QUESTION => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_DOT_QUESTION,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_STATUS => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_STATUS,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RANGE => PHPFHIRConstants::TYPE_CLASS_RANGE,
        PHPFHIRConstants::TYPE_NAME_RATIO => PHPFHIRConstants::TYPE_CLASS_RATIO,
        PHPFHIRConstants::TYPE_NAME_REACTION_SEVERITY => PHPFHIRConstants::TYPE_CLASS_REACTION_SEVERITY,
        PHPFHIRConstants::TYPE_NAME_REACTION_SEVERITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_REACTION_SEVERITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RELATED_PERSON => PHPFHIRConstants::TYPE_CLASS_RELATED_PERSON,
        PHPFHIRConstants::TYPE_NAME_RESOURCE => PHPFHIRConstants::TYPE_CLASS_RESOURCE,
        PHPFHIRConstants::TYPE_NAME_RESOURCE_DOT_INLINE => PHPFHIRConstants::TYPE_CLASS_RESOURCE_DOT_INLINE,
        PHPFHIRConstants::TYPE_NAME_RESOURCE_NAMES_PLUS_BINARY => PHPFHIRConstants::TYPE_CLASS_RESOURCE_NAMES_PLUS_BINARY,
        PHPFHIRConstants::TYPE_NAME_RESOURCE_PROFILE_STATUS => PHPFHIRConstants::TYPE_CLASS_RESOURCE_PROFILE_STATUS,
        PHPFHIRConstants::TYPE_NAME_RESOURCE_PROFILE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_RESOURCE_PROFILE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RESOURCE_REFERENCE => PHPFHIRConstants::TYPE_CLASS_RESOURCE_REFERENCE,
        PHPFHIRConstants::TYPE_NAME_RESOURCE_TYPE => PHPFHIRConstants::TYPE_CLASS_RESOURCE_TYPE,
        PHPFHIRConstants::TYPE_NAME_RESPONSE_TYPE => PHPFHIRConstants::TYPE_CLASS_RESPONSE_TYPE,
        PHPFHIRConstants::TYPE_NAME_RESPONSE_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_RESPONSE_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RESTFUL_CONFORMANCE_MODE => PHPFHIRConstants::TYPE_CLASS_RESTFUL_CONFORMANCE_MODE,
        PHPFHIRConstants::TYPE_NAME_RESTFUL_CONFORMANCE_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_RESTFUL_CONFORMANCE_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RESTFUL_OPERATION_SYSTEM => PHPFHIRConstants::TYPE_CLASS_RESTFUL_OPERATION_SYSTEM,
        PHPFHIRConstants::TYPE_NAME_RESTFUL_OPERATION_SYSTEM_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_RESTFUL_OPERATION_SYSTEM_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RESTFUL_OPERATION_TYPE => PHPFHIRConstants::TYPE_CLASS_RESTFUL_OPERATION_TYPE,
        PHPFHIRConstants::TYPE_NAME_RESTFUL_OPERATION_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_RESTFUL_OPERATION_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SAMPLED_DATA => PHPFHIRConstants::TYPE_CLASS_SAMPLED_DATA,
        PHPFHIRConstants::TYPE_NAME_SAMPLED_DATA_DATA_TYPE => PHPFHIRConstants::TYPE_CLASS_SAMPLED_DATA_DATA_TYPE,
        PHPFHIRConstants::TYPE_NAME_SAMPLED_DATA_DATA_TYPE_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_SAMPLED_DATA_DATA_TYPE_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_SCHEDULE => PHPFHIRConstants::TYPE_CLASS_SCHEDULE,
        PHPFHIRConstants::TYPE_NAME_SCHEDULE_DOT_REPEAT => PHPFHIRConstants::TYPE_CLASS_SCHEDULE_DOT_REPEAT,
        PHPFHIRConstants::TYPE_NAME_SCORE => PHPFHIRConstants::TYPE_CLASS_SCORE,
        PHPFHIRConstants::TYPE_NAME_SEARCH_PARAM_TYPE => PHPFHIRConstants::TYPE_CLASS_SEARCH_PARAM_TYPE,
        PHPFHIRConstants::TYPE_NAME_SEARCH_PARAM_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SEARCH_PARAM_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_DOT_DETAIL => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_DOT_DETAIL,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_DOT_EVENT => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_DOT_EVENT,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_DOT_NETWORK => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_DOT_NETWORK,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_DOT_OBJECT => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_DOT_OBJECT,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_DOT_PARTICIPANT => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_DOT_PARTICIPANT,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_DOT_SOURCE => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_DOT_SOURCE,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_ACTION => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_ACTION,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_ACTION_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_ACTION_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_LIFECYCLE => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_LIFECYCLE,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_LIFECYCLE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_LIFECYCLE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_ROLE => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_ROLE,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_ROLE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_ROLE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_TYPE => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_TYPE,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_OUTCOME => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_OUTCOME,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_OUTCOME_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_OUTCOME_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_PARTICIPANT_NETWORK_TYPE => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_PARTICIPANT_NETWORK_TYPE,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT_PARTICIPANT_NETWORK_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT_PARTICIPANT_NETWORK_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SENSITIVITY_STATUS => PHPFHIRConstants::TYPE_CLASS_SENSITIVITY_STATUS,
        PHPFHIRConstants::TYPE_NAME_SENSITIVITY_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SENSITIVITY_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SENSITIVITY_TYPE => PHPFHIRConstants::TYPE_CLASS_SENSITIVITY_TYPE,
        PHPFHIRConstants::TYPE_NAME_SENSITIVITY_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SENSITIVITY_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SLICING_RULES => PHPFHIRConstants::TYPE_CLASS_SLICING_RULES,
        PHPFHIRConstants::TYPE_NAME_SLICING_RULES_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SLICING_RULES_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN => PHPFHIRConstants::TYPE_CLASS_SPECIMEN,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN_DOT_COLLECTION => PHPFHIRConstants::TYPE_CLASS_SPECIMEN_DOT_COLLECTION,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN_DOT_CONTAINER => PHPFHIRConstants::TYPE_CLASS_SPECIMEN_DOT_CONTAINER,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN_DOT_SOURCE => PHPFHIRConstants::TYPE_CLASS_SPECIMEN_DOT_SOURCE,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN_DOT_TREATMENT => PHPFHIRConstants::TYPE_CLASS_SPECIMEN_DOT_TREATMENT,
        PHPFHIRConstants::TYPE_NAME_STRING => PHPFHIRConstants::TYPE_CLASS_STRING,
        PHPFHIRConstants::TYPE_NAME_STRING_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_STRING_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_SUBSTANCE => PHPFHIRConstants::TYPE_CLASS_SUBSTANCE,
        PHPFHIRConstants::TYPE_NAME_SUBSTANCE_DOT_INGREDIENT => PHPFHIRConstants::TYPE_CLASS_SUBSTANCE_DOT_INGREDIENT,
        PHPFHIRConstants::TYPE_NAME_SUBSTANCE_DOT_INSTANCE => PHPFHIRConstants::TYPE_CLASS_SUBSTANCE_DOT_INSTANCE,
        PHPFHIRConstants::TYPE_NAME_SUPPLY => PHPFHIRConstants::TYPE_CLASS_SUPPLY,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_DOT_DISPENSE => PHPFHIRConstants::TYPE_CLASS_SUPPLY_DOT_DISPENSE,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_DISPENSE_STATUS => PHPFHIRConstants::TYPE_CLASS_SUPPLY_DISPENSE_STATUS,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_DISPENSE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SUPPLY_DISPENSE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_STATUS => PHPFHIRConstants::TYPE_CLASS_SUPPLY_STATUS,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SUPPLY_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_TOTAL_RESULTS => PHPFHIRConstants::TYPE_CLASS_TOTAL_RESULTS,
        PHPFHIRConstants::TYPE_NAME_UNITS_OF_TIME => PHPFHIRConstants::TYPE_CLASS_UNITS_OF_TIME,
        PHPFHIRConstants::TYPE_NAME_UNITS_OF_TIME_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_UNITS_OF_TIME_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_URI => PHPFHIRConstants::TYPE_CLASS_URI,
        PHPFHIRConstants::TYPE_NAME_URI_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_URI_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_UUID => PHPFHIRConstants::TYPE_CLASS_UUID,
        PHPFHIRConstants::TYPE_NAME_UUID_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_UUID_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET => PHPFHIRConstants::TYPE_CLASS_VALUE_SET,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_COMPOSE => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_COMPOSE,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_CONCEPT => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_CONCEPT,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_CONTAINS => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_CONTAINS,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_DEFINE => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_DEFINE,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_EXPANSION => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_EXPANSION,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_FILTER => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_FILTER,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_INCLUDE => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_INCLUDE,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_STATUS => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_STATUS,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_XML_ID_REF => PHPFHIRConstants::TYPE_CLASS_XML_ID_REF,
    ];

    /**
     * This is the list of resource types that are allowed to be contained within a Resource.Inline type
     * @var array
     */
    private static $_containableTypes = [
        PHPFHIRConstants::TYPE_NAME_ADVERSE_REACTION => PHPFHIRConstants::TYPE_CLASS_ADVERSE_REACTION,
        PHPFHIRConstants::TYPE_NAME_ALERT => PHPFHIRConstants::TYPE_CLASS_ALERT,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE,
        PHPFHIRConstants::TYPE_NAME_BINARY => PHPFHIRConstants::TYPE_CLASS_BINARY,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION => PHPFHIRConstants::TYPE_CLASS_COMPOSITION,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP,
        PHPFHIRConstants::TYPE_NAME_CONDITION => PHPFHIRConstants::TYPE_CLASS_CONDITION,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE,
        PHPFHIRConstants::TYPE_NAME_DEVICE => PHPFHIRConstants::TYPE_CLASS_DEVICE,
        PHPFHIRConstants::TYPE_NAME_DEVICE_OBSERVATION_REPORT => PHPFHIRConstants::TYPE_CLASS_DEVICE_OBSERVATION_REPORT,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_REPORT => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_REPORT,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_MANIFEST => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_MANIFEST,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER,
        PHPFHIRConstants::TYPE_NAME_FAMILY_HISTORY => PHPFHIRConstants::TYPE_CLASS_FAMILY_HISTORY,
        PHPFHIRConstants::TYPE_NAME_GROUP => PHPFHIRConstants::TYPE_CLASS_GROUP,
        PHPFHIRConstants::TYPE_NAME_IMAGING_STUDY => PHPFHIRConstants::TYPE_CLASS_IMAGING_STUDY,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION,
        PHPFHIRConstants::TYPE_NAME_LIST => PHPFHIRConstants::TYPE_CLASS_LIST,
        PHPFHIRConstants::TYPE_NAME_LOCATION => PHPFHIRConstants::TYPE_CLASS_LOCATION,
        PHPFHIRConstants::TYPE_NAME_MEDIA => PHPFHIRConstants::TYPE_CLASS_MEDIA,
        PHPFHIRConstants::TYPE_NAME_MEDICATION => PHPFHIRConstants::TYPE_CLASS_MEDICATION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ADMINISTRATION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_PRESCRIPTION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_STATEMENT => PHPFHIRConstants::TYPE_CLASS_MEDICATION_STATEMENT,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_HEADER => PHPFHIRConstants::TYPE_CLASS_MESSAGE_HEADER,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION => PHPFHIRConstants::TYPE_CLASS_OBSERVATION,
        PHPFHIRConstants::TYPE_NAME_OPERATION_OUTCOME => PHPFHIRConstants::TYPE_CLASS_OPERATION_OUTCOME,
        PHPFHIRConstants::TYPE_NAME_ORDER => PHPFHIRConstants::TYPE_CLASS_ORDER,
        PHPFHIRConstants::TYPE_NAME_ORDER_RESPONSE => PHPFHIRConstants::TYPE_CLASS_ORDER_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_ORGANIZATION => PHPFHIRConstants::TYPE_CLASS_ORGANIZATION,
        PHPFHIRConstants::TYPE_NAME_OTHER => PHPFHIRConstants::TYPE_CLASS_OTHER,
        PHPFHIRConstants::TYPE_NAME_PATIENT => PHPFHIRConstants::TYPE_CLASS_PATIENT,
        PHPFHIRConstants::TYPE_NAME_PRACTITIONER => PHPFHIRConstants::TYPE_CLASS_PRACTITIONER,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE => PHPFHIRConstants::TYPE_CLASS_PROCEDURE,
        PHPFHIRConstants::TYPE_NAME_PROFILE => PHPFHIRConstants::TYPE_CLASS_PROFILE,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE => PHPFHIRConstants::TYPE_CLASS_PROVENANCE,
        PHPFHIRConstants::TYPE_NAME_QUERY => PHPFHIRConstants::TYPE_CLASS_QUERY,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE,
        PHPFHIRConstants::TYPE_NAME_RELATED_PERSON => PHPFHIRConstants::TYPE_CLASS_RELATED_PERSON,
        PHPFHIRConstants::TYPE_NAME_SECURITY_EVENT => PHPFHIRConstants::TYPE_CLASS_SECURITY_EVENT,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN => PHPFHIRConstants::TYPE_CLASS_SPECIMEN,
        PHPFHIRConstants::TYPE_NAME_SUBSTANCE => PHPFHIRConstants::TYPE_CLASS_SUBSTANCE,
        PHPFHIRConstants::TYPE_NAME_SUPPLY => PHPFHIRConstants::TYPE_CLASS_SUPPLY,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET => PHPFHIRConstants::TYPE_CLASS_VALUE_SET,
    ];

    /**
     * Get fully qualified class name for FHIR Type name.  Returns null if type not found
     * @param string $typeName
     * @return string|null
     */
    public static function getTypeClass($typeName) {
        return (is_string($typeName) && isset(self::$_typeMap[$typeName])) ? self::$_typeMap[$typeName] : null;
    }

    /**
     * Returns the full internal class map
     * @return array
     */
    public static function getMap() {
        return self::$_typeMap;
    }

    /**
     * Returns the full list of containable resource types
     * @return array
     */
    public static function getContainableTypes() {
        return self::$_containableTypes;
    }

    /**
     * @param string $typeName Name of FHIR object reference by Resource.Inline
     * @return string|null Name of class as string or null if type is not contained in map
     */
    public static function getContainedTypeClassName($typeName)
    {
        return (is_string($typeName) && isset(self::$_containableTypes[$typeName])) ? self::$_containableTypes[$typeName] : null;
    }

    /**
     * Will attempt to determine if the provided value is or describes a containable resource type
     * @param object|string|array $type
     * @return bool
     * @throws \InvalidArgumentException
     */
    public static function isContainableResource($type) {
        $tt = gettype($type);
        if ('object' === $tt) {
            if ($type instanceof PHPFHIRTypeInterface) {
                return in_array('\\'.get_class($type), self::$_containableTypes, true);
            }
            if ($type instanceof \SimpleXMLElement) {
                return isset(self::$_containableTypes[$type->getName()]);
            }
            throw new \InvalidArgumentException(sprintf(
                'Expected "$type" to be instance of "\DCarbone\PHPFHIRGenerated\DSTU1\PHPFHIRTypeInterface" or "%s", saw "%s"',
                '\\SimpleXMLElement',
                get_class($type)
            ));
        }
        if ('string' === $tt) {
            return isset(self::$_containableTypes[$type]) || in_array('\\'.ltrim($type, '\\'), self::$_containableTypes, true);
        }
        if ('array' === $tt) {
            if (isset($type[PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE])) {
                return isset(self::$_containableTypes[$type[PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE]]);
            }
            return false;
        }

        throw new \InvalidArgumentException(sprintf(
            'Unable to process input of type "%s"',
            gettype($type)
        ));
    }

    /**
     * @param \SimpleXMLElement $sxe Parent element containing inline resource
     * @return \DCarbone\PHPFHIRGenerated\DSTU1\PHPFHIRContainedTypeInterface|null
     */
    public static function getContainedTypeFromXML(\SimpleXMLElement $sxe)
    {
        $typeName = $sxe->getName();
        $className = self::getContainedTypeClassName($typeName);
        if (null === $className) {
            throw self::createdInvalidContainedTypeException($typeName);
        }
        /** @var \DCarbone\PHPFHIRGenerated\DSTU1\PHPFHIRContainedTypeInterface $className */
        return $className::xmlUnserialize($sxe);
    }

    /**
     * @param array|null $data
     * @return \DCarbone\PHPFHIRGenerated\DSTU1\PHPFHIRContainedTypeInterface|null
     */
    public static function getContainedTypeFromArray($data)
    {
        if (null === $data) {
            return null;
        }
        if (!is_array($data)) {
            throw new \InvalidArgumentException(sprintf(
                '$data must be either an array or null, %s seen.',
                gettype($data)
            ));
        }
        if ([] === $data) {
            return null;
        }
        $resourceType = isset($data[PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE]) ? $data[PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE] : null;
        if (null === $resourceType) {
            throw new \DomainException(sprintf(
                'Unable to determine contained Resource type from input (missing "%s" key).  Keys: ["%s"]',
                PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE,
                implode('","', array_keys($data))
            ));
        }
        unset($data[PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE]);
        $className = self::getContainedTypeClassName($resourceType);
        if (null === $className) {
            throw self::createdInvalidContainedTypeException($resourceType);
        }
        return new $className($data);
    }

    /**
     * @param string $typeName
     * @return \UnexpectedValueException
     */
    private static function createdInvalidContainedTypeException($typeName) {
        return new \UnexpectedValueException(sprintf(
            'Type "%s" is not among the list of types allowed within a Resource.Inline',
            $typeName
        ));
    }
}
