<?php declare(strict_types=1);

namespace DCarbone\PHPFHIRGenerated\Versions\DSTU1;

/*!
 * This class was generated with the PHPFHIR library (https://github.com/dcarbone/php-fhir) using
 * class definitions from HL7 FHIR (https://www.hl7.org/fhir/)
 * 
 * Class creation date: February 1st, 2025 22:01+0000
 * 
 * PHPFHIR Copyright:
 * 
 * Copyright 2016-2025 Daniel Carbone (daniel.p.carbone@gmail.com)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 *
 * FHIR Copyright Notice:
 *
 *   Copyright (c) 2011-2013, HL7, Inc.
 *   All rights reserved.
 * 
 *   Redistribution and use in source and binary forms, with or without modification,
 *   are permitted provided that the following conditions are met:
 * 
 *    * Redistributions of source code must retain the above copyright notice, this
 *      list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *    * Neither the name of HL7 nor the names of its contributors may be used to
 *      endorse or promote products derived from this software without specific
 *      prior written permission.
 * 
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *   ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 *   IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 *   INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 *   NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 *   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 * 
 * 
 *   Generated on Tue, Sep 30, 2014 18:08+1000 for FHIR v0.0.82
 */

use DCarbone\PHPFHIRGenerated\Constants;
use DCarbone\PHPFHIRGenerated\Types\TypeInterface;
use DCarbone\PHPFHIRGenerated\Versions\VersionTypeMapInterface;

class VersionTypeMap implements VersionTypeMapInterface
{
    private const _TYPE_MAP = [
        VersionConstants::TYPE_NAME_ADDRESS => VersionConstants::TYPE_CLASS_ADDRESS,
        VersionConstants::TYPE_NAME_ADDRESS_USE => VersionConstants::TYPE_CLASS_ADDRESS_USE,
        VersionConstants::TYPE_NAME_ADDRESS_USE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_ADDRESS_USE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_ADVERSE_REACTION => VersionConstants::TYPE_CLASS_ADVERSE_REACTION,
        VersionConstants::TYPE_NAME_ADVERSE_REACTION_DOT_EXPOSURE => VersionConstants::TYPE_CLASS_ADVERSE_REACTION_DOT_EXPOSURE,
        VersionConstants::TYPE_NAME_ADVERSE_REACTION_DOT_SYMPTOM => VersionConstants::TYPE_CLASS_ADVERSE_REACTION_DOT_SYMPTOM,
        VersionConstants::TYPE_NAME_AGE => VersionConstants::TYPE_CLASS_AGE,
        VersionConstants::TYPE_NAME_AGGREGATION_MODE => VersionConstants::TYPE_CLASS_AGGREGATION_MODE,
        VersionConstants::TYPE_NAME_AGGREGATION_MODE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_AGGREGATION_MODE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_ALERT => VersionConstants::TYPE_CLASS_ALERT,
        VersionConstants::TYPE_NAME_ALERT_STATUS => VersionConstants::TYPE_CLASS_ALERT_STATUS,
        VersionConstants::TYPE_NAME_ALERT_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_ALERT_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_ALLERGY_INTOLERANCE => VersionConstants::TYPE_CLASS_ALLERGY_INTOLERANCE,
        VersionConstants::TYPE_NAME_ATTACHMENT => VersionConstants::TYPE_CLASS_ATTACHMENT,
        VersionConstants::TYPE_NAME_BACKBONE_ELEMENT => VersionConstants::TYPE_CLASS_BACKBONE_ELEMENT,
        VersionConstants::TYPE_NAME_BASE_64BINARY => VersionConstants::TYPE_CLASS_BASE_64BINARY,
        VersionConstants::TYPE_NAME_BASE_64BINARY_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_BASE_64BINARY_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_BINARY => VersionConstants::TYPE_CLASS_BINARY,
        VersionConstants::TYPE_NAME_BINDING_CONFORMANCE => VersionConstants::TYPE_CLASS_BINDING_CONFORMANCE,
        VersionConstants::TYPE_NAME_BINDING_CONFORMANCE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_BINDING_CONFORMANCE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_BOOLEAN => VersionConstants::TYPE_CLASS_BOOLEAN,
        VersionConstants::TYPE_NAME_BOOLEAN_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_BOOLEAN_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_CARE_PLAN => VersionConstants::TYPE_CLASS_CARE_PLAN,
        VersionConstants::TYPE_NAME_CARE_PLAN_DOT_ACTIVITY => VersionConstants::TYPE_CLASS_CARE_PLAN_DOT_ACTIVITY,
        VersionConstants::TYPE_NAME_CARE_PLAN_DOT_GOAL => VersionConstants::TYPE_CLASS_CARE_PLAN_DOT_GOAL,
        VersionConstants::TYPE_NAME_CARE_PLAN_DOT_PARTICIPANT => VersionConstants::TYPE_CLASS_CARE_PLAN_DOT_PARTICIPANT,
        VersionConstants::TYPE_NAME_CARE_PLAN_DOT_SIMPLE => VersionConstants::TYPE_CLASS_CARE_PLAN_DOT_SIMPLE,
        VersionConstants::TYPE_NAME_CARE_PLAN_ACTIVITY_CATEGORY => VersionConstants::TYPE_CLASS_CARE_PLAN_ACTIVITY_CATEGORY,
        VersionConstants::TYPE_NAME_CARE_PLAN_ACTIVITY_CATEGORY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CARE_PLAN_ACTIVITY_CATEGORY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CARE_PLAN_ACTIVITY_STATUS => VersionConstants::TYPE_CLASS_CARE_PLAN_ACTIVITY_STATUS,
        VersionConstants::TYPE_NAME_CARE_PLAN_ACTIVITY_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CARE_PLAN_ACTIVITY_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CARE_PLAN_GOAL_STATUS => VersionConstants::TYPE_CLASS_CARE_PLAN_GOAL_STATUS,
        VersionConstants::TYPE_NAME_CARE_PLAN_GOAL_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CARE_PLAN_GOAL_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CARE_PLAN_STATUS => VersionConstants::TYPE_CLASS_CARE_PLAN_STATUS,
        VersionConstants::TYPE_NAME_CARE_PLAN_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CARE_PLAN_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CAUSALITY_EXPECTATION => VersionConstants::TYPE_CLASS_CAUSALITY_EXPECTATION,
        VersionConstants::TYPE_NAME_CAUSALITY_EXPECTATION_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CAUSALITY_EXPECTATION_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CODE => VersionConstants::TYPE_CLASS_CODE,
        VersionConstants::TYPE_NAME_CODE_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_CODE_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_CODEABLE_CONCEPT => VersionConstants::TYPE_CLASS_CODEABLE_CONCEPT,
        VersionConstants::TYPE_NAME_CODING => VersionConstants::TYPE_CLASS_CODING,
        VersionConstants::TYPE_NAME_COMPOSITION => VersionConstants::TYPE_CLASS_COMPOSITION,
        VersionConstants::TYPE_NAME_COMPOSITION_DOT_ATTESTER => VersionConstants::TYPE_CLASS_COMPOSITION_DOT_ATTESTER,
        VersionConstants::TYPE_NAME_COMPOSITION_DOT_EVENT => VersionConstants::TYPE_CLASS_COMPOSITION_DOT_EVENT,
        VersionConstants::TYPE_NAME_COMPOSITION_DOT_SECTION => VersionConstants::TYPE_CLASS_COMPOSITION_DOT_SECTION,
        VersionConstants::TYPE_NAME_COMPOSITION_ATTESTATION_MODE => VersionConstants::TYPE_CLASS_COMPOSITION_ATTESTATION_MODE,
        VersionConstants::TYPE_NAME_COMPOSITION_ATTESTATION_MODE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_COMPOSITION_ATTESTATION_MODE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_COMPOSITION_STATUS => VersionConstants::TYPE_CLASS_COMPOSITION_STATUS,
        VersionConstants::TYPE_NAME_COMPOSITION_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_COMPOSITION_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CONCEPT_MAP => VersionConstants::TYPE_CLASS_CONCEPT_MAP,
        VersionConstants::TYPE_NAME_CONCEPT_MAP_DOT_CONCEPT => VersionConstants::TYPE_CLASS_CONCEPT_MAP_DOT_CONCEPT,
        VersionConstants::TYPE_NAME_CONCEPT_MAP_DOT_DEPENDS_ON => VersionConstants::TYPE_CLASS_CONCEPT_MAP_DOT_DEPENDS_ON,
        VersionConstants::TYPE_NAME_CONCEPT_MAP_DOT_MAP => VersionConstants::TYPE_CLASS_CONCEPT_MAP_DOT_MAP,
        VersionConstants::TYPE_NAME_CONCEPT_MAP_EQUIVALENCE => VersionConstants::TYPE_CLASS_CONCEPT_MAP_EQUIVALENCE,
        VersionConstants::TYPE_NAME_CONCEPT_MAP_EQUIVALENCE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CONCEPT_MAP_EQUIVALENCE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CONDITION => VersionConstants::TYPE_CLASS_CONDITION,
        VersionConstants::TYPE_NAME_CONDITION_DOT_EVIDENCE => VersionConstants::TYPE_CLASS_CONDITION_DOT_EVIDENCE,
        VersionConstants::TYPE_NAME_CONDITION_DOT_LOCATION => VersionConstants::TYPE_CLASS_CONDITION_DOT_LOCATION,
        VersionConstants::TYPE_NAME_CONDITION_DOT_RELATED_ITEM => VersionConstants::TYPE_CLASS_CONDITION_DOT_RELATED_ITEM,
        VersionConstants::TYPE_NAME_CONDITION_DOT_STAGE => VersionConstants::TYPE_CLASS_CONDITION_DOT_STAGE,
        VersionConstants::TYPE_NAME_CONDITION_RELATIONSHIP_TYPE => VersionConstants::TYPE_CLASS_CONDITION_RELATIONSHIP_TYPE,
        VersionConstants::TYPE_NAME_CONDITION_RELATIONSHIP_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CONDITION_RELATIONSHIP_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CONDITION_STATUS => VersionConstants::TYPE_CLASS_CONDITION_STATUS,
        VersionConstants::TYPE_NAME_CONDITION_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CONDITION_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CONFORMANCE => VersionConstants::TYPE_CLASS_CONFORMANCE,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_CERTIFICATE => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_CERTIFICATE,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_DOCUMENT => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_DOCUMENT,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_EVENT => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_EVENT,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_IMPLEMENTATION => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_IMPLEMENTATION,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_MESSAGING => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_MESSAGING,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_OPERATION => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_OPERATION,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_OPERATION_1 => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_OPERATION_1,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_QUERY => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_QUERY,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_RESOURCE => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_RESOURCE,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_REST => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_REST,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_SEARCH_PARAM => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_SEARCH_PARAM,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_SECURITY => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_SECURITY,
        VersionConstants::TYPE_NAME_CONFORMANCE_DOT_SOFTWARE => VersionConstants::TYPE_CLASS_CONFORMANCE_DOT_SOFTWARE,
        VersionConstants::TYPE_NAME_CONFORMANCE_EVENT_MODE => VersionConstants::TYPE_CLASS_CONFORMANCE_EVENT_MODE,
        VersionConstants::TYPE_NAME_CONFORMANCE_EVENT_MODE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CONFORMANCE_EVENT_MODE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CONFORMANCE_STATEMENT_STATUS => VersionConstants::TYPE_CLASS_CONFORMANCE_STATEMENT_STATUS,
        VersionConstants::TYPE_NAME_CONFORMANCE_STATEMENT_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CONFORMANCE_STATEMENT_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CONSTRAINT_SEVERITY => VersionConstants::TYPE_CLASS_CONSTRAINT_SEVERITY,
        VersionConstants::TYPE_NAME_CONSTRAINT_SEVERITY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CONSTRAINT_SEVERITY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CONTACT => VersionConstants::TYPE_CLASS_CONTACT,
        VersionConstants::TYPE_NAME_CONTACT_SYSTEM => VersionConstants::TYPE_CLASS_CONTACT_SYSTEM,
        VersionConstants::TYPE_NAME_CONTACT_SYSTEM_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CONTACT_SYSTEM_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_CONTACT_USE => VersionConstants::TYPE_CLASS_CONTACT_USE,
        VersionConstants::TYPE_NAME_CONTACT_USE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CONTACT_USE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_COUNT => VersionConstants::TYPE_CLASS_COUNT,
        VersionConstants::TYPE_NAME_CRITICALITY => VersionConstants::TYPE_CLASS_CRITICALITY,
        VersionConstants::TYPE_NAME_CRITICALITY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_CRITICALITY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_DATE => VersionConstants::TYPE_CLASS_DATE,
        VersionConstants::TYPE_NAME_DATE_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_DATE_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_DATE_TIME => VersionConstants::TYPE_CLASS_DATE_TIME,
        VersionConstants::TYPE_NAME_DATE_TIME_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_DATE_TIME_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_DECIMAL => VersionConstants::TYPE_CLASS_DECIMAL,
        VersionConstants::TYPE_NAME_DECIMAL_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_DECIMAL_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_DEVICE => VersionConstants::TYPE_CLASS_DEVICE,
        VersionConstants::TYPE_NAME_DEVICE_OBSERVATION_REPORT => VersionConstants::TYPE_CLASS_DEVICE_OBSERVATION_REPORT,
        VersionConstants::TYPE_NAME_DEVICE_OBSERVATION_REPORT_DOT_CHANNEL => VersionConstants::TYPE_CLASS_DEVICE_OBSERVATION_REPORT_DOT_CHANNEL,
        VersionConstants::TYPE_NAME_DEVICE_OBSERVATION_REPORT_DOT_METRIC => VersionConstants::TYPE_CLASS_DEVICE_OBSERVATION_REPORT_DOT_METRIC,
        VersionConstants::TYPE_NAME_DEVICE_OBSERVATION_REPORT_DOT_VIRTUAL_DEVICE => VersionConstants::TYPE_CLASS_DEVICE_OBSERVATION_REPORT_DOT_VIRTUAL_DEVICE,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_ORDER => VersionConstants::TYPE_CLASS_DIAGNOSTIC_ORDER,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_ORDER_DOT_EVENT => VersionConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_DOT_EVENT,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_ORDER_DOT_ITEM => VersionConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_DOT_ITEM,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_ORDER_PRIORITY => VersionConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_PRIORITY,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_ORDER_PRIORITY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_PRIORITY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_ORDER_STATUS => VersionConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_STATUS,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_ORDER_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_REPORT => VersionConstants::TYPE_CLASS_DIAGNOSTIC_REPORT,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_REPORT_DOT_IMAGE => VersionConstants::TYPE_CLASS_DIAGNOSTIC_REPORT_DOT_IMAGE,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_REPORT_STATUS => VersionConstants::TYPE_CLASS_DIAGNOSTIC_REPORT_STATUS,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_REPORT_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_DIAGNOSTIC_REPORT_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_DISTANCE => VersionConstants::TYPE_CLASS_DISTANCE,
        VersionConstants::TYPE_NAME_DOCUMENT_MANIFEST => VersionConstants::TYPE_CLASS_DOCUMENT_MANIFEST,
        VersionConstants::TYPE_NAME_DOCUMENT_MODE => VersionConstants::TYPE_CLASS_DOCUMENT_MODE,
        VersionConstants::TYPE_NAME_DOCUMENT_MODE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_DOCUMENT_MODE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_DOCUMENT_REFERENCE => VersionConstants::TYPE_CLASS_DOCUMENT_REFERENCE,
        VersionConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_CONTEXT => VersionConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_CONTEXT,
        VersionConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_PARAMETER => VersionConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_PARAMETER,
        VersionConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_RELATES_TO => VersionConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_RELATES_TO,
        VersionConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_SERVICE => VersionConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_SERVICE,
        VersionConstants::TYPE_NAME_DOCUMENT_REFERENCE_STATUS => VersionConstants::TYPE_CLASS_DOCUMENT_REFERENCE_STATUS,
        VersionConstants::TYPE_NAME_DOCUMENT_REFERENCE_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_DOCUMENT_REFERENCE_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_DOCUMENT_RELATIONSHIP_TYPE => VersionConstants::TYPE_CLASS_DOCUMENT_RELATIONSHIP_TYPE,
        VersionConstants::TYPE_NAME_DOCUMENT_RELATIONSHIP_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_DOCUMENT_RELATIONSHIP_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_DURATION => VersionConstants::TYPE_CLASS_DURATION,
        VersionConstants::TYPE_NAME_ELEMENT => VersionConstants::TYPE_CLASS_ELEMENT,
        VersionConstants::TYPE_NAME_ENCOUNTER => VersionConstants::TYPE_CLASS_ENCOUNTER,
        VersionConstants::TYPE_NAME_ENCOUNTER_DOT_ACCOMODATION => VersionConstants::TYPE_CLASS_ENCOUNTER_DOT_ACCOMODATION,
        VersionConstants::TYPE_NAME_ENCOUNTER_DOT_HOSPITALIZATION => VersionConstants::TYPE_CLASS_ENCOUNTER_DOT_HOSPITALIZATION,
        VersionConstants::TYPE_NAME_ENCOUNTER_DOT_LOCATION => VersionConstants::TYPE_CLASS_ENCOUNTER_DOT_LOCATION,
        VersionConstants::TYPE_NAME_ENCOUNTER_DOT_PARTICIPANT => VersionConstants::TYPE_CLASS_ENCOUNTER_DOT_PARTICIPANT,
        VersionConstants::TYPE_NAME_ENCOUNTER_CLASS => VersionConstants::TYPE_CLASS_ENCOUNTER_CLASS,
        VersionConstants::TYPE_NAME_ENCOUNTER_CLASS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_ENCOUNTER_CLASS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_ENCOUNTER_STATE => VersionConstants::TYPE_CLASS_ENCOUNTER_STATE,
        VersionConstants::TYPE_NAME_ENCOUNTER_STATE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_ENCOUNTER_STATE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_EVENT_TIMING => VersionConstants::TYPE_CLASS_EVENT_TIMING,
        VersionConstants::TYPE_NAME_EVENT_TIMING_HYPHEN_LIST => VersionConstants::TYPE_CLASS_EVENT_TIMING_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_EXPOSURE_TYPE => VersionConstants::TYPE_CLASS_EXPOSURE_TYPE,
        VersionConstants::TYPE_NAME_EXPOSURE_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_EXPOSURE_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_EXTENSION => VersionConstants::TYPE_CLASS_EXTENSION,
        VersionConstants::TYPE_NAME_EXTENSION_CONTEXT => VersionConstants::TYPE_CLASS_EXTENSION_CONTEXT,
        VersionConstants::TYPE_NAME_EXTENSION_CONTEXT_HYPHEN_LIST => VersionConstants::TYPE_CLASS_EXTENSION_CONTEXT_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_FAMILY_HISTORY => VersionConstants::TYPE_CLASS_FAMILY_HISTORY,
        VersionConstants::TYPE_NAME_FAMILY_HISTORY_DOT_CONDITION => VersionConstants::TYPE_CLASS_FAMILY_HISTORY_DOT_CONDITION,
        VersionConstants::TYPE_NAME_FAMILY_HISTORY_DOT_RELATION => VersionConstants::TYPE_CLASS_FAMILY_HISTORY_DOT_RELATION,
        VersionConstants::TYPE_NAME_FILTER_OPERATOR => VersionConstants::TYPE_CLASS_FILTER_OPERATOR,
        VersionConstants::TYPE_NAME_FILTER_OPERATOR_HYPHEN_LIST => VersionConstants::TYPE_CLASS_FILTER_OPERATOR_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_GROUP => VersionConstants::TYPE_CLASS_GROUP,
        VersionConstants::TYPE_NAME_GROUP_DOT_CHARACTERISTIC => VersionConstants::TYPE_CLASS_GROUP_DOT_CHARACTERISTIC,
        VersionConstants::TYPE_NAME_GROUP_TYPE => VersionConstants::TYPE_CLASS_GROUP_TYPE,
        VersionConstants::TYPE_NAME_GROUP_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_GROUP_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_HIERARCHICAL_RELATIONSHIP_TYPE => VersionConstants::TYPE_CLASS_HIERARCHICAL_RELATIONSHIP_TYPE,
        VersionConstants::TYPE_NAME_HIERARCHICAL_RELATIONSHIP_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_HIERARCHICAL_RELATIONSHIP_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_HUMAN_NAME => VersionConstants::TYPE_CLASS_HUMAN_NAME,
        VersionConstants::TYPE_NAME_ID => VersionConstants::TYPE_CLASS_ID,
        VersionConstants::TYPE_NAME_ID_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_ID_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_IDENTIFIER => VersionConstants::TYPE_CLASS_IDENTIFIER,
        VersionConstants::TYPE_NAME_IDENTIFIER_USE => VersionConstants::TYPE_CLASS_IDENTIFIER_USE,
        VersionConstants::TYPE_NAME_IDENTIFIER_USE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_IDENTIFIER_USE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_IMAGING_MODALITY => VersionConstants::TYPE_CLASS_IMAGING_MODALITY,
        VersionConstants::TYPE_NAME_IMAGING_MODALITY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_IMAGING_MODALITY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_IMAGING_STUDY => VersionConstants::TYPE_CLASS_IMAGING_STUDY,
        VersionConstants::TYPE_NAME_IMAGING_STUDY_DOT_INSTANCE => VersionConstants::TYPE_CLASS_IMAGING_STUDY_DOT_INSTANCE,
        VersionConstants::TYPE_NAME_IMAGING_STUDY_DOT_SERIES => VersionConstants::TYPE_CLASS_IMAGING_STUDY_DOT_SERIES,
        VersionConstants::TYPE_NAME_IMMUNIZATION => VersionConstants::TYPE_CLASS_IMMUNIZATION,
        VersionConstants::TYPE_NAME_IMMUNIZATION_DOT_EXPLANATION => VersionConstants::TYPE_CLASS_IMMUNIZATION_DOT_EXPLANATION,
        VersionConstants::TYPE_NAME_IMMUNIZATION_DOT_REACTION => VersionConstants::TYPE_CLASS_IMMUNIZATION_DOT_REACTION,
        VersionConstants::TYPE_NAME_IMMUNIZATION_DOT_VACCINATION_PROTOCOL => VersionConstants::TYPE_CLASS_IMMUNIZATION_DOT_VACCINATION_PROTOCOL,
        VersionConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION => VersionConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION,
        VersionConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION_DOT_DATE_CRITERION => VersionConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION_DOT_DATE_CRITERION,
        VersionConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION_DOT_PROTOCOL => VersionConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION_DOT_PROTOCOL,
        VersionConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION_DOT_RECOMMENDATION => VersionConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION_DOT_RECOMMENDATION,
        VersionConstants::TYPE_NAME_INSTANCE_AVAILABILITY => VersionConstants::TYPE_CLASS_INSTANCE_AVAILABILITY,
        VersionConstants::TYPE_NAME_INSTANCE_AVAILABILITY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_INSTANCE_AVAILABILITY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_INSTANT => VersionConstants::TYPE_CLASS_INSTANT,
        VersionConstants::TYPE_NAME_INSTANT_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_INSTANT_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_INTEGER => VersionConstants::TYPE_CLASS_INTEGER,
        VersionConstants::TYPE_NAME_INTEGER_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_INTEGER_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_ISSUE_SEVERITY => VersionConstants::TYPE_CLASS_ISSUE_SEVERITY,
        VersionConstants::TYPE_NAME_ISSUE_SEVERITY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_ISSUE_SEVERITY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_LINK_TYPE => VersionConstants::TYPE_CLASS_LINK_TYPE,
        VersionConstants::TYPE_NAME_LINK_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_LINK_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_LIST => VersionConstants::TYPE_CLASS_LIST,
        VersionConstants::TYPE_NAME_LIST_DOT_ENTRY => VersionConstants::TYPE_CLASS_LIST_DOT_ENTRY,
        VersionConstants::TYPE_NAME_LIST_MODE => VersionConstants::TYPE_CLASS_LIST_MODE,
        VersionConstants::TYPE_NAME_LIST_MODE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_LIST_MODE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_LOCATION => VersionConstants::TYPE_CLASS_LOCATION,
        VersionConstants::TYPE_NAME_LOCATION_DOT_POSITION => VersionConstants::TYPE_CLASS_LOCATION_DOT_POSITION,
        VersionConstants::TYPE_NAME_LOCATION_MODE => VersionConstants::TYPE_CLASS_LOCATION_MODE,
        VersionConstants::TYPE_NAME_LOCATION_MODE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_LOCATION_MODE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_LOCATION_STATUS => VersionConstants::TYPE_CLASS_LOCATION_STATUS,
        VersionConstants::TYPE_NAME_LOCATION_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_LOCATION_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_MEDIA => VersionConstants::TYPE_CLASS_MEDIA,
        VersionConstants::TYPE_NAME_MEDIA_TYPE => VersionConstants::TYPE_CLASS_MEDIA_TYPE,
        VersionConstants::TYPE_NAME_MEDIA_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_MEDIA_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_MEDICATION => VersionConstants::TYPE_CLASS_MEDICATION,
        VersionConstants::TYPE_NAME_MEDICATION_DOT_CONTENT => VersionConstants::TYPE_CLASS_MEDICATION_DOT_CONTENT,
        VersionConstants::TYPE_NAME_MEDICATION_DOT_INGREDIENT => VersionConstants::TYPE_CLASS_MEDICATION_DOT_INGREDIENT,
        VersionConstants::TYPE_NAME_MEDICATION_DOT_PACKAGE => VersionConstants::TYPE_CLASS_MEDICATION_DOT_PACKAGE,
        VersionConstants::TYPE_NAME_MEDICATION_DOT_PRODUCT => VersionConstants::TYPE_CLASS_MEDICATION_DOT_PRODUCT,
        VersionConstants::TYPE_NAME_MEDICATION_ADMINISTRATION => VersionConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION,
        VersionConstants::TYPE_NAME_MEDICATION_ADMINISTRATION_DOT_DOSAGE => VersionConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION_DOT_DOSAGE,
        VersionConstants::TYPE_NAME_MEDICATION_ADMINISTRATION_STATUS => VersionConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION_STATUS,
        VersionConstants::TYPE_NAME_MEDICATION_ADMINISTRATION_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_MEDICATION_DISPENSE => VersionConstants::TYPE_CLASS_MEDICATION_DISPENSE,
        VersionConstants::TYPE_NAME_MEDICATION_DISPENSE_DOT_DISPENSE => VersionConstants::TYPE_CLASS_MEDICATION_DISPENSE_DOT_DISPENSE,
        VersionConstants::TYPE_NAME_MEDICATION_DISPENSE_DOT_DOSAGE => VersionConstants::TYPE_CLASS_MEDICATION_DISPENSE_DOT_DOSAGE,
        VersionConstants::TYPE_NAME_MEDICATION_DISPENSE_DOT_SUBSTITUTION => VersionConstants::TYPE_CLASS_MEDICATION_DISPENSE_DOT_SUBSTITUTION,
        VersionConstants::TYPE_NAME_MEDICATION_DISPENSE_STATUS => VersionConstants::TYPE_CLASS_MEDICATION_DISPENSE_STATUS,
        VersionConstants::TYPE_NAME_MEDICATION_DISPENSE_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_MEDICATION_DISPENSE_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_MEDICATION_KIND => VersionConstants::TYPE_CLASS_MEDICATION_KIND,
        VersionConstants::TYPE_NAME_MEDICATION_KIND_HYPHEN_LIST => VersionConstants::TYPE_CLASS_MEDICATION_KIND_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_MEDICATION_PRESCRIPTION => VersionConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION,
        VersionConstants::TYPE_NAME_MEDICATION_PRESCRIPTION_DOT_DISPENSE => VersionConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION_DOT_DISPENSE,
        VersionConstants::TYPE_NAME_MEDICATION_PRESCRIPTION_DOT_DOSAGE_INSTRUCTION => VersionConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION_DOT_DOSAGE_INSTRUCTION,
        VersionConstants::TYPE_NAME_MEDICATION_PRESCRIPTION_DOT_SUBSTITUTION => VersionConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION_DOT_SUBSTITUTION,
        VersionConstants::TYPE_NAME_MEDICATION_PRESCRIPTION_STATUS => VersionConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION_STATUS,
        VersionConstants::TYPE_NAME_MEDICATION_PRESCRIPTION_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_MEDICATION_STATEMENT => VersionConstants::TYPE_CLASS_MEDICATION_STATEMENT,
        VersionConstants::TYPE_NAME_MEDICATION_STATEMENT_DOT_DOSAGE => VersionConstants::TYPE_CLASS_MEDICATION_STATEMENT_DOT_DOSAGE,
        VersionConstants::TYPE_NAME_MESSAGE_HEADER => VersionConstants::TYPE_CLASS_MESSAGE_HEADER,
        VersionConstants::TYPE_NAME_MESSAGE_HEADER_DOT_DESTINATION => VersionConstants::TYPE_CLASS_MESSAGE_HEADER_DOT_DESTINATION,
        VersionConstants::TYPE_NAME_MESSAGE_HEADER_DOT_RESPONSE => VersionConstants::TYPE_CLASS_MESSAGE_HEADER_DOT_RESPONSE,
        VersionConstants::TYPE_NAME_MESSAGE_HEADER_DOT_SOURCE => VersionConstants::TYPE_CLASS_MESSAGE_HEADER_DOT_SOURCE,
        VersionConstants::TYPE_NAME_MESSAGE_SIGNIFICANCE_CATEGORY => VersionConstants::TYPE_CLASS_MESSAGE_SIGNIFICANCE_CATEGORY,
        VersionConstants::TYPE_NAME_MESSAGE_SIGNIFICANCE_CATEGORY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_MESSAGE_SIGNIFICANCE_CATEGORY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_MODALITY => VersionConstants::TYPE_CLASS_MODALITY,
        VersionConstants::TYPE_NAME_MODALITY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_MODALITY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_MONEY => VersionConstants::TYPE_CLASS_MONEY,
        VersionConstants::TYPE_NAME_NAME_USE => VersionConstants::TYPE_CLASS_NAME_USE,
        VersionConstants::TYPE_NAME_NAME_USE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_NAME_USE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_NARRATIVE => VersionConstants::TYPE_CLASS_NARRATIVE,
        VersionConstants::TYPE_NAME_NARRATIVE_STATUS => VersionConstants::TYPE_CLASS_NARRATIVE_STATUS,
        VersionConstants::TYPE_NAME_NARRATIVE_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_NARRATIVE_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_OBSERVATION => VersionConstants::TYPE_CLASS_OBSERVATION,
        VersionConstants::TYPE_NAME_OBSERVATION_DOT_REFERENCE_RANGE => VersionConstants::TYPE_CLASS_OBSERVATION_DOT_REFERENCE_RANGE,
        VersionConstants::TYPE_NAME_OBSERVATION_DOT_RELATED => VersionConstants::TYPE_CLASS_OBSERVATION_DOT_RELATED,
        VersionConstants::TYPE_NAME_OBSERVATION_RELATIONSHIP_TYPE => VersionConstants::TYPE_CLASS_OBSERVATION_RELATIONSHIP_TYPE,
        VersionConstants::TYPE_NAME_OBSERVATION_RELATIONSHIP_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_OBSERVATION_RELATIONSHIP_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_OBSERVATION_RELIABILITY => VersionConstants::TYPE_CLASS_OBSERVATION_RELIABILITY,
        VersionConstants::TYPE_NAME_OBSERVATION_RELIABILITY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_OBSERVATION_RELIABILITY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_OBSERVATION_STATUS => VersionConstants::TYPE_CLASS_OBSERVATION_STATUS,
        VersionConstants::TYPE_NAME_OBSERVATION_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_OBSERVATION_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_OID => VersionConstants::TYPE_CLASS_OID,
        VersionConstants::TYPE_NAME_OID_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_OID_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_OPERATION_OUTCOME => VersionConstants::TYPE_CLASS_OPERATION_OUTCOME,
        VersionConstants::TYPE_NAME_OPERATION_OUTCOME_DOT_ISSUE => VersionConstants::TYPE_CLASS_OPERATION_OUTCOME_DOT_ISSUE,
        VersionConstants::TYPE_NAME_ORDER => VersionConstants::TYPE_CLASS_ORDER,
        VersionConstants::TYPE_NAME_ORDER_DOT_WHEN => VersionConstants::TYPE_CLASS_ORDER_DOT_WHEN,
        VersionConstants::TYPE_NAME_ORDER_OUTCOME_STATUS => VersionConstants::TYPE_CLASS_ORDER_OUTCOME_STATUS,
        VersionConstants::TYPE_NAME_ORDER_OUTCOME_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_ORDER_OUTCOME_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_ORDER_RESPONSE => VersionConstants::TYPE_CLASS_ORDER_RESPONSE,
        VersionConstants::TYPE_NAME_ORGANIZATION => VersionConstants::TYPE_CLASS_ORGANIZATION,
        VersionConstants::TYPE_NAME_ORGANIZATION_DOT_CONTACT => VersionConstants::TYPE_CLASS_ORGANIZATION_DOT_CONTACT,
        VersionConstants::TYPE_NAME_OTHER => VersionConstants::TYPE_CLASS_OTHER,
        VersionConstants::TYPE_NAME_PATIENT => VersionConstants::TYPE_CLASS_PATIENT,
        VersionConstants::TYPE_NAME_PATIENT_DOT_ANIMAL => VersionConstants::TYPE_CLASS_PATIENT_DOT_ANIMAL,
        VersionConstants::TYPE_NAME_PATIENT_DOT_CONTACT => VersionConstants::TYPE_CLASS_PATIENT_DOT_CONTACT,
        VersionConstants::TYPE_NAME_PATIENT_DOT_LINK => VersionConstants::TYPE_CLASS_PATIENT_DOT_LINK,
        VersionConstants::TYPE_NAME_PERIOD => VersionConstants::TYPE_CLASS_PERIOD,
        VersionConstants::TYPE_NAME_PRACTITIONER => VersionConstants::TYPE_CLASS_PRACTITIONER,
        VersionConstants::TYPE_NAME_PRACTITIONER_DOT_QUALIFICATION => VersionConstants::TYPE_CLASS_PRACTITIONER_DOT_QUALIFICATION,
        VersionConstants::TYPE_NAME_PROCEDURE => VersionConstants::TYPE_CLASS_PROCEDURE,
        VersionConstants::TYPE_NAME_PROCEDURE_DOT_PERFORMER => VersionConstants::TYPE_CLASS_PROCEDURE_DOT_PERFORMER,
        VersionConstants::TYPE_NAME_PROCEDURE_DOT_RELATED_ITEM => VersionConstants::TYPE_CLASS_PROCEDURE_DOT_RELATED_ITEM,
        VersionConstants::TYPE_NAME_PROCEDURE_RELATIONSHIP_TYPE => VersionConstants::TYPE_CLASS_PROCEDURE_RELATIONSHIP_TYPE,
        VersionConstants::TYPE_NAME_PROCEDURE_RELATIONSHIP_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_PROCEDURE_RELATIONSHIP_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_PROFILE => VersionConstants::TYPE_CLASS_PROFILE,
        VersionConstants::TYPE_NAME_PROFILE_DOT_BINDING => VersionConstants::TYPE_CLASS_PROFILE_DOT_BINDING,
        VersionConstants::TYPE_NAME_PROFILE_DOT_CONSTRAINT => VersionConstants::TYPE_CLASS_PROFILE_DOT_CONSTRAINT,
        VersionConstants::TYPE_NAME_PROFILE_DOT_DEFINITION => VersionConstants::TYPE_CLASS_PROFILE_DOT_DEFINITION,
        VersionConstants::TYPE_NAME_PROFILE_DOT_ELEMENT => VersionConstants::TYPE_CLASS_PROFILE_DOT_ELEMENT,
        VersionConstants::TYPE_NAME_PROFILE_DOT_EXTENSION_DEFN => VersionConstants::TYPE_CLASS_PROFILE_DOT_EXTENSION_DEFN,
        VersionConstants::TYPE_NAME_PROFILE_DOT_MAPPING => VersionConstants::TYPE_CLASS_PROFILE_DOT_MAPPING,
        VersionConstants::TYPE_NAME_PROFILE_DOT_MAPPING_1 => VersionConstants::TYPE_CLASS_PROFILE_DOT_MAPPING_1,
        VersionConstants::TYPE_NAME_PROFILE_DOT_QUERY => VersionConstants::TYPE_CLASS_PROFILE_DOT_QUERY,
        VersionConstants::TYPE_NAME_PROFILE_DOT_SEARCH_PARAM => VersionConstants::TYPE_CLASS_PROFILE_DOT_SEARCH_PARAM,
        VersionConstants::TYPE_NAME_PROFILE_DOT_SLICING => VersionConstants::TYPE_CLASS_PROFILE_DOT_SLICING,
        VersionConstants::TYPE_NAME_PROFILE_DOT_STRUCTURE => VersionConstants::TYPE_CLASS_PROFILE_DOT_STRUCTURE,
        VersionConstants::TYPE_NAME_PROFILE_DOT_TYPE => VersionConstants::TYPE_CLASS_PROFILE_DOT_TYPE,
        VersionConstants::TYPE_NAME_PROPERTY_REPRESENTATION => VersionConstants::TYPE_CLASS_PROPERTY_REPRESENTATION,
        VersionConstants::TYPE_NAME_PROPERTY_REPRESENTATION_HYPHEN_LIST => VersionConstants::TYPE_CLASS_PROPERTY_REPRESENTATION_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_PROVENANCE => VersionConstants::TYPE_CLASS_PROVENANCE,
        VersionConstants::TYPE_NAME_PROVENANCE_DOT_AGENT => VersionConstants::TYPE_CLASS_PROVENANCE_DOT_AGENT,
        VersionConstants::TYPE_NAME_PROVENANCE_DOT_ENTITY => VersionConstants::TYPE_CLASS_PROVENANCE_DOT_ENTITY,
        VersionConstants::TYPE_NAME_PROVENANCE_ENTITY_ROLE => VersionConstants::TYPE_CLASS_PROVENANCE_ENTITY_ROLE,
        VersionConstants::TYPE_NAME_PROVENANCE_ENTITY_ROLE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_PROVENANCE_ENTITY_ROLE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_QUANTITY => VersionConstants::TYPE_CLASS_QUANTITY,
        VersionConstants::TYPE_NAME_QUANTITY_COMPARARATOR => VersionConstants::TYPE_CLASS_QUANTITY_COMPARARATOR,
        VersionConstants::TYPE_NAME_QUANTITY_COMPARARATOR_HYPHEN_LIST => VersionConstants::TYPE_CLASS_QUANTITY_COMPARARATOR_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_QUERY => VersionConstants::TYPE_CLASS_QUERY,
        VersionConstants::TYPE_NAME_QUERY_DOT_RESPONSE => VersionConstants::TYPE_CLASS_QUERY_DOT_RESPONSE,
        VersionConstants::TYPE_NAME_QUERY_OUTCOME => VersionConstants::TYPE_CLASS_QUERY_OUTCOME,
        VersionConstants::TYPE_NAME_QUERY_OUTCOME_HYPHEN_LIST => VersionConstants::TYPE_CLASS_QUERY_OUTCOME_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_QUESTIONNAIRE => VersionConstants::TYPE_CLASS_QUESTIONNAIRE,
        VersionConstants::TYPE_NAME_QUESTIONNAIRE_DOT_GROUP => VersionConstants::TYPE_CLASS_QUESTIONNAIRE_DOT_GROUP,
        VersionConstants::TYPE_NAME_QUESTIONNAIRE_DOT_QUESTION => VersionConstants::TYPE_CLASS_QUESTIONNAIRE_DOT_QUESTION,
        VersionConstants::TYPE_NAME_QUESTIONNAIRE_STATUS => VersionConstants::TYPE_CLASS_QUESTIONNAIRE_STATUS,
        VersionConstants::TYPE_NAME_QUESTIONNAIRE_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_QUESTIONNAIRE_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_RANGE => VersionConstants::TYPE_CLASS_RANGE,
        VersionConstants::TYPE_NAME_RATIO => VersionConstants::TYPE_CLASS_RATIO,
        VersionConstants::TYPE_NAME_REACTION_SEVERITY => VersionConstants::TYPE_CLASS_REACTION_SEVERITY,
        VersionConstants::TYPE_NAME_REACTION_SEVERITY_HYPHEN_LIST => VersionConstants::TYPE_CLASS_REACTION_SEVERITY_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_RELATED_PERSON => VersionConstants::TYPE_CLASS_RELATED_PERSON,
        VersionConstants::TYPE_NAME_RESOURCE => VersionConstants::TYPE_CLASS_RESOURCE,
        VersionConstants::TYPE_NAME_RESOURCE_DOT_INLINE => VersionConstants::TYPE_CLASS_RESOURCE_DOT_INLINE,
        VersionConstants::TYPE_NAME_RESOURCE_NAMES_PLUS_BINARY => VersionConstants::TYPE_CLASS_RESOURCE_NAMES_PLUS_BINARY,
        VersionConstants::TYPE_NAME_RESOURCE_PROFILE_STATUS => VersionConstants::TYPE_CLASS_RESOURCE_PROFILE_STATUS,
        VersionConstants::TYPE_NAME_RESOURCE_PROFILE_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_RESOURCE_PROFILE_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_RESOURCE_REFERENCE => VersionConstants::TYPE_CLASS_RESOURCE_REFERENCE,
        VersionConstants::TYPE_NAME_RESOURCE_TYPE => VersionConstants::TYPE_CLASS_RESOURCE_TYPE,
        VersionConstants::TYPE_NAME_RESPONSE_TYPE => VersionConstants::TYPE_CLASS_RESPONSE_TYPE,
        VersionConstants::TYPE_NAME_RESPONSE_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_RESPONSE_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_RESTFUL_CONFORMANCE_MODE => VersionConstants::TYPE_CLASS_RESTFUL_CONFORMANCE_MODE,
        VersionConstants::TYPE_NAME_RESTFUL_CONFORMANCE_MODE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_RESTFUL_CONFORMANCE_MODE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_RESTFUL_OPERATION_SYSTEM => VersionConstants::TYPE_CLASS_RESTFUL_OPERATION_SYSTEM,
        VersionConstants::TYPE_NAME_RESTFUL_OPERATION_SYSTEM_HYPHEN_LIST => VersionConstants::TYPE_CLASS_RESTFUL_OPERATION_SYSTEM_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_RESTFUL_OPERATION_TYPE => VersionConstants::TYPE_CLASS_RESTFUL_OPERATION_TYPE,
        VersionConstants::TYPE_NAME_RESTFUL_OPERATION_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_RESTFUL_OPERATION_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SAMPLED_DATA => VersionConstants::TYPE_CLASS_SAMPLED_DATA,
        VersionConstants::TYPE_NAME_SAMPLED_DATA_DATA_TYPE => VersionConstants::TYPE_CLASS_SAMPLED_DATA_DATA_TYPE,
        VersionConstants::TYPE_NAME_SAMPLED_DATA_DATA_TYPE_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_SAMPLED_DATA_DATA_TYPE_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_SCHEDULE => VersionConstants::TYPE_CLASS_SCHEDULE,
        VersionConstants::TYPE_NAME_SCHEDULE_DOT_REPEAT => VersionConstants::TYPE_CLASS_SCHEDULE_DOT_REPEAT,
        VersionConstants::TYPE_NAME_SCORE => VersionConstants::TYPE_CLASS_SCORE,
        VersionConstants::TYPE_NAME_SEARCH_PARAM_TYPE => VersionConstants::TYPE_CLASS_SEARCH_PARAM_TYPE,
        VersionConstants::TYPE_NAME_SEARCH_PARAM_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SEARCH_PARAM_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SECURITY_EVENT => VersionConstants::TYPE_CLASS_SECURITY_EVENT,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_DOT_DETAIL => VersionConstants::TYPE_CLASS_SECURITY_EVENT_DOT_DETAIL,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_DOT_EVENT => VersionConstants::TYPE_CLASS_SECURITY_EVENT_DOT_EVENT,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_DOT_NETWORK => VersionConstants::TYPE_CLASS_SECURITY_EVENT_DOT_NETWORK,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_DOT_OBJECT => VersionConstants::TYPE_CLASS_SECURITY_EVENT_DOT_OBJECT,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_DOT_PARTICIPANT => VersionConstants::TYPE_CLASS_SECURITY_EVENT_DOT_PARTICIPANT,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_DOT_SOURCE => VersionConstants::TYPE_CLASS_SECURITY_EVENT_DOT_SOURCE,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_ACTION => VersionConstants::TYPE_CLASS_SECURITY_EVENT_ACTION,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_ACTION_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SECURITY_EVENT_ACTION_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_LIFECYCLE => VersionConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_LIFECYCLE,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_LIFECYCLE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_LIFECYCLE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_ROLE => VersionConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_ROLE,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_ROLE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_ROLE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_TYPE => VersionConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_TYPE,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_OBJECT_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SECURITY_EVENT_OBJECT_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_OUTCOME => VersionConstants::TYPE_CLASS_SECURITY_EVENT_OUTCOME,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_OUTCOME_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SECURITY_EVENT_OUTCOME_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_PARTICIPANT_NETWORK_TYPE => VersionConstants::TYPE_CLASS_SECURITY_EVENT_PARTICIPANT_NETWORK_TYPE,
        VersionConstants::TYPE_NAME_SECURITY_EVENT_PARTICIPANT_NETWORK_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SECURITY_EVENT_PARTICIPANT_NETWORK_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SENSITIVITY_STATUS => VersionConstants::TYPE_CLASS_SENSITIVITY_STATUS,
        VersionConstants::TYPE_NAME_SENSITIVITY_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SENSITIVITY_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SENSITIVITY_TYPE => VersionConstants::TYPE_CLASS_SENSITIVITY_TYPE,
        VersionConstants::TYPE_NAME_SENSITIVITY_TYPE_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SENSITIVITY_TYPE_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SLICING_RULES => VersionConstants::TYPE_CLASS_SLICING_RULES,
        VersionConstants::TYPE_NAME_SLICING_RULES_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SLICING_RULES_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SPECIMEN => VersionConstants::TYPE_CLASS_SPECIMEN,
        VersionConstants::TYPE_NAME_SPECIMEN_DOT_COLLECTION => VersionConstants::TYPE_CLASS_SPECIMEN_DOT_COLLECTION,
        VersionConstants::TYPE_NAME_SPECIMEN_DOT_CONTAINER => VersionConstants::TYPE_CLASS_SPECIMEN_DOT_CONTAINER,
        VersionConstants::TYPE_NAME_SPECIMEN_DOT_SOURCE => VersionConstants::TYPE_CLASS_SPECIMEN_DOT_SOURCE,
        VersionConstants::TYPE_NAME_SPECIMEN_DOT_TREATMENT => VersionConstants::TYPE_CLASS_SPECIMEN_DOT_TREATMENT,
        VersionConstants::TYPE_NAME_STRING => VersionConstants::TYPE_CLASS_STRING,
        VersionConstants::TYPE_NAME_STRING_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_STRING_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_SUBSTANCE => VersionConstants::TYPE_CLASS_SUBSTANCE,
        VersionConstants::TYPE_NAME_SUBSTANCE_DOT_INGREDIENT => VersionConstants::TYPE_CLASS_SUBSTANCE_DOT_INGREDIENT,
        VersionConstants::TYPE_NAME_SUBSTANCE_DOT_INSTANCE => VersionConstants::TYPE_CLASS_SUBSTANCE_DOT_INSTANCE,
        VersionConstants::TYPE_NAME_SUPPLY => VersionConstants::TYPE_CLASS_SUPPLY,
        VersionConstants::TYPE_NAME_SUPPLY_DOT_DISPENSE => VersionConstants::TYPE_CLASS_SUPPLY_DOT_DISPENSE,
        VersionConstants::TYPE_NAME_SUPPLY_DISPENSE_STATUS => VersionConstants::TYPE_CLASS_SUPPLY_DISPENSE_STATUS,
        VersionConstants::TYPE_NAME_SUPPLY_DISPENSE_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SUPPLY_DISPENSE_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_SUPPLY_STATUS => VersionConstants::TYPE_CLASS_SUPPLY_STATUS,
        VersionConstants::TYPE_NAME_SUPPLY_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_SUPPLY_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_TOTAL_RESULTS => VersionConstants::TYPE_CLASS_TOTAL_RESULTS,
        VersionConstants::TYPE_NAME_UNITS_OF_TIME => VersionConstants::TYPE_CLASS_UNITS_OF_TIME,
        VersionConstants::TYPE_NAME_UNITS_OF_TIME_HYPHEN_LIST => VersionConstants::TYPE_CLASS_UNITS_OF_TIME_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_URI => VersionConstants::TYPE_CLASS_URI,
        VersionConstants::TYPE_NAME_URI_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_URI_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_UUID => VersionConstants::TYPE_CLASS_UUID,
        VersionConstants::TYPE_NAME_UUID_HYPHEN_PRIMITIVE => VersionConstants::TYPE_CLASS_UUID_HYPHEN_PRIMITIVE,
        VersionConstants::TYPE_NAME_VALUE_SET => VersionConstants::TYPE_CLASS_VALUE_SET,
        VersionConstants::TYPE_NAME_VALUE_SET_DOT_COMPOSE => VersionConstants::TYPE_CLASS_VALUE_SET_DOT_COMPOSE,
        VersionConstants::TYPE_NAME_VALUE_SET_DOT_CONCEPT => VersionConstants::TYPE_CLASS_VALUE_SET_DOT_CONCEPT,
        VersionConstants::TYPE_NAME_VALUE_SET_DOT_CONTAINS => VersionConstants::TYPE_CLASS_VALUE_SET_DOT_CONTAINS,
        VersionConstants::TYPE_NAME_VALUE_SET_DOT_DEFINE => VersionConstants::TYPE_CLASS_VALUE_SET_DOT_DEFINE,
        VersionConstants::TYPE_NAME_VALUE_SET_DOT_EXPANSION => VersionConstants::TYPE_CLASS_VALUE_SET_DOT_EXPANSION,
        VersionConstants::TYPE_NAME_VALUE_SET_DOT_FILTER => VersionConstants::TYPE_CLASS_VALUE_SET_DOT_FILTER,
        VersionConstants::TYPE_NAME_VALUE_SET_DOT_INCLUDE => VersionConstants::TYPE_CLASS_VALUE_SET_DOT_INCLUDE,
        VersionConstants::TYPE_NAME_VALUE_SET_STATUS => VersionConstants::TYPE_CLASS_VALUE_SET_STATUS,
        VersionConstants::TYPE_NAME_VALUE_SET_STATUS_HYPHEN_LIST => VersionConstants::TYPE_CLASS_VALUE_SET_STATUS_HYPHEN_LIST,
        VersionConstants::TYPE_NAME_XHTML => VersionConstants::TYPE_CLASS_XHTML,
        VersionConstants::TYPE_NAME_XML_ID_REF => VersionConstants::TYPE_CLASS_XML_ID_REF,
    ];

    private const _CONTAINABLE_TYPES = [
        VersionConstants::TYPE_NAME_ADVERSE_REACTION => VersionConstants::TYPE_CLASS_ADVERSE_REACTION,
        VersionConstants::TYPE_NAME_ALERT => VersionConstants::TYPE_CLASS_ALERT,
        VersionConstants::TYPE_NAME_ALLERGY_INTOLERANCE => VersionConstants::TYPE_CLASS_ALLERGY_INTOLERANCE,
        VersionConstants::TYPE_NAME_BINARY => VersionConstants::TYPE_CLASS_BINARY,
        VersionConstants::TYPE_NAME_CARE_PLAN => VersionConstants::TYPE_CLASS_CARE_PLAN,
        VersionConstants::TYPE_NAME_COMPOSITION => VersionConstants::TYPE_CLASS_COMPOSITION,
        VersionConstants::TYPE_NAME_CONCEPT_MAP => VersionConstants::TYPE_CLASS_CONCEPT_MAP,
        VersionConstants::TYPE_NAME_CONDITION => VersionConstants::TYPE_CLASS_CONDITION,
        VersionConstants::TYPE_NAME_CONFORMANCE => VersionConstants::TYPE_CLASS_CONFORMANCE,
        VersionConstants::TYPE_NAME_DEVICE => VersionConstants::TYPE_CLASS_DEVICE,
        VersionConstants::TYPE_NAME_DEVICE_OBSERVATION_REPORT => VersionConstants::TYPE_CLASS_DEVICE_OBSERVATION_REPORT,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_ORDER => VersionConstants::TYPE_CLASS_DIAGNOSTIC_ORDER,
        VersionConstants::TYPE_NAME_DIAGNOSTIC_REPORT => VersionConstants::TYPE_CLASS_DIAGNOSTIC_REPORT,
        VersionConstants::TYPE_NAME_DOCUMENT_MANIFEST => VersionConstants::TYPE_CLASS_DOCUMENT_MANIFEST,
        VersionConstants::TYPE_NAME_DOCUMENT_REFERENCE => VersionConstants::TYPE_CLASS_DOCUMENT_REFERENCE,
        VersionConstants::TYPE_NAME_ENCOUNTER => VersionConstants::TYPE_CLASS_ENCOUNTER,
        VersionConstants::TYPE_NAME_FAMILY_HISTORY => VersionConstants::TYPE_CLASS_FAMILY_HISTORY,
        VersionConstants::TYPE_NAME_GROUP => VersionConstants::TYPE_CLASS_GROUP,
        VersionConstants::TYPE_NAME_IMAGING_STUDY => VersionConstants::TYPE_CLASS_IMAGING_STUDY,
        VersionConstants::TYPE_NAME_IMMUNIZATION => VersionConstants::TYPE_CLASS_IMMUNIZATION,
        VersionConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION => VersionConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION,
        VersionConstants::TYPE_NAME_LIST => VersionConstants::TYPE_CLASS_LIST,
        VersionConstants::TYPE_NAME_LOCATION => VersionConstants::TYPE_CLASS_LOCATION,
        VersionConstants::TYPE_NAME_MEDIA => VersionConstants::TYPE_CLASS_MEDIA,
        VersionConstants::TYPE_NAME_MEDICATION => VersionConstants::TYPE_CLASS_MEDICATION,
        VersionConstants::TYPE_NAME_MEDICATION_ADMINISTRATION => VersionConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION,
        VersionConstants::TYPE_NAME_MEDICATION_DISPENSE => VersionConstants::TYPE_CLASS_MEDICATION_DISPENSE,
        VersionConstants::TYPE_NAME_MEDICATION_PRESCRIPTION => VersionConstants::TYPE_CLASS_MEDICATION_PRESCRIPTION,
        VersionConstants::TYPE_NAME_MEDICATION_STATEMENT => VersionConstants::TYPE_CLASS_MEDICATION_STATEMENT,
        VersionConstants::TYPE_NAME_MESSAGE_HEADER => VersionConstants::TYPE_CLASS_MESSAGE_HEADER,
        VersionConstants::TYPE_NAME_OBSERVATION => VersionConstants::TYPE_CLASS_OBSERVATION,
        VersionConstants::TYPE_NAME_OPERATION_OUTCOME => VersionConstants::TYPE_CLASS_OPERATION_OUTCOME,
        VersionConstants::TYPE_NAME_ORDER => VersionConstants::TYPE_CLASS_ORDER,
        VersionConstants::TYPE_NAME_ORDER_RESPONSE => VersionConstants::TYPE_CLASS_ORDER_RESPONSE,
        VersionConstants::TYPE_NAME_ORGANIZATION => VersionConstants::TYPE_CLASS_ORGANIZATION,
        VersionConstants::TYPE_NAME_OTHER => VersionConstants::TYPE_CLASS_OTHER,
        VersionConstants::TYPE_NAME_PATIENT => VersionConstants::TYPE_CLASS_PATIENT,
        VersionConstants::TYPE_NAME_PRACTITIONER => VersionConstants::TYPE_CLASS_PRACTITIONER,
        VersionConstants::TYPE_NAME_PROCEDURE => VersionConstants::TYPE_CLASS_PROCEDURE,
        VersionConstants::TYPE_NAME_PROFILE => VersionConstants::TYPE_CLASS_PROFILE,
        VersionConstants::TYPE_NAME_PROVENANCE => VersionConstants::TYPE_CLASS_PROVENANCE,
        VersionConstants::TYPE_NAME_QUERY => VersionConstants::TYPE_CLASS_QUERY,
        VersionConstants::TYPE_NAME_QUESTIONNAIRE => VersionConstants::TYPE_CLASS_QUESTIONNAIRE,
        VersionConstants::TYPE_NAME_RELATED_PERSON => VersionConstants::TYPE_CLASS_RELATED_PERSON,
        VersionConstants::TYPE_NAME_SECURITY_EVENT => VersionConstants::TYPE_CLASS_SECURITY_EVENT,
        VersionConstants::TYPE_NAME_SPECIMEN => VersionConstants::TYPE_CLASS_SPECIMEN,
        VersionConstants::TYPE_NAME_SUBSTANCE => VersionConstants::TYPE_CLASS_SUBSTANCE,
        VersionConstants::TYPE_NAME_SUPPLY => VersionConstants::TYPE_CLASS_SUPPLY,
        VersionConstants::TYPE_NAME_VALUE_SET => VersionConstants::TYPE_CLASS_VALUE_SET,
    ];

    /**
     * Get fully qualified class name for FHIR Type name.  Returns null if type not found
     * @param string $typeName
     * @return string|null
     */
    public static function getTypeClassName(string $typeName): null|string
    {
        return self::_TYPE_MAP[$typeName] ?? null;
    }

    /**
     * Returns the full internal class map
     * @return array
     */
    public static function getMap(): array
    {
        return self::_TYPE_MAP;
    }

    /**
     * Returns the full list of containable resource types
     * @return array
     */
    public static function getContainableTypes(): array
    {
        return self::_CONTAINABLE_TYPES;
    }

    /**
     * @param string $typeName Name of FHIR object reference by Resource.Inline
     * @return string|null Name of class as string or null if type is not contained in map
     */
    public static function getContainedTypeClassName(string $typeName): null|string
    {
        return self::_CONTAINABLE_TYPES[$typeName] ?? null;
    }

    /**
     * Will attempt to determine if the provided value is or describes a containable resource type
     * @param string|array|\SimpleXMLElement|\DCarbone\PHPFHIRGenerated\Types\TypeInterface $type
     * @return bool
     * @throws \InvalidArgumentException
     */
    public static function isContainableResource(string|array|\SimpleXMLElement|TypeInterface $type): bool
    {
        $tt = gettype($type);
        if ('object' === $tt) {
            if ($type instanceof TypeInterface) {
                return ($type instanceof VersionContainedTypeInterface);
            }
            return isset(self::_CONTAINABLE_TYPES[$type->getName()]);
        }
        if ('string' === $tt) {
            return isset(self::_CONTAINABLE_TYPES[$type]) || in_array('\\' . ltrim($type, '\\'), self::_CONTAINABLE_TYPES, true);
        }
        if (isset($type[Constants::JSON_FIELD_RESOURCE_TYPE])) {
            return isset(self::_CONTAINABLE_TYPES[$type[Constants::JSON_FIELD_RESOURCE_TYPE]]);
        }
        return false;
    }

    /**
     * @param \SimpleXMLElement $node Parent element containing inline resource
     * @return string Fully qualified class name of contained resource type
     */
    public static function getContainedTypeClassNameFromXML(\SimpleXMLElement $node): string
    {
        $typeName = $node->getName();
        $className = self::getContainedTypeClassName($typeName);
        if (null === $className) {
            throw self::createdInvalidContainedTypeException($typeName);
        }
        return $className;
    }

    /**
     * @param array $data
     * @return string Fully qualified class name of contained resource type
     */
    public static function getContainedTypeClassNameFromArray(array $data): string
    {
        $resourceType = null;
        if (isset($data[Constants::JSON_FIELD_RESOURCE_TYPE])) {
            $resourceType = $data[Constants::JSON_FIELD_RESOURCE_TYPE];
        }
        if (null === $resourceType) {
            throw new \DomainException(sprintf(
                'Unable to determine contained Resource type from input (missing "%s" key).  Keys: ["%s"]',
                Constants::JSON_FIELD_RESOURCE_TYPE,
                implode('","', array_keys($data))
            ));
        }
        $className = self::getContainedTypeClassName($resourceType);
        if (null === $className) {
            throw self::createdInvalidContainedTypeException($resourceType);
        }
        return $className;
    }

    /**
     * @param string $typeName
     * @return \UnexpectedValueException
     */
    private static function createdInvalidContainedTypeException(string $typeName): \UnexpectedValueException
    {
        return new \UnexpectedValueException(sprintf(
            'Type "%s" is not among the list of types allowed within a Resource.Inline',
            $typeName
        ));
    }
}
