<?php namespace PHPFHIRGenerated;

/*!
 * This class was generated with the PHPFHIR library (https://github.com/dcarbone/php-fhir) using
 * class definitions from HL7 FHIR (https://www.hl7.org/fhir/)
 * 
 * Class creation date: April 28th, 2016
 * 
 * PHPFHIR Copyright:
 * 
 * Copyright 2016 Daniel Carbone (daniel.p.carbone@gmail.com)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 */

class PHPFHIRAutoloader
{
    const ROOT_DIR = __DIR__;

    /** @var array */
    private static $_classMap = array (
  'PHPFHIRGenerated\\PHPFHIRParserMap' => 'PHPFHIRParserMap.php',
  'PHPFHIRGenerated\\JsonSerializable' => 'JsonSerializable.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRMarkdown' => 'FHIRElement/FHIRMarkdown.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRInteger' => 'FHIRElement/FHIRInteger.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDateTime' => 'FHIRElement/FHIRDateTime.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRUnsignedInt' => 'FHIRElement/FHIRUnsignedInt.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRCode' => 'FHIRElement/FHIRCode.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDate' => 'FHIRElement/FHIRDate.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDecimal' => 'FHIRElement/FHIRDecimal.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRUri' => 'FHIRElement/FHIRUri.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRId' => 'FHIRElement/FHIRId.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRBase64Binary' => 'FHIRElement/FHIRBase64Binary.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRTime' => 'FHIRElement/FHIRTime.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIROid' => 'FHIRElement/FHIROid.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRPositiveInt' => 'FHIRElement/FHIRPositiveInt.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRString' => 'FHIRElement/FHIRString.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRBoolean' => 'FHIRElement/FHIRBoolean.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRUuid' => 'FHIRElement/FHIRUuid.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRInstant' => 'FHIRElement/FHIRInstant.php',
  'PHPFHIRGenerated\\FHIRResourceContainer' => 'FHIRResourceContainer.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRExtension' => 'FHIRElement/FHIRExtension.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRBackboneElement' => 'FHIRElement/FHIRBackboneElement.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRNarrative' => 'FHIRElement/FHIRNarrative.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRNarrativeStatus' => 'FHIRElement/FHIRNarrativeStatus.php',
  'PHPFHIRGenerated\\FHIRElement' => 'FHIRElement.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRPeriod' => 'FHIRElement/FHIRPeriod.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRCoding' => 'FHIRElement/FHIRCoding.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRRange' => 'FHIRElement/FHIRRange.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRQuantity' => 'FHIRElement/FHIRQuantity.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRQuantityComparator' => 'FHIRElement/FHIRQuantityComparator.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAttachment' => 'FHIRElement/FHIRAttachment.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRRatio' => 'FHIRElement/FHIRRatio.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAnnotation' => 'FHIRElement/FHIRAnnotation.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSampledData' => 'FHIRElement/FHIRSampledData.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSampledDataDataType' => 'FHIRElement/FHIRSampledDataDataType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRReference' => 'FHIRElement/FHIRReference.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRCodeableConcept' => 'FHIRElement/FHIRCodeableConcept.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRIdentifier' => 'FHIRElement/FHIRIdentifier.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRIdentifierUse' => 'FHIRElement/FHIRIdentifierUse.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSignature' => 'FHIRElement/FHIRSignature.php',
  'PHPFHIRGenerated\\FHIRAge' => 'FHIRAge.php',
  'PHPFHIRGenerated\\FHIRCount' => 'FHIRCount.php',
  'PHPFHIRGenerated\\FHIRMoney' => 'FHIRMoney.php',
  'PHPFHIRGenerated\\FHIRDistance' => 'FHIRDistance.php',
  'PHPFHIRGenerated\\FHIRDuration' => 'FHIRDuration.php',
  'PHPFHIRGenerated\\FHIRSimpleQuantity' => 'FHIRSimpleQuantity.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRElementDefinition' => 'FHIRElement/FHIRElementDefinition.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionMapping' => 'FHIRResource/FHIRElementDefinition/FHIRElementDefinitionMapping.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionSlicing' => 'FHIRResource/FHIRElementDefinition/FHIRElementDefinitionSlicing.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionBinding' => 'FHIRResource/FHIRElementDefinition/FHIRElementDefinitionBinding.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionType' => 'FHIRResource/FHIRElementDefinition/FHIRElementDefinitionType.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionBase' => 'FHIRResource/FHIRElementDefinition/FHIRElementDefinitionBase.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionConstraint' => 'FHIRResource/FHIRElementDefinition/FHIRElementDefinitionConstraint.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRPropertyRepresentation' => 'FHIRElement/FHIRPropertyRepresentation.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSlicingRules' => 'FHIRElement/FHIRSlicingRules.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRBindingStrength' => 'FHIRElement/FHIRBindingStrength.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAggregationMode' => 'FHIRElement/FHIRAggregationMode.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRConstraintSeverity' => 'FHIRElement/FHIRConstraintSeverity.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRTiming' => 'FHIRElement/FHIRTiming.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTiming\\FHIRTimingRepeat' => 'FHIRResource/FHIRTiming/FHIRTimingRepeat.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRUnitsOfTime' => 'FHIRElement/FHIRUnitsOfTime.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIREventTiming' => 'FHIRElement/FHIREventTiming.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAddress' => 'FHIRElement/FHIRAddress.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAddressUse' => 'FHIRElement/FHIRAddressUse.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAddressType' => 'FHIRElement/FHIRAddressType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRHumanName' => 'FHIRElement/FHIRHumanName.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRNameUse' => 'FHIRElement/FHIRNameUse.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRMeta' => 'FHIRElement/FHIRMeta.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRContactPoint' => 'FHIRElement/FHIRContactPoint.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRContactPointSystem' => 'FHIRElement/FHIRContactPointSystem.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRContactPointUse' => 'FHIRElement/FHIRContactPointUse.php',
  'PHPFHIRGenerated\\FHIRResource' => 'FHIRResource.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDomainResource' => 'FHIRResource/FHIRDomainResource.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRNoteType' => 'FHIRElement/FHIRNoteType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDocumentReferenceStatus' => 'FHIRElement/FHIRDocumentReferenceStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRConceptMapEquivalence' => 'FHIRElement/FHIRConceptMapEquivalence.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRRemittanceOutcome' => 'FHIRElement/FHIRRemittanceOutcome.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRConformanceResourceStatus' => 'FHIRElement/FHIRConformanceResourceStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAdministrativeGender' => 'FHIRElement/FHIRAdministrativeGender.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSearchParamType' => 'FHIRElement/FHIRSearchParamType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRAccount' => 'FHIRDomainResource/FHIRAccount.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAccountStatus' => 'FHIRElement/FHIRAccountStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRAllergyIntolerance' => 'FHIRDomainResource/FHIRAllergyIntolerance.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRAllergyIntolerance\\FHIRAllergyIntoleranceReaction' => 'FHIRResource/FHIRAllergyIntolerance/FHIRAllergyIntoleranceReaction.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAllergyIntoleranceCertainty' => 'FHIRElement/FHIRAllergyIntoleranceCertainty.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAllergyIntoleranceType' => 'FHIRElement/FHIRAllergyIntoleranceType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAllergyIntoleranceSeverity' => 'FHIRElement/FHIRAllergyIntoleranceSeverity.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAllergyIntoleranceCriticality' => 'FHIRElement/FHIRAllergyIntoleranceCriticality.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAllergyIntoleranceCategory' => 'FHIRElement/FHIRAllergyIntoleranceCategory.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAllergyIntoleranceStatus' => 'FHIRElement/FHIRAllergyIntoleranceStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRAppointment' => 'FHIRDomainResource/FHIRAppointment.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRAppointment\\FHIRAppointmentParticipant' => 'FHIRResource/FHIRAppointment/FHIRAppointmentParticipant.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRParticipantRequired' => 'FHIRElement/FHIRParticipantRequired.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAppointmentStatus' => 'FHIRElement/FHIRAppointmentStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRParticipationStatus' => 'FHIRElement/FHIRParticipationStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRAppointmentResponse' => 'FHIRDomainResource/FHIRAppointmentResponse.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRParticipantStatus' => 'FHIRElement/FHIRParticipantStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRAuditEvent' => 'FHIRDomainResource/FHIRAuditEvent.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventEvent' => 'FHIRResource/FHIRAuditEvent/FHIRAuditEventEvent.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventParticipant' => 'FHIRResource/FHIRAuditEvent/FHIRAuditEventParticipant.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventNetwork' => 'FHIRResource/FHIRAuditEvent/FHIRAuditEventNetwork.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventSource' => 'FHIRResource/FHIRAuditEvent/FHIRAuditEventSource.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventObject' => 'FHIRResource/FHIRAuditEvent/FHIRAuditEventObject.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventDetail' => 'FHIRResource/FHIRAuditEvent/FHIRAuditEventDetail.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAuditEventAction' => 'FHIRElement/FHIRAuditEventAction.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAuditEventOutcome' => 'FHIRElement/FHIRAuditEventOutcome.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAuditEventParticipantNetworkType' => 'FHIRElement/FHIRAuditEventParticipantNetworkType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRBasic' => 'FHIRDomainResource/FHIRBasic.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRBinary' => 'FHIRResource/FHIRBinary.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRBodySite' => 'FHIRDomainResource/FHIRBodySite.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRBundle' => 'FHIRResource/FHIRBundle.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRBundle\\FHIRBundleLink' => 'FHIRResource/FHIRBundle/FHIRBundleLink.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRBundle\\FHIRBundleEntry' => 'FHIRResource/FHIRBundle/FHIRBundleEntry.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRBundle\\FHIRBundleSearch' => 'FHIRResource/FHIRBundle/FHIRBundleSearch.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRBundle\\FHIRBundleRequest' => 'FHIRResource/FHIRBundle/FHIRBundleRequest.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRBundle\\FHIRBundleResponse' => 'FHIRResource/FHIRBundle/FHIRBundleResponse.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRHTTPVerb' => 'FHIRElement/FHIRHTTPVerb.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSearchEntryMode' => 'FHIRElement/FHIRSearchEntryMode.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRBundleType' => 'FHIRElement/FHIRBundleType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRCarePlan' => 'FHIRDomainResource/FHIRCarePlan.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRCarePlan\\FHIRCarePlanRelatedPlan' => 'FHIRResource/FHIRCarePlan/FHIRCarePlanRelatedPlan.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRCarePlan\\FHIRCarePlanParticipant' => 'FHIRResource/FHIRCarePlan/FHIRCarePlanParticipant.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRCarePlan\\FHIRCarePlanActivity' => 'FHIRResource/FHIRCarePlan/FHIRCarePlanActivity.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRCarePlan\\FHIRCarePlanDetail' => 'FHIRResource/FHIRCarePlan/FHIRCarePlanDetail.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRCarePlanStatus' => 'FHIRElement/FHIRCarePlanStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRCarePlanRelationship' => 'FHIRElement/FHIRCarePlanRelationship.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRCarePlanActivityStatus' => 'FHIRElement/FHIRCarePlanActivityStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRClaim' => 'FHIRDomainResource/FHIRClaim.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaim\\FHIRClaimPayee' => 'FHIRResource/FHIRClaim/FHIRClaimPayee.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaim\\FHIRClaimDiagnosis' => 'FHIRResource/FHIRClaim/FHIRClaimDiagnosis.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaim\\FHIRClaimCoverage' => 'FHIRResource/FHIRClaim/FHIRClaimCoverage.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaim\\FHIRClaimItem' => 'FHIRResource/FHIRClaim/FHIRClaimItem.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaim\\FHIRClaimDetail' => 'FHIRResource/FHIRClaim/FHIRClaimDetail.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaim\\FHIRClaimSubDetail' => 'FHIRResource/FHIRClaim/FHIRClaimSubDetail.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaim\\FHIRClaimProsthesis' => 'FHIRResource/FHIRClaim/FHIRClaimProsthesis.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaim\\FHIRClaimMissingTeeth' => 'FHIRResource/FHIRClaim/FHIRClaimMissingTeeth.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRClaimType' => 'FHIRElement/FHIRClaimType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRUse' => 'FHIRElement/FHIRUse.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRClaimResponse' => 'FHIRDomainResource/FHIRClaimResponse.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseItem' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseItem.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAdjudication' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseAdjudication.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseDetail' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseDetail.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAdjudication1' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseAdjudication1.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseSubDetail' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseSubDetail.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAdjudication2' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseAdjudication2.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAddItem' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseAddItem.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAdjudication3' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseAdjudication3.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseDetail1' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseDetail1.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAdjudication4' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseAdjudication4.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseError' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseError.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseNote' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseNote.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseCoverage' => 'FHIRResource/FHIRClaimResponse/FHIRClaimResponseCoverage.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRClinicalImpression' => 'FHIRDomainResource/FHIRClinicalImpression.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClinicalImpression\\FHIRClinicalImpressionInvestigations' => 'FHIRResource/FHIRClinicalImpression/FHIRClinicalImpressionInvestigations.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClinicalImpression\\FHIRClinicalImpressionFinding' => 'FHIRResource/FHIRClinicalImpression/FHIRClinicalImpressionFinding.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRClinicalImpression\\FHIRClinicalImpressionRuledOut' => 'FHIRResource/FHIRClinicalImpression/FHIRClinicalImpressionRuledOut.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRClinicalImpressionStatus' => 'FHIRElement/FHIRClinicalImpressionStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRCommunication' => 'FHIRDomainResource/FHIRCommunication.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRCommunication\\FHIRCommunicationPayload' => 'FHIRResource/FHIRCommunication/FHIRCommunicationPayload.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRCommunicationStatus' => 'FHIRElement/FHIRCommunicationStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRCommunicationRequest' => 'FHIRDomainResource/FHIRCommunicationRequest.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRCommunicationRequest\\FHIRCommunicationRequestPayload' => 'FHIRResource/FHIRCommunicationRequest/FHIRCommunicationRequestPayload.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRCommunicationRequestStatus' => 'FHIRElement/FHIRCommunicationRequestStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRComposition' => 'FHIRDomainResource/FHIRComposition.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRComposition\\FHIRCompositionAttester' => 'FHIRResource/FHIRComposition/FHIRCompositionAttester.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRComposition\\FHIRCompositionEvent' => 'FHIRResource/FHIRComposition/FHIRCompositionEvent.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRComposition\\FHIRCompositionSection' => 'FHIRResource/FHIRComposition/FHIRCompositionSection.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRCompositionStatus' => 'FHIRElement/FHIRCompositionStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRCompositionAttestationMode' => 'FHIRElement/FHIRCompositionAttestationMode.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRConceptMap' => 'FHIRDomainResource/FHIRConceptMap.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConceptMap\\FHIRConceptMapContact' => 'FHIRResource/FHIRConceptMap/FHIRConceptMapContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConceptMap\\FHIRConceptMapElement' => 'FHIRResource/FHIRConceptMap/FHIRConceptMapElement.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConceptMap\\FHIRConceptMapTarget' => 'FHIRResource/FHIRConceptMap/FHIRConceptMapTarget.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConceptMap\\FHIRConceptMapDependsOn' => 'FHIRResource/FHIRConceptMap/FHIRConceptMapDependsOn.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRCondition' => 'FHIRDomainResource/FHIRCondition.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRCondition\\FHIRConditionStage' => 'FHIRResource/FHIRCondition/FHIRConditionStage.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRCondition\\FHIRConditionEvidence' => 'FHIRResource/FHIRCondition/FHIRConditionEvidence.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRConditionVerificationStatus' => 'FHIRElement/FHIRConditionVerificationStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRConditionDefinition' => 'FHIRDomainResource/FHIRConditionDefinition.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConditionDefinition\\FHIRConditionDefinitionContact' => 'FHIRResource/FHIRConditionDefinition/FHIRConditionDefinitionContact.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRConformance' => 'FHIRDomainResource/FHIRConformance.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceContact' => 'FHIRResource/FHIRConformance/FHIRConformanceContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceSoftware' => 'FHIRResource/FHIRConformance/FHIRConformanceSoftware.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceImplementation' => 'FHIRResource/FHIRConformance/FHIRConformanceImplementation.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceRest' => 'FHIRResource/FHIRConformance/FHIRConformanceRest.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceSecurity' => 'FHIRResource/FHIRConformance/FHIRConformanceSecurity.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceCertificate' => 'FHIRResource/FHIRConformance/FHIRConformanceCertificate.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceResource' => 'FHIRResource/FHIRConformance/FHIRConformanceResource.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceInteraction' => 'FHIRResource/FHIRConformance/FHIRConformanceInteraction.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceSearchParam' => 'FHIRResource/FHIRConformance/FHIRConformanceSearchParam.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceInteraction1' => 'FHIRResource/FHIRConformance/FHIRConformanceInteraction1.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceOperation' => 'FHIRResource/FHIRConformance/FHIRConformanceOperation.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceMessaging' => 'FHIRResource/FHIRConformance/FHIRConformanceMessaging.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceEndpoint' => 'FHIRResource/FHIRConformance/FHIRConformanceEndpoint.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceEvent' => 'FHIRResource/FHIRConformance/FHIRConformanceEvent.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRConformance\\FHIRConformanceDocument' => 'FHIRResource/FHIRConformance/FHIRConformanceDocument.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDocumentMode' => 'FHIRElement/FHIRDocumentMode.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSystemRestfulInteraction' => 'FHIRElement/FHIRSystemRestfulInteraction.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRResourceVersionPolicy' => 'FHIRElement/FHIRResourceVersionPolicy.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRRestfulConformanceMode' => 'FHIRElement/FHIRRestfulConformanceMode.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRTypeRestfulInteraction' => 'FHIRElement/FHIRTypeRestfulInteraction.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRConditionalDeleteStatus' => 'FHIRElement/FHIRConditionalDeleteStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRConformanceStatementKind' => 'FHIRElement/FHIRConformanceStatementKind.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSearchModifierCode' => 'FHIRElement/FHIRSearchModifierCode.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRConformanceEventMode' => 'FHIRElement/FHIRConformanceEventMode.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRMessageSignificanceCategory' => 'FHIRElement/FHIRMessageSignificanceCategory.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRUnknownContentCode' => 'FHIRElement/FHIRUnknownContentCode.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRTransactionMode' => 'FHIRElement/FHIRTransactionMode.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRContract' => 'FHIRDomainResource/FHIRContract.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRContract\\FHIRContractActor' => 'FHIRResource/FHIRContract/FHIRContractActor.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRContract\\FHIRContractValuedItem' => 'FHIRResource/FHIRContract/FHIRContractValuedItem.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRContract\\FHIRContractSigner' => 'FHIRResource/FHIRContract/FHIRContractSigner.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRContract\\FHIRContractTerm' => 'FHIRResource/FHIRContract/FHIRContractTerm.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRContract\\FHIRContractActor1' => 'FHIRResource/FHIRContract/FHIRContractActor1.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRContract\\FHIRContractValuedItem1' => 'FHIRResource/FHIRContract/FHIRContractValuedItem1.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRContract\\FHIRContractFriendly' => 'FHIRResource/FHIRContract/FHIRContractFriendly.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRContract\\FHIRContractLegal' => 'FHIRResource/FHIRContract/FHIRContractLegal.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRContract\\FHIRContractRule' => 'FHIRResource/FHIRContract/FHIRContractRule.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRContraindication' => 'FHIRDomainResource/FHIRContraindication.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRContraindication\\FHIRContraindicationMitigation' => 'FHIRResource/FHIRContraindication/FHIRContraindicationMitigation.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRContraindicationSeverity' => 'FHIRElement/FHIRContraindicationSeverity.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRCoverage' => 'FHIRDomainResource/FHIRCoverage.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDataElement' => 'FHIRDomainResource/FHIRDataElement.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDataElement\\FHIRDataElementContact' => 'FHIRResource/FHIRDataElement/FHIRDataElementContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDataElement\\FHIRDataElementMapping' => 'FHIRResource/FHIRDataElement/FHIRDataElementMapping.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDataElementStringency' => 'FHIRElement/FHIRDataElementStringency.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDetectedIssue' => 'FHIRDomainResource/FHIRDetectedIssue.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDetectedIssue\\FHIRDetectedIssueMitigation' => 'FHIRResource/FHIRDetectedIssue/FHIRDetectedIssueMitigation.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDetectedIssueSeverity' => 'FHIRElement/FHIRDetectedIssueSeverity.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDevice' => 'FHIRDomainResource/FHIRDevice.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDeviceStatus' => 'FHIRElement/FHIRDeviceStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDeviceComponent' => 'FHIRDomainResource/FHIRDeviceComponent.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDeviceComponent\\FHIRDeviceComponentProductionSpecification' => 'FHIRResource/FHIRDeviceComponent/FHIRDeviceComponentProductionSpecification.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRMeasmnt_Principle' => 'FHIRElement/FHIRMeasmnt_Principle.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDeviceMetric' => 'FHIRDomainResource/FHIRDeviceMetric.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDeviceMetric\\FHIRDeviceMetricCalibration' => 'FHIRResource/FHIRDeviceMetric/FHIRDeviceMetricCalibration.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDeviceMetricColor' => 'FHIRElement/FHIRDeviceMetricColor.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDeviceMetricCalibrationState' => 'FHIRElement/FHIRDeviceMetricCalibrationState.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDeviceMetricCalibrationType' => 'FHIRElement/FHIRDeviceMetricCalibrationType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDeviceMetricCategory' => 'FHIRElement/FHIRDeviceMetricCategory.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDeviceMetricOperationalStatus' => 'FHIRElement/FHIRDeviceMetricOperationalStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDeviceUseRequest' => 'FHIRDomainResource/FHIRDeviceUseRequest.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDeviceUseRequestStatus' => 'FHIRElement/FHIRDeviceUseRequestStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDeviceUseRequestPriority' => 'FHIRElement/FHIRDeviceUseRequestPriority.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDeviceUseStatement' => 'FHIRDomainResource/FHIRDeviceUseStatement.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDiagnosticOrder' => 'FHIRDomainResource/FHIRDiagnosticOrder.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDiagnosticOrder\\FHIRDiagnosticOrderEvent' => 'FHIRResource/FHIRDiagnosticOrder/FHIRDiagnosticOrderEvent.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDiagnosticOrder\\FHIRDiagnosticOrderItem' => 'FHIRResource/FHIRDiagnosticOrder/FHIRDiagnosticOrderItem.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDiagnosticOrderStatus' => 'FHIRElement/FHIRDiagnosticOrderStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDiagnosticOrderPriority' => 'FHIRElement/FHIRDiagnosticOrderPriority.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDiagnosticReport' => 'FHIRDomainResource/FHIRDiagnosticReport.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDiagnosticReport\\FHIRDiagnosticReportImage' => 'FHIRResource/FHIRDiagnosticReport/FHIRDiagnosticReportImage.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDiagnosticReportStatus' => 'FHIRElement/FHIRDiagnosticReportStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDocumentManifest' => 'FHIRDomainResource/FHIRDocumentManifest.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDocumentManifest\\FHIRDocumentManifestContent' => 'FHIRResource/FHIRDocumentManifest/FHIRDocumentManifestContent.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDocumentManifest\\FHIRDocumentManifestRelated' => 'FHIRResource/FHIRDocumentManifest/FHIRDocumentManifestRelated.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRDocumentReference' => 'FHIRDomainResource/FHIRDocumentReference.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDocumentReference\\FHIRDocumentReferenceRelatesTo' => 'FHIRResource/FHIRDocumentReference/FHIRDocumentReferenceRelatesTo.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDocumentReference\\FHIRDocumentReferenceContent' => 'FHIRResource/FHIRDocumentReference/FHIRDocumentReferenceContent.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDocumentReference\\FHIRDocumentReferenceContext' => 'FHIRResource/FHIRDocumentReference/FHIRDocumentReferenceContext.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRDocumentReference\\FHIRDocumentReferenceRelated' => 'FHIRResource/FHIRDocumentReference/FHIRDocumentReferenceRelated.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDocumentRelationshipType' => 'FHIRElement/FHIRDocumentRelationshipType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIREligibilityRequest' => 'FHIRDomainResource/FHIREligibilityRequest.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIREligibilityResponse' => 'FHIRDomainResource/FHIREligibilityResponse.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIREncounter' => 'FHIRDomainResource/FHIREncounter.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIREncounter\\FHIREncounterStatusHistory' => 'FHIRResource/FHIREncounter/FHIREncounterStatusHistory.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIREncounter\\FHIREncounterParticipant' => 'FHIRResource/FHIREncounter/FHIREncounterParticipant.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIREncounter\\FHIREncounterHospitalization' => 'FHIRResource/FHIREncounter/FHIREncounterHospitalization.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIREncounter\\FHIREncounterLocation' => 'FHIRResource/FHIREncounter/FHIREncounterLocation.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIREncounterLocationStatus' => 'FHIRElement/FHIREncounterLocationStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIREncounterClass' => 'FHIRElement/FHIREncounterClass.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIREncounterState' => 'FHIRElement/FHIREncounterState.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIREnrollmentRequest' => 'FHIRDomainResource/FHIREnrollmentRequest.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIREnrollmentResponse' => 'FHIRDomainResource/FHIREnrollmentResponse.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIREpisodeOfCare' => 'FHIRDomainResource/FHIREpisodeOfCare.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIREpisodeOfCare\\FHIREpisodeOfCareStatusHistory' => 'FHIRResource/FHIREpisodeOfCare/FHIREpisodeOfCareStatusHistory.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIREpisodeOfCare\\FHIREpisodeOfCareCareTeam' => 'FHIRResource/FHIREpisodeOfCare/FHIREpisodeOfCareCareTeam.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIREpisodeOfCareStatus' => 'FHIRElement/FHIREpisodeOfCareStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRExplanationOfBenefit' => 'FHIRDomainResource/FHIRExplanationOfBenefit.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRFamilyMemberHistory' => 'FHIRDomainResource/FHIRFamilyMemberHistory.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRFamilyMemberHistory\\FHIRFamilyMemberHistoryCondition' => 'FHIRResource/FHIRFamilyMemberHistory/FHIRFamilyMemberHistoryCondition.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRFamilyHistoryStatus' => 'FHIRElement/FHIRFamilyHistoryStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRFlag' => 'FHIRDomainResource/FHIRFlag.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRFlagStatus' => 'FHIRElement/FHIRFlagStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRGoal' => 'FHIRDomainResource/FHIRGoal.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRGoal\\FHIRGoalOutcome' => 'FHIRResource/FHIRGoal/FHIRGoalOutcome.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRGoalStatus' => 'FHIRElement/FHIRGoalStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRGroup' => 'FHIRDomainResource/FHIRGroup.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRGroup\\FHIRGroupCharacteristic' => 'FHIRResource/FHIRGroup/FHIRGroupCharacteristic.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRGroup\\FHIRGroupMember' => 'FHIRResource/FHIRGroup/FHIRGroupMember.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRGroupType' => 'FHIRElement/FHIRGroupType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRHealthcareService' => 'FHIRDomainResource/FHIRHealthcareService.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRHealthcareService\\FHIRHealthcareServiceServiceType' => 'FHIRResource/FHIRHealthcareService/FHIRHealthcareServiceServiceType.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRHealthcareService\\FHIRHealthcareServiceAvailableTime' => 'FHIRResource/FHIRHealthcareService/FHIRHealthcareServiceAvailableTime.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRHealthcareService\\FHIRHealthcareServiceNotAvailable' => 'FHIRResource/FHIRHealthcareService/FHIRHealthcareServiceNotAvailable.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDaysOfWeek' => 'FHIRElement/FHIRDaysOfWeek.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRImagingObjectSelection' => 'FHIRDomainResource/FHIRImagingObjectSelection.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImagingObjectSelection\\FHIRImagingObjectSelectionStudy' => 'FHIRResource/FHIRImagingObjectSelection/FHIRImagingObjectSelectionStudy.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImagingObjectSelection\\FHIRImagingObjectSelectionSeries' => 'FHIRResource/FHIRImagingObjectSelection/FHIRImagingObjectSelectionSeries.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImagingObjectSelection\\FHIRImagingObjectSelectionInstance' => 'FHIRResource/FHIRImagingObjectSelection/FHIRImagingObjectSelectionInstance.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImagingObjectSelection\\FHIRImagingObjectSelectionFrames' => 'FHIRResource/FHIRImagingObjectSelection/FHIRImagingObjectSelectionFrames.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRImagingStudy' => 'FHIRDomainResource/FHIRImagingStudy.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImagingStudy\\FHIRImagingStudySeries' => 'FHIRResource/FHIRImagingStudy/FHIRImagingStudySeries.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImagingStudy\\FHIRImagingStudyInstance' => 'FHIRResource/FHIRImagingStudy/FHIRImagingStudyInstance.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRInstanceAvailability' => 'FHIRElement/FHIRInstanceAvailability.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRImmunization' => 'FHIRDomainResource/FHIRImmunization.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImmunization\\FHIRImmunizationExplanation' => 'FHIRResource/FHIRImmunization/FHIRImmunizationExplanation.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImmunization\\FHIRImmunizationReaction' => 'FHIRResource/FHIRImmunization/FHIRImmunizationReaction.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImmunization\\FHIRImmunizationVaccinationProtocol' => 'FHIRResource/FHIRImmunization/FHIRImmunizationVaccinationProtocol.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRImmunizationRecommendation' => 'FHIRDomainResource/FHIRImmunizationRecommendation.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImmunizationRecommendation\\FHIRImmunizationRecommendationRecommendation' => 'FHIRResource/FHIRImmunizationRecommendation/FHIRImmunizationRecommendationRecommendation.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImmunizationRecommendation\\FHIRImmunizationRecommendationDateCriterion' => 'FHIRResource/FHIRImmunizationRecommendation/FHIRImmunizationRecommendationDateCriterion.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImmunizationRecommendation\\FHIRImmunizationRecommendationProtocol' => 'FHIRResource/FHIRImmunizationRecommendation/FHIRImmunizationRecommendationProtocol.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRImplementationGuide' => 'FHIRDomainResource/FHIRImplementationGuide.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuideContact' => 'FHIRResource/FHIRImplementationGuide/FHIRImplementationGuideContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuideDependency' => 'FHIRResource/FHIRImplementationGuide/FHIRImplementationGuideDependency.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuidePackage' => 'FHIRResource/FHIRImplementationGuide/FHIRImplementationGuidePackage.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuideResource' => 'FHIRResource/FHIRImplementationGuide/FHIRImplementationGuideResource.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuideGlobal' => 'FHIRResource/FHIRImplementationGuide/FHIRImplementationGuideGlobal.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuidePage' => 'FHIRResource/FHIRImplementationGuide/FHIRImplementationGuidePage.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRGuideDependencyType' => 'FHIRElement/FHIRGuideDependencyType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRGuideResourcePurpose' => 'FHIRElement/FHIRGuideResourcePurpose.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRGuidePageKind' => 'FHIRElement/FHIRGuidePageKind.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRList' => 'FHIRDomainResource/FHIRList.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRList\\FHIRListEntry' => 'FHIRResource/FHIRList/FHIRListEntry.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRListStatus' => 'FHIRElement/FHIRListStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRListMode' => 'FHIRElement/FHIRListMode.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRLocation' => 'FHIRDomainResource/FHIRLocation.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRLocation\\FHIRLocationPosition' => 'FHIRResource/FHIRLocation/FHIRLocationPosition.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRLocationStatus' => 'FHIRElement/FHIRLocationStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRLocationMode' => 'FHIRElement/FHIRLocationMode.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRMedia' => 'FHIRDomainResource/FHIRMedia.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRDigitalMediaType' => 'FHIRElement/FHIRDigitalMediaType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRMedication' => 'FHIRDomainResource/FHIRMedication.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedication\\FHIRMedicationProduct' => 'FHIRResource/FHIRMedication/FHIRMedicationProduct.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedication\\FHIRMedicationIngredient' => 'FHIRResource/FHIRMedication/FHIRMedicationIngredient.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedication\\FHIRMedicationBatch' => 'FHIRResource/FHIRMedication/FHIRMedicationBatch.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedication\\FHIRMedicationPackage' => 'FHIRResource/FHIRMedication/FHIRMedicationPackage.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedication\\FHIRMedicationContent' => 'FHIRResource/FHIRMedication/FHIRMedicationContent.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRMedicationAdministration' => 'FHIRDomainResource/FHIRMedicationAdministration.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedicationAdministration\\FHIRMedicationAdministrationDosage' => 'FHIRResource/FHIRMedicationAdministration/FHIRMedicationAdministrationDosage.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRMedicationAdministrationStatus' => 'FHIRElement/FHIRMedicationAdministrationStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRMedicationDispense' => 'FHIRDomainResource/FHIRMedicationDispense.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedicationDispense\\FHIRMedicationDispenseDosageInstruction' => 'FHIRResource/FHIRMedicationDispense/FHIRMedicationDispenseDosageInstruction.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedicationDispense\\FHIRMedicationDispenseSubstitution' => 'FHIRResource/FHIRMedicationDispense/FHIRMedicationDispenseSubstitution.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRMedicationDispenseStatus' => 'FHIRElement/FHIRMedicationDispenseStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRMedicationOrder' => 'FHIRDomainResource/FHIRMedicationOrder.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedicationOrder\\FHIRMedicationOrderDosageInstruction' => 'FHIRResource/FHIRMedicationOrder/FHIRMedicationOrderDosageInstruction.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedicationOrder\\FHIRMedicationOrderDispenseRequest' => 'FHIRResource/FHIRMedicationOrder/FHIRMedicationOrderDispenseRequest.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedicationOrder\\FHIRMedicationOrderSubstitution' => 'FHIRResource/FHIRMedicationOrder/FHIRMedicationOrderSubstitution.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRMedicationOrderStatus' => 'FHIRElement/FHIRMedicationOrderStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRMedicationPrescription' => 'FHIRDomainResource/FHIRMedicationPrescription.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedicationPrescription\\FHIRMedicationPrescriptionDosageInstruction' => 'FHIRResource/FHIRMedicationPrescription/FHIRMedicationPrescriptionDosageInstruction.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedicationPrescription\\FHIRMedicationPrescriptionDispense' => 'FHIRResource/FHIRMedicationPrescription/FHIRMedicationPrescriptionDispense.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedicationPrescription\\FHIRMedicationPrescriptionSubstitution' => 'FHIRResource/FHIRMedicationPrescription/FHIRMedicationPrescriptionSubstitution.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRMedicationPrescriptionStatus' => 'FHIRElement/FHIRMedicationPrescriptionStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRMedicationStatement' => 'FHIRDomainResource/FHIRMedicationStatement.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMedicationStatement\\FHIRMedicationStatementDosage' => 'FHIRResource/FHIRMedicationStatement/FHIRMedicationStatementDosage.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRMedicationStatementStatus' => 'FHIRElement/FHIRMedicationStatementStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRMessageHeader' => 'FHIRDomainResource/FHIRMessageHeader.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMessageHeader\\FHIRMessageHeaderResponse' => 'FHIRResource/FHIRMessageHeader/FHIRMessageHeaderResponse.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMessageHeader\\FHIRMessageHeaderSource' => 'FHIRResource/FHIRMessageHeader/FHIRMessageHeaderSource.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRMessageHeader\\FHIRMessageHeaderDestination' => 'FHIRResource/FHIRMessageHeader/FHIRMessageHeaderDestination.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRResponseType' => 'FHIRElement/FHIRResponseType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRNamingSystem' => 'FHIRDomainResource/FHIRNamingSystem.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRNamingSystem\\FHIRNamingSystemContact' => 'FHIRResource/FHIRNamingSystem/FHIRNamingSystemContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRNamingSystem\\FHIRNamingSystemUniqueId' => 'FHIRResource/FHIRNamingSystem/FHIRNamingSystemUniqueId.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRNamingSystemType' => 'FHIRElement/FHIRNamingSystemType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRNamingSystemIdentifierType' => 'FHIRElement/FHIRNamingSystemIdentifierType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRNutritionOrder' => 'FHIRDomainResource/FHIRNutritionOrder.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderOralDiet' => 'FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderOralDiet.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderNutrient' => 'FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderNutrient.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderTexture' => 'FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderTexture.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderSupplement' => 'FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderSupplement.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderEnteralFormula' => 'FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderEnteralFormula.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderAdministration' => 'FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderAdministration.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRNutritionOrderStatus' => 'FHIRElement/FHIRNutritionOrderStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRObservation' => 'FHIRDomainResource/FHIRObservation.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRObservation\\FHIRObservationReferenceRange' => 'FHIRResource/FHIRObservation/FHIRObservationReferenceRange.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRObservation\\FHIRObservationRelated' => 'FHIRResource/FHIRObservation/FHIRObservationRelated.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRObservation\\FHIRObservationComponent' => 'FHIRResource/FHIRObservation/FHIRObservationComponent.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRObservationStatus' => 'FHIRElement/FHIRObservationStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRObservationRelationshipType' => 'FHIRElement/FHIRObservationRelationshipType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIROperationDefinition' => 'FHIRDomainResource/FHIROperationDefinition.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIROperationDefinition\\FHIROperationDefinitionContact' => 'FHIRResource/FHIROperationDefinition/FHIROperationDefinitionContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIROperationDefinition\\FHIROperationDefinitionParameter' => 'FHIRResource/FHIROperationDefinition/FHIROperationDefinitionParameter.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIROperationDefinition\\FHIROperationDefinitionBinding' => 'FHIRResource/FHIROperationDefinition/FHIROperationDefinitionBinding.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIROperationParameterUse' => 'FHIRElement/FHIROperationParameterUse.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIROperationKind' => 'FHIRElement/FHIROperationKind.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIROperationOutcome' => 'FHIRDomainResource/FHIROperationOutcome.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIROperationOutcome\\FHIROperationOutcomeIssue' => 'FHIRResource/FHIROperationOutcome/FHIROperationOutcomeIssue.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRIssueType' => 'FHIRElement/FHIRIssueType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRIssueSeverity' => 'FHIRElement/FHIRIssueSeverity.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIROrder' => 'FHIRDomainResource/FHIROrder.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIROrder\\FHIROrderWhen' => 'FHIRResource/FHIROrder/FHIROrderWhen.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIROrderResponse' => 'FHIRDomainResource/FHIROrderResponse.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIROrderStatus' => 'FHIRElement/FHIROrderStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIROrganization' => 'FHIRDomainResource/FHIROrganization.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIROrganization\\FHIROrganizationContact' => 'FHIRResource/FHIROrganization/FHIROrganizationContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRParameters' => 'FHIRResource/FHIRParameters.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRParameters\\FHIRParametersParameter' => 'FHIRResource/FHIRParameters/FHIRParametersParameter.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRPatient' => 'FHIRDomainResource/FHIRPatient.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRPatient\\FHIRPatientContact' => 'FHIRResource/FHIRPatient/FHIRPatientContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRPatient\\FHIRPatientAnimal' => 'FHIRResource/FHIRPatient/FHIRPatientAnimal.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRPatient\\FHIRPatientCommunication' => 'FHIRResource/FHIRPatient/FHIRPatientCommunication.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRPatient\\FHIRPatientLink' => 'FHIRResource/FHIRPatient/FHIRPatientLink.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRLinkType' => 'FHIRElement/FHIRLinkType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRPaymentNotice' => 'FHIRDomainResource/FHIRPaymentNotice.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRPaymentReconciliation' => 'FHIRDomainResource/FHIRPaymentReconciliation.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRPaymentReconciliation\\FHIRPaymentReconciliationDetail' => 'FHIRResource/FHIRPaymentReconciliation/FHIRPaymentReconciliationDetail.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRPaymentReconciliation\\FHIRPaymentReconciliationNote' => 'FHIRResource/FHIRPaymentReconciliation/FHIRPaymentReconciliationNote.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRPerson' => 'FHIRDomainResource/FHIRPerson.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRPerson\\FHIRPersonLink' => 'FHIRResource/FHIRPerson/FHIRPersonLink.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRIdentityAssuranceLevel' => 'FHIRElement/FHIRIdentityAssuranceLevel.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRPractitioner' => 'FHIRDomainResource/FHIRPractitioner.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRPractitioner\\FHIRPractitionerPractitionerRole' => 'FHIRResource/FHIRPractitioner/FHIRPractitionerPractitionerRole.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRPractitioner\\FHIRPractitionerQualification' => 'FHIRResource/FHIRPractitioner/FHIRPractitionerQualification.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRProcedure' => 'FHIRDomainResource/FHIRProcedure.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRProcedure\\FHIRProcedurePerformer' => 'FHIRResource/FHIRProcedure/FHIRProcedurePerformer.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRProcedure\\FHIRProcedureFocalDevice' => 'FHIRResource/FHIRProcedure/FHIRProcedureFocalDevice.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRProcedureStatus' => 'FHIRElement/FHIRProcedureStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRProcedureRequest' => 'FHIRDomainResource/FHIRProcedureRequest.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRProcedureRequestPriority' => 'FHIRElement/FHIRProcedureRequestPriority.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRProcedureRequestStatus' => 'FHIRElement/FHIRProcedureRequestStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRProcessRequest' => 'FHIRDomainResource/FHIRProcessRequest.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRProcessRequest\\FHIRProcessRequestItem' => 'FHIRResource/FHIRProcessRequest/FHIRProcessRequestItem.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRActionList' => 'FHIRElement/FHIRActionList.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRProcessResponse' => 'FHIRDomainResource/FHIRProcessResponse.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRProcessResponse\\FHIRProcessResponseNotes' => 'FHIRResource/FHIRProcessResponse/FHIRProcessResponseNotes.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRProvenance' => 'FHIRDomainResource/FHIRProvenance.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRProvenance\\FHIRProvenanceAgent' => 'FHIRResource/FHIRProvenance/FHIRProvenanceAgent.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRProvenance\\FHIRProvenanceRelatedAgent' => 'FHIRResource/FHIRProvenance/FHIRProvenanceRelatedAgent.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRProvenance\\FHIRProvenanceEntity' => 'FHIRResource/FHIRProvenance/FHIRProvenanceEntity.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRProvenanceEntityRole' => 'FHIRElement/FHIRProvenanceEntityRole.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRQuestionnaire' => 'FHIRDomainResource/FHIRQuestionnaire.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRQuestionnaire\\FHIRQuestionnaireGroup' => 'FHIRResource/FHIRQuestionnaire/FHIRQuestionnaireGroup.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRQuestionnaire\\FHIRQuestionnaireQuestion' => 'FHIRResource/FHIRQuestionnaire/FHIRQuestionnaireQuestion.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRQuestionnaireStatus' => 'FHIRElement/FHIRQuestionnaireStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAnswerFormat' => 'FHIRElement/FHIRAnswerFormat.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRQuestionnaireAnswers' => 'FHIRDomainResource/FHIRQuestionnaireAnswers.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRQuestionnaireAnswers\\FHIRQuestionnaireAnswersGroup' => 'FHIRResource/FHIRQuestionnaireAnswers/FHIRQuestionnaireAnswersGroup.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRQuestionnaireAnswers\\FHIRQuestionnaireAnswersQuestion' => 'FHIRResource/FHIRQuestionnaireAnswers/FHIRQuestionnaireAnswersQuestion.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRQuestionnaireAnswers\\FHIRQuestionnaireAnswersAnswer' => 'FHIRResource/FHIRQuestionnaireAnswers/FHIRQuestionnaireAnswersAnswer.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRQuestionnaireAnswersStatus' => 'FHIRElement/FHIRQuestionnaireAnswersStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRQuestionnaireResponse' => 'FHIRDomainResource/FHIRQuestionnaireResponse.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRQuestionnaireResponse\\FHIRQuestionnaireResponseGroup' => 'FHIRResource/FHIRQuestionnaireResponse/FHIRQuestionnaireResponseGroup.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRQuestionnaireResponse\\FHIRQuestionnaireResponseQuestion' => 'FHIRResource/FHIRQuestionnaireResponse/FHIRQuestionnaireResponseQuestion.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRQuestionnaireResponse\\FHIRQuestionnaireResponseAnswer' => 'FHIRResource/FHIRQuestionnaireResponse/FHIRQuestionnaireResponseAnswer.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRQuestionnaireResponseStatus' => 'FHIRElement/FHIRQuestionnaireResponseStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRReferralRequest' => 'FHIRDomainResource/FHIRReferralRequest.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRReferralStatus' => 'FHIRElement/FHIRReferralStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRRelatedPerson' => 'FHIRDomainResource/FHIRRelatedPerson.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRRiskAssessment' => 'FHIRDomainResource/FHIRRiskAssessment.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRRiskAssessment\\FHIRRiskAssessmentPrediction' => 'FHIRResource/FHIRRiskAssessment/FHIRRiskAssessmentPrediction.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRSchedule' => 'FHIRDomainResource/FHIRSchedule.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRSearchParameter' => 'FHIRDomainResource/FHIRSearchParameter.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRSearchParameter\\FHIRSearchParameterContact' => 'FHIRResource/FHIRSearchParameter/FHIRSearchParameterContact.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRXPathUsageType' => 'FHIRElement/FHIRXPathUsageType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRSlot' => 'FHIRDomainResource/FHIRSlot.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSlotStatus' => 'FHIRElement/FHIRSlotStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRSpecimen' => 'FHIRDomainResource/FHIRSpecimen.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRSpecimen\\FHIRSpecimenCollection' => 'FHIRResource/FHIRSpecimen/FHIRSpecimenCollection.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRSpecimen\\FHIRSpecimenTreatment' => 'FHIRResource/FHIRSpecimen/FHIRSpecimenTreatment.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRSpecimen\\FHIRSpecimenContainer' => 'FHIRResource/FHIRSpecimen/FHIRSpecimenContainer.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSpecimenStatus' => 'FHIRElement/FHIRSpecimenStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRStructureDefinition' => 'FHIRDomainResource/FHIRStructureDefinition.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRStructureDefinition\\FHIRStructureDefinitionContact' => 'FHIRResource/FHIRStructureDefinition/FHIRStructureDefinitionContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRStructureDefinition\\FHIRStructureDefinitionMapping' => 'FHIRResource/FHIRStructureDefinition/FHIRStructureDefinitionMapping.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRStructureDefinition\\FHIRStructureDefinitionSnapshot' => 'FHIRResource/FHIRStructureDefinition/FHIRStructureDefinitionSnapshot.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRStructureDefinition\\FHIRStructureDefinitionDifferential' => 'FHIRResource/FHIRStructureDefinition/FHIRStructureDefinitionDifferential.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRStructureDefinitionKind' => 'FHIRElement/FHIRStructureDefinitionKind.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRExtensionContext' => 'FHIRElement/FHIRExtensionContext.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRSubscription' => 'FHIRDomainResource/FHIRSubscription.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRSubscription\\FHIRSubscriptionChannel' => 'FHIRResource/FHIRSubscription/FHIRSubscriptionChannel.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSubscriptionStatus' => 'FHIRElement/FHIRSubscriptionStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSubscriptionChannelType' => 'FHIRElement/FHIRSubscriptionChannelType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRSubstance' => 'FHIRDomainResource/FHIRSubstance.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRSubstance\\FHIRSubstanceInstance' => 'FHIRResource/FHIRSubstance/FHIRSubstanceInstance.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRSubstance\\FHIRSubstanceIngredient' => 'FHIRResource/FHIRSubstance/FHIRSubstanceIngredient.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRSupply' => 'FHIRDomainResource/FHIRSupply.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRSupply\\FHIRSupplyDispense' => 'FHIRResource/FHIRSupply/FHIRSupplyDispense.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSupplyDispenseStatus' => 'FHIRElement/FHIRSupplyDispenseStatus.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSupplyStatus' => 'FHIRElement/FHIRSupplyStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRSupplyDelivery' => 'FHIRDomainResource/FHIRSupplyDelivery.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSupplyDeliveryStatus' => 'FHIRElement/FHIRSupplyDeliveryStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRSupplyRequest' => 'FHIRDomainResource/FHIRSupplyRequest.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRSupplyRequest\\FHIRSupplyRequestWhen' => 'FHIRResource/FHIRSupplyRequest/FHIRSupplyRequestWhen.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRSupplyRequestStatus' => 'FHIRElement/FHIRSupplyRequestStatus.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRTestScript' => 'FHIRDomainResource/FHIRTestScript.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptContact' => 'FHIRResource/FHIRTestScript/FHIRTestScriptContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptMetadata' => 'FHIRResource/FHIRTestScript/FHIRTestScriptMetadata.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptLink' => 'FHIRResource/FHIRTestScript/FHIRTestScriptLink.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptCapability' => 'FHIRResource/FHIRTestScript/FHIRTestScriptCapability.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptFixture' => 'FHIRResource/FHIRTestScript/FHIRTestScriptFixture.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptVariable' => 'FHIRResource/FHIRTestScript/FHIRTestScriptVariable.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptSetup' => 'FHIRResource/FHIRTestScript/FHIRTestScriptSetup.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptAction' => 'FHIRResource/FHIRTestScript/FHIRTestScriptAction.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptOperation' => 'FHIRResource/FHIRTestScript/FHIRTestScriptOperation.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptRequestHeader' => 'FHIRResource/FHIRTestScript/FHIRTestScriptRequestHeader.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptAssert' => 'FHIRResource/FHIRTestScript/FHIRTestScriptAssert.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptTest' => 'FHIRResource/FHIRTestScript/FHIRTestScriptTest.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptAction1' => 'FHIRResource/FHIRTestScript/FHIRTestScriptAction1.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptTeardown' => 'FHIRResource/FHIRTestScript/FHIRTestScriptTeardown.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRTestScript\\FHIRTestScriptAction2' => 'FHIRResource/FHIRTestScript/FHIRTestScriptAction2.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAssertionDirectionType' => 'FHIRElement/FHIRAssertionDirectionType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAssertionResponseTypes' => 'FHIRElement/FHIRAssertionResponseTypes.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRAssertionOperatorType' => 'FHIRElement/FHIRAssertionOperatorType.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRContentType' => 'FHIRElement/FHIRContentType.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRValueSet' => 'FHIRDomainResource/FHIRValueSet.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetContact' => 'FHIRResource/FHIRValueSet/FHIRValueSetContact.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetCodeSystem' => 'FHIRResource/FHIRValueSet/FHIRValueSetCodeSystem.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetConcept' => 'FHIRResource/FHIRValueSet/FHIRValueSetConcept.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetDesignation' => 'FHIRResource/FHIRValueSet/FHIRValueSetDesignation.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetCompose' => 'FHIRResource/FHIRValueSet/FHIRValueSetCompose.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetInclude' => 'FHIRResource/FHIRValueSet/FHIRValueSetInclude.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetConcept1' => 'FHIRResource/FHIRValueSet/FHIRValueSetConcept1.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetFilter' => 'FHIRResource/FHIRValueSet/FHIRValueSetFilter.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetExpansion' => 'FHIRResource/FHIRValueSet/FHIRValueSetExpansion.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetParameter' => 'FHIRResource/FHIRValueSet/FHIRValueSetParameter.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRValueSet\\FHIRValueSetContains' => 'FHIRResource/FHIRValueSet/FHIRValueSetContains.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRFilterOperator' => 'FHIRElement/FHIRFilterOperator.php',
  'PHPFHIRGenerated\\FHIRDomainResource\\FHIRVisionPrescription' => 'FHIRDomainResource/FHIRVisionPrescription.php',
  'PHPFHIRGenerated\\FHIRResource\\FHIRVisionPrescription\\FHIRVisionPrescriptionDispense' => 'FHIRResource/FHIRVisionPrescription/FHIRVisionPrescriptionDispense.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRVisionBase' => 'FHIRElement/FHIRVisionBase.php',
  'PHPFHIRGenerated\\FHIRElement\\FHIRVisionEyes' => 'FHIRElement/FHIRVisionEyes.php',
);

    /** @var bool */
    private static $_registered = false;

    /**
     * @return bool
     * @throws \Exception
     */
    public static function register()
    {
        if (self::$_registered)
            return self::$_registered;
        return self::$_registered = spl_autoload_register(array(__CLASS__, 'loadClass'), true);
    }

    /**
     * @return bool
     */
    public static function unregister()
    {
        self::$_registered = !spl_autoload_unregister(array(__CLASS__, 'loadClass'));
        return !self::$_registered;
    }

    /**
     * Please see associated documentation for more information on what this method looks for.
     *
     * @param string $class
     * @return bool|null
     */
    public static function loadClass($class)
    {
        if (isset(self::$_classMap[$class]))
            return (bool)require sprintf('%s/%s', self::ROOT_DIR, self::$_classMap[$class]);
        return null;
    }
}