<?php

namespace DCarbone\PHPFHIRGenerated\DSTU2;

/*!
 * This class was generated with the PHPFHIR library (https://github.com/dcarbone/php-fhir) using
 * class definitions from HL7 FHIR (https://www.hl7.org/fhir/)
 * 
 * Class creation date: December 26th, 2019 15:43+0000
 * 
 * PHPFHIR Copyright:
 * 
 * Copyright 2016-2019 Daniel Carbone (daniel.p.carbone@gmail.com)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 *
 * FHIR Copyright Notice:
 *
 *   Copyright (c) 2011+, HL7, Inc.
 *   All rights reserved.
 * 
 *   Redistribution and use in source and binary forms, with or without modification,
 *   are permitted provided that the following conditions are met:
 * 
 *    * Redistributions of source code must retain the above copyright notice, this
 *      list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *    * Neither the name of HL7 nor the names of its contributors may be used to
 *      endorse or promote products derived from this software without specific
 *      prior written permission.
 * 
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *   ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 *   IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 *   INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 *   NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 *   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 * 
 * 
 *   Generated on Sat, Oct 24, 2015 07:41+1100 for FHIR v1.0.2
 * 
 *   Note: the schemas & schematrons do not contain all of the rules about what makes resources
 *   valid. Implementers will still need to be familiar with the content of the specification and with
 *   any profiles that apply to the resources in order to make a conformant implementation.
 * 
 */

/**
 * Class PHPFHIRTypeMap
 * @package \DCarbone\PHPFHIRGenerated\DSTU2
 */
abstract class PHPFHIRTypeMap
{
    /**
     * This array represents every type known to this lib
     * @var array
     */
    private static $_typeMap = [
        PHPFHIRConstants::TYPE_NAME_ACCOUNT => PHPFHIRConstants::TYPE_CLASS_ACCOUNT,
        PHPFHIRConstants::TYPE_NAME_ACCOUNT_STATUS => PHPFHIRConstants::TYPE_CLASS_ACCOUNT_STATUS,
        PHPFHIRConstants::TYPE_NAME_ACCOUNT_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ACCOUNT_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ACTION_LIST => PHPFHIRConstants::TYPE_CLASS_ACTION_LIST,
        PHPFHIRConstants::TYPE_NAME_ACTION_LIST_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ACTION_LIST_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ADDRESS => PHPFHIRConstants::TYPE_CLASS_ADDRESS,
        PHPFHIRConstants::TYPE_NAME_ADDRESS_TYPE => PHPFHIRConstants::TYPE_CLASS_ADDRESS_TYPE,
        PHPFHIRConstants::TYPE_NAME_ADDRESS_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ADDRESS_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ADDRESS_USE => PHPFHIRConstants::TYPE_CLASS_ADDRESS_USE,
        PHPFHIRConstants::TYPE_NAME_ADDRESS_USE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ADDRESS_USE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ADMINISTRATIVE_GENDER => PHPFHIRConstants::TYPE_CLASS_ADMINISTRATIVE_GENDER,
        PHPFHIRConstants::TYPE_NAME_ADMINISTRATIVE_GENDER_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ADMINISTRATIVE_GENDER_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_AGE => PHPFHIRConstants::TYPE_CLASS_AGE,
        PHPFHIRConstants::TYPE_NAME_AGGREGATION_MODE => PHPFHIRConstants::TYPE_CLASS_AGGREGATION_MODE,
        PHPFHIRConstants::TYPE_NAME_AGGREGATION_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_AGGREGATION_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_DOT_REACTION => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_DOT_REACTION,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_CATEGORY => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_CATEGORY,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_CATEGORY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_CATEGORY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_CERTAINTY => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_CERTAINTY,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_CERTAINTY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_CERTAINTY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_CRITICALITY => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_CRITICALITY,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_CRITICALITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_CRITICALITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_SEVERITY => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_SEVERITY,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_SEVERITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_SEVERITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_STATUS => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_STATUS,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_TYPE => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_TYPE,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ANNOTATION => PHPFHIRConstants::TYPE_CLASS_ANNOTATION,
        PHPFHIRConstants::TYPE_NAME_ANSWER_FORMAT => PHPFHIRConstants::TYPE_CLASS_ANSWER_FORMAT,
        PHPFHIRConstants::TYPE_NAME_ANSWER_FORMAT_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ANSWER_FORMAT_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_APPOINTMENT => PHPFHIRConstants::TYPE_CLASS_APPOINTMENT,
        PHPFHIRConstants::TYPE_NAME_APPOINTMENT_DOT_PARTICIPANT => PHPFHIRConstants::TYPE_CLASS_APPOINTMENT_DOT_PARTICIPANT,
        PHPFHIRConstants::TYPE_NAME_APPOINTMENT_RESPONSE => PHPFHIRConstants::TYPE_CLASS_APPOINTMENT_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_APPOINTMENT_STATUS => PHPFHIRConstants::TYPE_CLASS_APPOINTMENT_STATUS,
        PHPFHIRConstants::TYPE_NAME_APPOINTMENT_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_APPOINTMENT_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ASSERTION_DIRECTION_TYPE => PHPFHIRConstants::TYPE_CLASS_ASSERTION_DIRECTION_TYPE,
        PHPFHIRConstants::TYPE_NAME_ASSERTION_DIRECTION_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ASSERTION_DIRECTION_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ASSERTION_OPERATOR_TYPE => PHPFHIRConstants::TYPE_CLASS_ASSERTION_OPERATOR_TYPE,
        PHPFHIRConstants::TYPE_NAME_ASSERTION_OPERATOR_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ASSERTION_OPERATOR_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ASSERTION_RESPONSE_TYPES => PHPFHIRConstants::TYPE_CLASS_ASSERTION_RESPONSE_TYPES,
        PHPFHIRConstants::TYPE_NAME_ASSERTION_RESPONSE_TYPES_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ASSERTION_RESPONSE_TYPES_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ATTACHMENT => PHPFHIRConstants::TYPE_CLASS_ATTACHMENT,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_DOT_DETAIL => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_DOT_DETAIL,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_DOT_EVENT => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_DOT_EVENT,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_DOT_NETWORK => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_DOT_NETWORK,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_DOT_OBJECT => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_DOT_OBJECT,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_DOT_PARTICIPANT => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_DOT_PARTICIPANT,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_DOT_SOURCE => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_DOT_SOURCE,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_ACTION => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_ACTION,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_ACTION_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_ACTION_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_OUTCOME => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_OUTCOME,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_OUTCOME_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_OUTCOME_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_PARTICIPANT_NETWORK_TYPE => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_PARTICIPANT_NETWORK_TYPE,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT_PARTICIPANT_NETWORK_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT_PARTICIPANT_NETWORK_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_BACKBONE_ELEMENT => PHPFHIRConstants::TYPE_CLASS_BACKBONE_ELEMENT,
        PHPFHIRConstants::TYPE_NAME_BASE_64BINARY => PHPFHIRConstants::TYPE_CLASS_BASE_64BINARY,
        PHPFHIRConstants::TYPE_NAME_BASE_64BINARY_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_BASE_64BINARY_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_BASIC => PHPFHIRConstants::TYPE_CLASS_BASIC,
        PHPFHIRConstants::TYPE_NAME_BINARY => PHPFHIRConstants::TYPE_CLASS_BINARY,
        PHPFHIRConstants::TYPE_NAME_BINDING_STRENGTH => PHPFHIRConstants::TYPE_CLASS_BINDING_STRENGTH,
        PHPFHIRConstants::TYPE_NAME_BINDING_STRENGTH_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_BINDING_STRENGTH_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_BODY_SITE => PHPFHIRConstants::TYPE_CLASS_BODY_SITE,
        PHPFHIRConstants::TYPE_NAME_BOOLEAN => PHPFHIRConstants::TYPE_CLASS_BOOLEAN,
        PHPFHIRConstants::TYPE_NAME_BOOLEAN_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_BOOLEAN_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_BUNDLE => PHPFHIRConstants::TYPE_CLASS_BUNDLE,
        PHPFHIRConstants::TYPE_NAME_BUNDLE_DOT_ENTRY => PHPFHIRConstants::TYPE_CLASS_BUNDLE_DOT_ENTRY,
        PHPFHIRConstants::TYPE_NAME_BUNDLE_DOT_LINK => PHPFHIRConstants::TYPE_CLASS_BUNDLE_DOT_LINK,
        PHPFHIRConstants::TYPE_NAME_BUNDLE_DOT_REQUEST => PHPFHIRConstants::TYPE_CLASS_BUNDLE_DOT_REQUEST,
        PHPFHIRConstants::TYPE_NAME_BUNDLE_DOT_RESPONSE => PHPFHIRConstants::TYPE_CLASS_BUNDLE_DOT_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_BUNDLE_DOT_SEARCH => PHPFHIRConstants::TYPE_CLASS_BUNDLE_DOT_SEARCH,
        PHPFHIRConstants::TYPE_NAME_BUNDLE_TYPE => PHPFHIRConstants::TYPE_CLASS_BUNDLE_TYPE,
        PHPFHIRConstants::TYPE_NAME_BUNDLE_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_BUNDLE_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_DOT_ACTIVITY => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_DOT_ACTIVITY,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_DOT_DETAIL => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_DOT_DETAIL,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_DOT_PARTICIPANT => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_DOT_PARTICIPANT,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_DOT_RELATED_PLAN => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_DOT_RELATED_PLAN,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_ACTIVITY_STATUS => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_ACTIVITY_STATUS,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_ACTIVITY_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_ACTIVITY_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_RELATIONSHIP => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_RELATIONSHIP,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_RELATIONSHIP_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_RELATIONSHIP_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_STATUS => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_STATUS,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CLAIM => PHPFHIRConstants::TYPE_CLASS_CLAIM,
        PHPFHIRConstants::TYPE_NAME_CLAIM_DOT_COVERAGE => PHPFHIRConstants::TYPE_CLASS_CLAIM_DOT_COVERAGE,
        PHPFHIRConstants::TYPE_NAME_CLAIM_DOT_DETAIL => PHPFHIRConstants::TYPE_CLASS_CLAIM_DOT_DETAIL,
        PHPFHIRConstants::TYPE_NAME_CLAIM_DOT_DIAGNOSIS => PHPFHIRConstants::TYPE_CLASS_CLAIM_DOT_DIAGNOSIS,
        PHPFHIRConstants::TYPE_NAME_CLAIM_DOT_ITEM => PHPFHIRConstants::TYPE_CLASS_CLAIM_DOT_ITEM,
        PHPFHIRConstants::TYPE_NAME_CLAIM_DOT_MISSING_TEETH => PHPFHIRConstants::TYPE_CLASS_CLAIM_DOT_MISSING_TEETH,
        PHPFHIRConstants::TYPE_NAME_CLAIM_DOT_PAYEE => PHPFHIRConstants::TYPE_CLASS_CLAIM_DOT_PAYEE,
        PHPFHIRConstants::TYPE_NAME_CLAIM_DOT_PROSTHESIS => PHPFHIRConstants::TYPE_CLASS_CLAIM_DOT_PROSTHESIS,
        PHPFHIRConstants::TYPE_NAME_CLAIM_DOT_SUB_DETAIL => PHPFHIRConstants::TYPE_CLASS_CLAIM_DOT_SUB_DETAIL,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_ADD_ITEM => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_ADD_ITEM,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_ADJUDICATION => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_ADJUDICATION,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_ADJUDICATION_1 => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_ADJUDICATION_1,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_ADJUDICATION_2 => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_ADJUDICATION_2,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_ADJUDICATION_3 => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_ADJUDICATION_3,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_ADJUDICATION_4 => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_ADJUDICATION_4,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_COVERAGE => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_COVERAGE,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_DETAIL => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_DETAIL,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_DETAIL_1 => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_DETAIL_1,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_ERROR => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_ERROR,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_ITEM => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_ITEM,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_NOTE => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_NOTE,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE_DOT_SUB_DETAIL => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE_DOT_SUB_DETAIL,
        PHPFHIRConstants::TYPE_NAME_CLAIM_TYPE => PHPFHIRConstants::TYPE_CLASS_CLAIM_TYPE,
        PHPFHIRConstants::TYPE_NAME_CLAIM_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CLAIM_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CLINICAL_IMPRESSION => PHPFHIRConstants::TYPE_CLASS_CLINICAL_IMPRESSION,
        PHPFHIRConstants::TYPE_NAME_CLINICAL_IMPRESSION_DOT_FINDING => PHPFHIRConstants::TYPE_CLASS_CLINICAL_IMPRESSION_DOT_FINDING,
        PHPFHIRConstants::TYPE_NAME_CLINICAL_IMPRESSION_DOT_INVESTIGATIONS => PHPFHIRConstants::TYPE_CLASS_CLINICAL_IMPRESSION_DOT_INVESTIGATIONS,
        PHPFHIRConstants::TYPE_NAME_CLINICAL_IMPRESSION_DOT_RULED_OUT => PHPFHIRConstants::TYPE_CLASS_CLINICAL_IMPRESSION_DOT_RULED_OUT,
        PHPFHIRConstants::TYPE_NAME_CLINICAL_IMPRESSION_STATUS => PHPFHIRConstants::TYPE_CLASS_CLINICAL_IMPRESSION_STATUS,
        PHPFHIRConstants::TYPE_NAME_CLINICAL_IMPRESSION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CLINICAL_IMPRESSION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CODE => PHPFHIRConstants::TYPE_CLASS_CODE,
        PHPFHIRConstants::TYPE_NAME_CODE_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_CODE_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_CODEABLE_CONCEPT => PHPFHIRConstants::TYPE_CLASS_CODEABLE_CONCEPT,
        PHPFHIRConstants::TYPE_NAME_CODING => PHPFHIRConstants::TYPE_CLASS_CODING,
        PHPFHIRConstants::TYPE_NAME_COMMUNICATION => PHPFHIRConstants::TYPE_CLASS_COMMUNICATION,
        PHPFHIRConstants::TYPE_NAME_COMMUNICATION_DOT_PAYLOAD => PHPFHIRConstants::TYPE_CLASS_COMMUNICATION_DOT_PAYLOAD,
        PHPFHIRConstants::TYPE_NAME_COMMUNICATION_REQUEST => PHPFHIRConstants::TYPE_CLASS_COMMUNICATION_REQUEST,
        PHPFHIRConstants::TYPE_NAME_COMMUNICATION_REQUEST_DOT_PAYLOAD => PHPFHIRConstants::TYPE_CLASS_COMMUNICATION_REQUEST_DOT_PAYLOAD,
        PHPFHIRConstants::TYPE_NAME_COMMUNICATION_REQUEST_STATUS => PHPFHIRConstants::TYPE_CLASS_COMMUNICATION_REQUEST_STATUS,
        PHPFHIRConstants::TYPE_NAME_COMMUNICATION_REQUEST_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_COMMUNICATION_REQUEST_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_COMMUNICATION_STATUS => PHPFHIRConstants::TYPE_CLASS_COMMUNICATION_STATUS,
        PHPFHIRConstants::TYPE_NAME_COMMUNICATION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_COMMUNICATION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION => PHPFHIRConstants::TYPE_CLASS_COMPOSITION,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_DOT_ATTESTER => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_DOT_ATTESTER,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_DOT_EVENT => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_DOT_EVENT,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_DOT_SECTION => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_DOT_SECTION,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_ATTESTATION_MODE => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_ATTESTATION_MODE,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_ATTESTATION_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_ATTESTATION_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_STATUS => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_STATUS,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_COMPOSITION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_DOT_DEPENDS_ON => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_DOT_DEPENDS_ON,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_DOT_ELEMENT => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_DOT_ELEMENT,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_DOT_TARGET => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_DOT_TARGET,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_EQUIVALENCE => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_EQUIVALENCE,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP_EQUIVALENCE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP_EQUIVALENCE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONDITION => PHPFHIRConstants::TYPE_CLASS_CONDITION,
        PHPFHIRConstants::TYPE_NAME_CONDITION_DOT_EVIDENCE => PHPFHIRConstants::TYPE_CLASS_CONDITION_DOT_EVIDENCE,
        PHPFHIRConstants::TYPE_NAME_CONDITION_DOT_STAGE => PHPFHIRConstants::TYPE_CLASS_CONDITION_DOT_STAGE,
        PHPFHIRConstants::TYPE_NAME_CONDITIONAL_DELETE_STATUS => PHPFHIRConstants::TYPE_CLASS_CONDITIONAL_DELETE_STATUS,
        PHPFHIRConstants::TYPE_NAME_CONDITIONAL_DELETE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONDITIONAL_DELETE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONDITION_VERIFICATION_STATUS => PHPFHIRConstants::TYPE_CLASS_CONDITION_VERIFICATION_STATUS,
        PHPFHIRConstants::TYPE_NAME_CONDITION_VERIFICATION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONDITION_VERIFICATION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_CERTIFICATE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_CERTIFICATE,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_DOCUMENT => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_DOCUMENT,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_ENDPOINT => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_ENDPOINT,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_EVENT => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_EVENT,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_IMPLEMENTATION => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_IMPLEMENTATION,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_INTERACTION => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_INTERACTION,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_INTERACTION_1 => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_INTERACTION_1,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_MESSAGING => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_MESSAGING,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_OPERATION => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_OPERATION,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_RESOURCE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_RESOURCE,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_REST => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_REST,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_SEARCH_PARAM => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_SEARCH_PARAM,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_SECURITY => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_SECURITY,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_DOT_SOFTWARE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_DOT_SOFTWARE,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_EVENT_MODE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_EVENT_MODE,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_EVENT_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_EVENT_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_RESOURCE_STATUS => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_RESOURCE_STATUS,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_RESOURCE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_RESOURCE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_STATEMENT_KIND => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_STATEMENT_KIND,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE_STATEMENT_KIND_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE_STATEMENT_KIND_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONSTRAINT_SEVERITY => PHPFHIRConstants::TYPE_CLASS_CONSTRAINT_SEVERITY,
        PHPFHIRConstants::TYPE_NAME_CONSTRAINT_SEVERITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONSTRAINT_SEVERITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONTACT_POINT => PHPFHIRConstants::TYPE_CLASS_CONTACT_POINT,
        PHPFHIRConstants::TYPE_NAME_CONTACT_POINT_SYSTEM => PHPFHIRConstants::TYPE_CLASS_CONTACT_POINT_SYSTEM,
        PHPFHIRConstants::TYPE_NAME_CONTACT_POINT_SYSTEM_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONTACT_POINT_SYSTEM_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONTACT_POINT_USE => PHPFHIRConstants::TYPE_CLASS_CONTACT_POINT_USE,
        PHPFHIRConstants::TYPE_NAME_CONTACT_POINT_USE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONTACT_POINT_USE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONTENT_TYPE => PHPFHIRConstants::TYPE_CLASS_CONTENT_TYPE,
        PHPFHIRConstants::TYPE_NAME_CONTENT_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_CONTENT_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_CONTRACT => PHPFHIRConstants::TYPE_CLASS_CONTRACT,
        PHPFHIRConstants::TYPE_NAME_CONTRACT_DOT_ACTOR => PHPFHIRConstants::TYPE_CLASS_CONTRACT_DOT_ACTOR,
        PHPFHIRConstants::TYPE_NAME_CONTRACT_DOT_ACTOR_1 => PHPFHIRConstants::TYPE_CLASS_CONTRACT_DOT_ACTOR_1,
        PHPFHIRConstants::TYPE_NAME_CONTRACT_DOT_FRIENDLY => PHPFHIRConstants::TYPE_CLASS_CONTRACT_DOT_FRIENDLY,
        PHPFHIRConstants::TYPE_NAME_CONTRACT_DOT_LEGAL => PHPFHIRConstants::TYPE_CLASS_CONTRACT_DOT_LEGAL,
        PHPFHIRConstants::TYPE_NAME_CONTRACT_DOT_RULE => PHPFHIRConstants::TYPE_CLASS_CONTRACT_DOT_RULE,
        PHPFHIRConstants::TYPE_NAME_CONTRACT_DOT_SIGNER => PHPFHIRConstants::TYPE_CLASS_CONTRACT_DOT_SIGNER,
        PHPFHIRConstants::TYPE_NAME_CONTRACT_DOT_TERM => PHPFHIRConstants::TYPE_CLASS_CONTRACT_DOT_TERM,
        PHPFHIRConstants::TYPE_NAME_CONTRACT_DOT_VALUED_ITEM => PHPFHIRConstants::TYPE_CLASS_CONTRACT_DOT_VALUED_ITEM,
        PHPFHIRConstants::TYPE_NAME_CONTRACT_DOT_VALUED_ITEM_1 => PHPFHIRConstants::TYPE_CLASS_CONTRACT_DOT_VALUED_ITEM_1,
        PHPFHIRConstants::TYPE_NAME_COUNT => PHPFHIRConstants::TYPE_CLASS_COUNT,
        PHPFHIRConstants::TYPE_NAME_COVERAGE => PHPFHIRConstants::TYPE_CLASS_COVERAGE,
        PHPFHIRConstants::TYPE_NAME_DATA_ELEMENT => PHPFHIRConstants::TYPE_CLASS_DATA_ELEMENT,
        PHPFHIRConstants::TYPE_NAME_DATA_ELEMENT_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_DATA_ELEMENT_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_DATA_ELEMENT_DOT_MAPPING => PHPFHIRConstants::TYPE_CLASS_DATA_ELEMENT_DOT_MAPPING,
        PHPFHIRConstants::TYPE_NAME_DATA_ELEMENT_STRINGENCY => PHPFHIRConstants::TYPE_CLASS_DATA_ELEMENT_STRINGENCY,
        PHPFHIRConstants::TYPE_NAME_DATA_ELEMENT_STRINGENCY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DATA_ELEMENT_STRINGENCY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DATE => PHPFHIRConstants::TYPE_CLASS_DATE,
        PHPFHIRConstants::TYPE_NAME_DATE_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_DATE_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_DATE_TIME => PHPFHIRConstants::TYPE_CLASS_DATE_TIME,
        PHPFHIRConstants::TYPE_NAME_DATE_TIME_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_DATE_TIME_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_DAYS_OF_WEEK => PHPFHIRConstants::TYPE_CLASS_DAYS_OF_WEEK,
        PHPFHIRConstants::TYPE_NAME_DAYS_OF_WEEK_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DAYS_OF_WEEK_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DECIMAL => PHPFHIRConstants::TYPE_CLASS_DECIMAL,
        PHPFHIRConstants::TYPE_NAME_DECIMAL_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_DECIMAL_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_DETECTED_ISSUE => PHPFHIRConstants::TYPE_CLASS_DETECTED_ISSUE,
        PHPFHIRConstants::TYPE_NAME_DETECTED_ISSUE_DOT_MITIGATION => PHPFHIRConstants::TYPE_CLASS_DETECTED_ISSUE_DOT_MITIGATION,
        PHPFHIRConstants::TYPE_NAME_DETECTED_ISSUE_SEVERITY => PHPFHIRConstants::TYPE_CLASS_DETECTED_ISSUE_SEVERITY,
        PHPFHIRConstants::TYPE_NAME_DETECTED_ISSUE_SEVERITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DETECTED_ISSUE_SEVERITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DEVICE => PHPFHIRConstants::TYPE_CLASS_DEVICE,
        PHPFHIRConstants::TYPE_NAME_DEVICE_COMPONENT => PHPFHIRConstants::TYPE_CLASS_DEVICE_COMPONENT,
        PHPFHIRConstants::TYPE_NAME_DEVICE_COMPONENT_DOT_PRODUCTION_SPECIFICATION => PHPFHIRConstants::TYPE_CLASS_DEVICE_COMPONENT_DOT_PRODUCTION_SPECIFICATION,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_DOT_CALIBRATION => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_DOT_CALIBRATION,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_CALIBRATION_STATE => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_CALIBRATION_STATE,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_CALIBRATION_STATE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_CALIBRATION_STATE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_CALIBRATION_TYPE => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_CALIBRATION_TYPE,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_CALIBRATION_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_CALIBRATION_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_CATEGORY => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_CATEGORY,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_CATEGORY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_CATEGORY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_COLOR => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_COLOR,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_COLOR_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_COLOR_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_OPERATIONAL_STATUS => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_OPERATIONAL_STATUS,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC_OPERATIONAL_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC_OPERATIONAL_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DEVICE_STATUS => PHPFHIRConstants::TYPE_CLASS_DEVICE_STATUS,
        PHPFHIRConstants::TYPE_NAME_DEVICE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DEVICE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DEVICE_USE_REQUEST => PHPFHIRConstants::TYPE_CLASS_DEVICE_USE_REQUEST,
        PHPFHIRConstants::TYPE_NAME_DEVICE_USE_REQUEST_PRIORITY => PHPFHIRConstants::TYPE_CLASS_DEVICE_USE_REQUEST_PRIORITY,
        PHPFHIRConstants::TYPE_NAME_DEVICE_USE_REQUEST_PRIORITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DEVICE_USE_REQUEST_PRIORITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DEVICE_USE_REQUEST_STATUS => PHPFHIRConstants::TYPE_CLASS_DEVICE_USE_REQUEST_STATUS,
        PHPFHIRConstants::TYPE_NAME_DEVICE_USE_REQUEST_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DEVICE_USE_REQUEST_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DEVICE_USE_STATEMENT => PHPFHIRConstants::TYPE_CLASS_DEVICE_USE_STATEMENT,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_DOT_EVENT => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_DOT_EVENT,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_DOT_ITEM => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_DOT_ITEM,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_PRIORITY => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_PRIORITY,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_PRIORITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_PRIORITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_STATUS => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_STATUS,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_REPORT => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_REPORT,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_REPORT_DOT_IMAGE => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_REPORT_DOT_IMAGE,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_REPORT_STATUS => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_REPORT_STATUS,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_REPORT_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_REPORT_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DIGITAL_MEDIA_TYPE => PHPFHIRConstants::TYPE_CLASS_DIGITAL_MEDIA_TYPE,
        PHPFHIRConstants::TYPE_NAME_DIGITAL_MEDIA_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DIGITAL_MEDIA_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DISTANCE => PHPFHIRConstants::TYPE_CLASS_DISTANCE,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_MANIFEST => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_MANIFEST,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_MANIFEST_DOT_CONTENT => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_MANIFEST_DOT_CONTENT,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_MANIFEST_DOT_RELATED => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_MANIFEST_DOT_RELATED,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_MODE => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_MODE,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_CONTENT => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_CONTENT,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_CONTEXT => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_CONTEXT,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_RELATED => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_RELATED,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_DOT_RELATES_TO => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_DOT_RELATES_TO,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_STATUS => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_STATUS,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_RELATIONSHIP_TYPE => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_RELATIONSHIP_TYPE,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_RELATIONSHIP_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_RELATIONSHIP_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_DOMAIN_RESOURCE => PHPFHIRConstants::TYPE_CLASS_DOMAIN_RESOURCE,
        PHPFHIRConstants::TYPE_NAME_DURATION => PHPFHIRConstants::TYPE_CLASS_DURATION,
        PHPFHIRConstants::TYPE_NAME_ELEMENT => PHPFHIRConstants::TYPE_CLASS_ELEMENT,
        PHPFHIRConstants::TYPE_NAME_ELEMENT_DEFINITION => PHPFHIRConstants::TYPE_CLASS_ELEMENT_DEFINITION,
        PHPFHIRConstants::TYPE_NAME_ELEMENT_DEFINITION_DOT_BASE => PHPFHIRConstants::TYPE_CLASS_ELEMENT_DEFINITION_DOT_BASE,
        PHPFHIRConstants::TYPE_NAME_ELEMENT_DEFINITION_DOT_BINDING => PHPFHIRConstants::TYPE_CLASS_ELEMENT_DEFINITION_DOT_BINDING,
        PHPFHIRConstants::TYPE_NAME_ELEMENT_DEFINITION_DOT_CONSTRAINT => PHPFHIRConstants::TYPE_CLASS_ELEMENT_DEFINITION_DOT_CONSTRAINT,
        PHPFHIRConstants::TYPE_NAME_ELEMENT_DEFINITION_DOT_MAPPING => PHPFHIRConstants::TYPE_CLASS_ELEMENT_DEFINITION_DOT_MAPPING,
        PHPFHIRConstants::TYPE_NAME_ELEMENT_DEFINITION_DOT_SLICING => PHPFHIRConstants::TYPE_CLASS_ELEMENT_DEFINITION_DOT_SLICING,
        PHPFHIRConstants::TYPE_NAME_ELEMENT_DEFINITION_DOT_TYPE => PHPFHIRConstants::TYPE_CLASS_ELEMENT_DEFINITION_DOT_TYPE,
        PHPFHIRConstants::TYPE_NAME_ELIGIBILITY_REQUEST => PHPFHIRConstants::TYPE_CLASS_ELIGIBILITY_REQUEST,
        PHPFHIRConstants::TYPE_NAME_ELIGIBILITY_RESPONSE => PHPFHIRConstants::TYPE_CLASS_ELIGIBILITY_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_DOT_HOSPITALIZATION => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_DOT_HOSPITALIZATION,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_DOT_LOCATION => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_DOT_LOCATION,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_DOT_PARTICIPANT => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_DOT_PARTICIPANT,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_DOT_STATUS_HISTORY => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_DOT_STATUS_HISTORY,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_CLASS => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_CLASS,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_CLASS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_CLASS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_LOCATION_STATUS => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_LOCATION_STATUS,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_LOCATION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_LOCATION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_STATE => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_STATE,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER_STATE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER_STATE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ENROLLMENT_REQUEST => PHPFHIRConstants::TYPE_CLASS_ENROLLMENT_REQUEST,
        PHPFHIRConstants::TYPE_NAME_ENROLLMENT_RESPONSE => PHPFHIRConstants::TYPE_CLASS_ENROLLMENT_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_EPISODE_OF_CARE => PHPFHIRConstants::TYPE_CLASS_EPISODE_OF_CARE,
        PHPFHIRConstants::TYPE_NAME_EPISODE_OF_CARE_DOT_CARE_TEAM => PHPFHIRConstants::TYPE_CLASS_EPISODE_OF_CARE_DOT_CARE_TEAM,
        PHPFHIRConstants::TYPE_NAME_EPISODE_OF_CARE_DOT_STATUS_HISTORY => PHPFHIRConstants::TYPE_CLASS_EPISODE_OF_CARE_DOT_STATUS_HISTORY,
        PHPFHIRConstants::TYPE_NAME_EPISODE_OF_CARE_STATUS => PHPFHIRConstants::TYPE_CLASS_EPISODE_OF_CARE_STATUS,
        PHPFHIRConstants::TYPE_NAME_EPISODE_OF_CARE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_EPISODE_OF_CARE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_EVENT_TIMING => PHPFHIRConstants::TYPE_CLASS_EVENT_TIMING,
        PHPFHIRConstants::TYPE_NAME_EVENT_TIMING_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_EVENT_TIMING_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_EXPLANATION_OF_BENEFIT => PHPFHIRConstants::TYPE_CLASS_EXPLANATION_OF_BENEFIT,
        PHPFHIRConstants::TYPE_NAME_EXTENSION => PHPFHIRConstants::TYPE_CLASS_EXTENSION,
        PHPFHIRConstants::TYPE_NAME_EXTENSION_CONTEXT => PHPFHIRConstants::TYPE_CLASS_EXTENSION_CONTEXT,
        PHPFHIRConstants::TYPE_NAME_EXTENSION_CONTEXT_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_EXTENSION_CONTEXT_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_FAMILY_HISTORY_STATUS => PHPFHIRConstants::TYPE_CLASS_FAMILY_HISTORY_STATUS,
        PHPFHIRConstants::TYPE_NAME_FAMILY_HISTORY_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_FAMILY_HISTORY_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_FAMILY_MEMBER_HISTORY => PHPFHIRConstants::TYPE_CLASS_FAMILY_MEMBER_HISTORY,
        PHPFHIRConstants::TYPE_NAME_FAMILY_MEMBER_HISTORY_DOT_CONDITION => PHPFHIRConstants::TYPE_CLASS_FAMILY_MEMBER_HISTORY_DOT_CONDITION,
        PHPFHIRConstants::TYPE_NAME_FILTER_OPERATOR => PHPFHIRConstants::TYPE_CLASS_FILTER_OPERATOR,
        PHPFHIRConstants::TYPE_NAME_FILTER_OPERATOR_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_FILTER_OPERATOR_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_FLAG => PHPFHIRConstants::TYPE_CLASS_FLAG,
        PHPFHIRConstants::TYPE_NAME_FLAG_STATUS => PHPFHIRConstants::TYPE_CLASS_FLAG_STATUS,
        PHPFHIRConstants::TYPE_NAME_FLAG_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_FLAG_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_GOAL => PHPFHIRConstants::TYPE_CLASS_GOAL,
        PHPFHIRConstants::TYPE_NAME_GOAL_DOT_OUTCOME => PHPFHIRConstants::TYPE_CLASS_GOAL_DOT_OUTCOME,
        PHPFHIRConstants::TYPE_NAME_GOAL_STATUS => PHPFHIRConstants::TYPE_CLASS_GOAL_STATUS,
        PHPFHIRConstants::TYPE_NAME_GOAL_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_GOAL_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_GROUP => PHPFHIRConstants::TYPE_CLASS_GROUP,
        PHPFHIRConstants::TYPE_NAME_GROUP_DOT_CHARACTERISTIC => PHPFHIRConstants::TYPE_CLASS_GROUP_DOT_CHARACTERISTIC,
        PHPFHIRConstants::TYPE_NAME_GROUP_DOT_MEMBER => PHPFHIRConstants::TYPE_CLASS_GROUP_DOT_MEMBER,
        PHPFHIRConstants::TYPE_NAME_GROUP_TYPE => PHPFHIRConstants::TYPE_CLASS_GROUP_TYPE,
        PHPFHIRConstants::TYPE_NAME_GROUP_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_GROUP_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_GUIDE_DEPENDENCY_TYPE => PHPFHIRConstants::TYPE_CLASS_GUIDE_DEPENDENCY_TYPE,
        PHPFHIRConstants::TYPE_NAME_GUIDE_DEPENDENCY_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_GUIDE_DEPENDENCY_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_GUIDE_PAGE_KIND => PHPFHIRConstants::TYPE_CLASS_GUIDE_PAGE_KIND,
        PHPFHIRConstants::TYPE_NAME_GUIDE_PAGE_KIND_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_GUIDE_PAGE_KIND_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_GUIDE_RESOURCE_PURPOSE => PHPFHIRConstants::TYPE_CLASS_GUIDE_RESOURCE_PURPOSE,
        PHPFHIRConstants::TYPE_NAME_GUIDE_RESOURCE_PURPOSE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_GUIDE_RESOURCE_PURPOSE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_HEALTHCARE_SERVICE => PHPFHIRConstants::TYPE_CLASS_HEALTHCARE_SERVICE,
        PHPFHIRConstants::TYPE_NAME_HEALTHCARE_SERVICE_DOT_AVAILABLE_TIME => PHPFHIRConstants::TYPE_CLASS_HEALTHCARE_SERVICE_DOT_AVAILABLE_TIME,
        PHPFHIRConstants::TYPE_NAME_HEALTHCARE_SERVICE_DOT_NOT_AVAILABLE => PHPFHIRConstants::TYPE_CLASS_HEALTHCARE_SERVICE_DOT_NOT_AVAILABLE,
        PHPFHIRConstants::TYPE_NAME_HEALTHCARE_SERVICE_DOT_SERVICE_TYPE => PHPFHIRConstants::TYPE_CLASS_HEALTHCARE_SERVICE_DOT_SERVICE_TYPE,
        PHPFHIRConstants::TYPE_NAME_HTTPVERB => PHPFHIRConstants::TYPE_CLASS_HTTPVERB,
        PHPFHIRConstants::TYPE_NAME_HTTPVERB_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_HTTPVERB_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_HUMAN_NAME => PHPFHIRConstants::TYPE_CLASS_HUMAN_NAME,
        PHPFHIRConstants::TYPE_NAME_ID => PHPFHIRConstants::TYPE_CLASS_ID,
        PHPFHIRConstants::TYPE_NAME_ID_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_ID_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_IDENTIFIER => PHPFHIRConstants::TYPE_CLASS_IDENTIFIER,
        PHPFHIRConstants::TYPE_NAME_IDENTIFIER_USE => PHPFHIRConstants::TYPE_CLASS_IDENTIFIER_USE,
        PHPFHIRConstants::TYPE_NAME_IDENTIFIER_USE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_IDENTIFIER_USE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_IDENTITY_ASSURANCE_LEVEL => PHPFHIRConstants::TYPE_CLASS_IDENTITY_ASSURANCE_LEVEL,
        PHPFHIRConstants::TYPE_NAME_IDENTITY_ASSURANCE_LEVEL_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_IDENTITY_ASSURANCE_LEVEL_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_IMAGING_OBJECT_SELECTION => PHPFHIRConstants::TYPE_CLASS_IMAGING_OBJECT_SELECTION,
        PHPFHIRConstants::TYPE_NAME_IMAGING_OBJECT_SELECTION_DOT_FRAMES => PHPFHIRConstants::TYPE_CLASS_IMAGING_OBJECT_SELECTION_DOT_FRAMES,
        PHPFHIRConstants::TYPE_NAME_IMAGING_OBJECT_SELECTION_DOT_INSTANCE => PHPFHIRConstants::TYPE_CLASS_IMAGING_OBJECT_SELECTION_DOT_INSTANCE,
        PHPFHIRConstants::TYPE_NAME_IMAGING_OBJECT_SELECTION_DOT_SERIES => PHPFHIRConstants::TYPE_CLASS_IMAGING_OBJECT_SELECTION_DOT_SERIES,
        PHPFHIRConstants::TYPE_NAME_IMAGING_OBJECT_SELECTION_DOT_STUDY => PHPFHIRConstants::TYPE_CLASS_IMAGING_OBJECT_SELECTION_DOT_STUDY,
        PHPFHIRConstants::TYPE_NAME_IMAGING_STUDY => PHPFHIRConstants::TYPE_CLASS_IMAGING_STUDY,
        PHPFHIRConstants::TYPE_NAME_IMAGING_STUDY_DOT_INSTANCE => PHPFHIRConstants::TYPE_CLASS_IMAGING_STUDY_DOT_INSTANCE,
        PHPFHIRConstants::TYPE_NAME_IMAGING_STUDY_DOT_SERIES => PHPFHIRConstants::TYPE_CLASS_IMAGING_STUDY_DOT_SERIES,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_DOT_EXPLANATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_DOT_EXPLANATION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_DOT_REACTION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_DOT_REACTION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_DOT_VACCINATION_PROTOCOL => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_DOT_VACCINATION_PROTOCOL,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION_DOT_DATE_CRITERION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION_DOT_DATE_CRITERION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION_DOT_PROTOCOL => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION_DOT_PROTOCOL,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION_DOT_RECOMMENDATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION_DOT_RECOMMENDATION,
        PHPFHIRConstants::TYPE_NAME_IMPLEMENTATION_GUIDE => PHPFHIRConstants::TYPE_CLASS_IMPLEMENTATION_GUIDE,
        PHPFHIRConstants::TYPE_NAME_IMPLEMENTATION_GUIDE_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_IMPLEMENTATION_GUIDE_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_IMPLEMENTATION_GUIDE_DOT_DEPENDENCY => PHPFHIRConstants::TYPE_CLASS_IMPLEMENTATION_GUIDE_DOT_DEPENDENCY,
        PHPFHIRConstants::TYPE_NAME_IMPLEMENTATION_GUIDE_DOT_GLOBAL => PHPFHIRConstants::TYPE_CLASS_IMPLEMENTATION_GUIDE_DOT_GLOBAL,
        PHPFHIRConstants::TYPE_NAME_IMPLEMENTATION_GUIDE_DOT_PACKAGE => PHPFHIRConstants::TYPE_CLASS_IMPLEMENTATION_GUIDE_DOT_PACKAGE,
        PHPFHIRConstants::TYPE_NAME_IMPLEMENTATION_GUIDE_DOT_PAGE => PHPFHIRConstants::TYPE_CLASS_IMPLEMENTATION_GUIDE_DOT_PAGE,
        PHPFHIRConstants::TYPE_NAME_IMPLEMENTATION_GUIDE_DOT_RESOURCE => PHPFHIRConstants::TYPE_CLASS_IMPLEMENTATION_GUIDE_DOT_RESOURCE,
        PHPFHIRConstants::TYPE_NAME_INSTANCE_AVAILABILITY => PHPFHIRConstants::TYPE_CLASS_INSTANCE_AVAILABILITY,
        PHPFHIRConstants::TYPE_NAME_INSTANCE_AVAILABILITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_INSTANCE_AVAILABILITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_INSTANT => PHPFHIRConstants::TYPE_CLASS_INSTANT,
        PHPFHIRConstants::TYPE_NAME_INSTANT_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_INSTANT_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_INTEGER => PHPFHIRConstants::TYPE_CLASS_INTEGER,
        PHPFHIRConstants::TYPE_NAME_INTEGER_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_INTEGER_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_ISSUE_SEVERITY => PHPFHIRConstants::TYPE_CLASS_ISSUE_SEVERITY,
        PHPFHIRConstants::TYPE_NAME_ISSUE_SEVERITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ISSUE_SEVERITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ISSUE_TYPE => PHPFHIRConstants::TYPE_CLASS_ISSUE_TYPE,
        PHPFHIRConstants::TYPE_NAME_ISSUE_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ISSUE_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_LINK_TYPE => PHPFHIRConstants::TYPE_CLASS_LINK_TYPE,
        PHPFHIRConstants::TYPE_NAME_LINK_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_LINK_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_LIST => PHPFHIRConstants::TYPE_CLASS_LIST,
        PHPFHIRConstants::TYPE_NAME_LIST_DOT_ENTRY => PHPFHIRConstants::TYPE_CLASS_LIST_DOT_ENTRY,
        PHPFHIRConstants::TYPE_NAME_LIST_MODE => PHPFHIRConstants::TYPE_CLASS_LIST_MODE,
        PHPFHIRConstants::TYPE_NAME_LIST_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_LIST_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_LIST_STATUS => PHPFHIRConstants::TYPE_CLASS_LIST_STATUS,
        PHPFHIRConstants::TYPE_NAME_LIST_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_LIST_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_LOCATION => PHPFHIRConstants::TYPE_CLASS_LOCATION,
        PHPFHIRConstants::TYPE_NAME_LOCATION_DOT_POSITION => PHPFHIRConstants::TYPE_CLASS_LOCATION_DOT_POSITION,
        PHPFHIRConstants::TYPE_NAME_LOCATION_MODE => PHPFHIRConstants::TYPE_CLASS_LOCATION_MODE,
        PHPFHIRConstants::TYPE_NAME_LOCATION_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_LOCATION_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_LOCATION_STATUS => PHPFHIRConstants::TYPE_CLASS_LOCATION_STATUS,
        PHPFHIRConstants::TYPE_NAME_LOCATION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_LOCATION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MARKDOWN => PHPFHIRConstants::TYPE_CLASS_MARKDOWN,
        PHPFHIRConstants::TYPE_NAME_MARKDOWN_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_MARKDOWN_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_MEASMNT_HYPHEN_PRINCIPLE => PHPFHIRConstants::TYPE_CLASS_MEASMNT_HYPHEN_PRINCIPLE,
        PHPFHIRConstants::TYPE_NAME_MEASMNT_HYPHEN_PRINCIPLE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MEASMNT_HYPHEN_PRINCIPLE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MEDIA => PHPFHIRConstants::TYPE_CLASS_MEDIA,
        PHPFHIRConstants::TYPE_NAME_MEDICATION => PHPFHIRConstants::TYPE_CLASS_MEDICATION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DOT_BATCH => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DOT_BATCH,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DOT_CONTENT => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DOT_CONTENT,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DOT_INGREDIENT => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DOT_INGREDIENT,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DOT_PACKAGE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DOT_PACKAGE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DOT_PRODUCT => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DOT_PRODUCT,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ADMINISTRATION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ADMINISTRATION_DOT_DOSAGE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION_DOT_DOSAGE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ADMINISTRATION_STATUS => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION_STATUS,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ADMINISTRATION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE_DOT_DOSAGE_INSTRUCTION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE_DOT_DOSAGE_INSTRUCTION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE_DOT_SUBSTITUTION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE_DOT_SUBSTITUTION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE_STATUS => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE_STATUS,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ORDER => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ORDER,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ORDER_DOT_DISPENSE_REQUEST => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ORDER_DOT_DISPENSE_REQUEST,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ORDER_DOT_DOSAGE_INSTRUCTION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ORDER_DOT_DOSAGE_INSTRUCTION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ORDER_DOT_SUBSTITUTION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ORDER_DOT_SUBSTITUTION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ORDER_STATUS => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ORDER_STATUS,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ORDER_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ORDER_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_STATEMENT => PHPFHIRConstants::TYPE_CLASS_MEDICATION_STATEMENT,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_STATEMENT_DOT_DOSAGE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_STATEMENT_DOT_DOSAGE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_STATEMENT_STATUS => PHPFHIRConstants::TYPE_CLASS_MEDICATION_STATEMENT_STATUS,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_STATEMENT_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MEDICATION_STATEMENT_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_HEADER => PHPFHIRConstants::TYPE_CLASS_MESSAGE_HEADER,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_HEADER_DOT_DESTINATION => PHPFHIRConstants::TYPE_CLASS_MESSAGE_HEADER_DOT_DESTINATION,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_HEADER_DOT_RESPONSE => PHPFHIRConstants::TYPE_CLASS_MESSAGE_HEADER_DOT_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_HEADER_DOT_SOURCE => PHPFHIRConstants::TYPE_CLASS_MESSAGE_HEADER_DOT_SOURCE,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_SIGNIFICANCE_CATEGORY => PHPFHIRConstants::TYPE_CLASS_MESSAGE_SIGNIFICANCE_CATEGORY,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_SIGNIFICANCE_CATEGORY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_MESSAGE_SIGNIFICANCE_CATEGORY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_META => PHPFHIRConstants::TYPE_CLASS_META,
        PHPFHIRConstants::TYPE_NAME_MONEY => PHPFHIRConstants::TYPE_CLASS_MONEY,
        PHPFHIRConstants::TYPE_NAME_NAME_USE => PHPFHIRConstants::TYPE_CLASS_NAME_USE,
        PHPFHIRConstants::TYPE_NAME_NAME_USE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_NAME_USE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_NAMING_SYSTEM => PHPFHIRConstants::TYPE_CLASS_NAMING_SYSTEM,
        PHPFHIRConstants::TYPE_NAME_NAMING_SYSTEM_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_NAMING_SYSTEM_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_NAMING_SYSTEM_DOT_UNIQUE_ID => PHPFHIRConstants::TYPE_CLASS_NAMING_SYSTEM_DOT_UNIQUE_ID,
        PHPFHIRConstants::TYPE_NAME_NAMING_SYSTEM_IDENTIFIER_TYPE => PHPFHIRConstants::TYPE_CLASS_NAMING_SYSTEM_IDENTIFIER_TYPE,
        PHPFHIRConstants::TYPE_NAME_NAMING_SYSTEM_IDENTIFIER_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_NAMING_SYSTEM_IDENTIFIER_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_NAMING_SYSTEM_TYPE => PHPFHIRConstants::TYPE_CLASS_NAMING_SYSTEM_TYPE,
        PHPFHIRConstants::TYPE_NAME_NAMING_SYSTEM_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_NAMING_SYSTEM_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_NARRATIVE => PHPFHIRConstants::TYPE_CLASS_NARRATIVE,
        PHPFHIRConstants::TYPE_NAME_NARRATIVE_STATUS => PHPFHIRConstants::TYPE_CLASS_NARRATIVE_STATUS,
        PHPFHIRConstants::TYPE_NAME_NARRATIVE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_NARRATIVE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_NOTE_TYPE => PHPFHIRConstants::TYPE_CLASS_NOTE_TYPE,
        PHPFHIRConstants::TYPE_NAME_NOTE_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_NOTE_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_NUTRITION_ORDER => PHPFHIRConstants::TYPE_CLASS_NUTRITION_ORDER,
        PHPFHIRConstants::TYPE_NAME_NUTRITION_ORDER_DOT_ADMINISTRATION => PHPFHIRConstants::TYPE_CLASS_NUTRITION_ORDER_DOT_ADMINISTRATION,
        PHPFHIRConstants::TYPE_NAME_NUTRITION_ORDER_DOT_ENTERAL_FORMULA => PHPFHIRConstants::TYPE_CLASS_NUTRITION_ORDER_DOT_ENTERAL_FORMULA,
        PHPFHIRConstants::TYPE_NAME_NUTRITION_ORDER_DOT_NUTRIENT => PHPFHIRConstants::TYPE_CLASS_NUTRITION_ORDER_DOT_NUTRIENT,
        PHPFHIRConstants::TYPE_NAME_NUTRITION_ORDER_DOT_ORAL_DIET => PHPFHIRConstants::TYPE_CLASS_NUTRITION_ORDER_DOT_ORAL_DIET,
        PHPFHIRConstants::TYPE_NAME_NUTRITION_ORDER_DOT_SUPPLEMENT => PHPFHIRConstants::TYPE_CLASS_NUTRITION_ORDER_DOT_SUPPLEMENT,
        PHPFHIRConstants::TYPE_NAME_NUTRITION_ORDER_DOT_TEXTURE => PHPFHIRConstants::TYPE_CLASS_NUTRITION_ORDER_DOT_TEXTURE,
        PHPFHIRConstants::TYPE_NAME_NUTRITION_ORDER_STATUS => PHPFHIRConstants::TYPE_CLASS_NUTRITION_ORDER_STATUS,
        PHPFHIRConstants::TYPE_NAME_NUTRITION_ORDER_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_NUTRITION_ORDER_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION => PHPFHIRConstants::TYPE_CLASS_OBSERVATION,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_DOT_COMPONENT => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_DOT_COMPONENT,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_DOT_REFERENCE_RANGE => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_DOT_REFERENCE_RANGE,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_DOT_RELATED => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_DOT_RELATED,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_RELATIONSHIP_TYPE => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_RELATIONSHIP_TYPE,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_RELATIONSHIP_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_RELATIONSHIP_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_STATUS => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_STATUS,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_OBSERVATION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_OID => PHPFHIRConstants::TYPE_CLASS_OID,
        PHPFHIRConstants::TYPE_NAME_OID_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_OID_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_OPERATION_DEFINITION => PHPFHIRConstants::TYPE_CLASS_OPERATION_DEFINITION,
        PHPFHIRConstants::TYPE_NAME_OPERATION_DEFINITION_DOT_BINDING => PHPFHIRConstants::TYPE_CLASS_OPERATION_DEFINITION_DOT_BINDING,
        PHPFHIRConstants::TYPE_NAME_OPERATION_DEFINITION_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_OPERATION_DEFINITION_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_OPERATION_DEFINITION_DOT_PARAMETER => PHPFHIRConstants::TYPE_CLASS_OPERATION_DEFINITION_DOT_PARAMETER,
        PHPFHIRConstants::TYPE_NAME_OPERATION_KIND => PHPFHIRConstants::TYPE_CLASS_OPERATION_KIND,
        PHPFHIRConstants::TYPE_NAME_OPERATION_KIND_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_OPERATION_KIND_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_OPERATION_OUTCOME => PHPFHIRConstants::TYPE_CLASS_OPERATION_OUTCOME,
        PHPFHIRConstants::TYPE_NAME_OPERATION_OUTCOME_DOT_ISSUE => PHPFHIRConstants::TYPE_CLASS_OPERATION_OUTCOME_DOT_ISSUE,
        PHPFHIRConstants::TYPE_NAME_OPERATION_PARAMETER_USE => PHPFHIRConstants::TYPE_CLASS_OPERATION_PARAMETER_USE,
        PHPFHIRConstants::TYPE_NAME_OPERATION_PARAMETER_USE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_OPERATION_PARAMETER_USE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ORDER => PHPFHIRConstants::TYPE_CLASS_ORDER,
        PHPFHIRConstants::TYPE_NAME_ORDER_DOT_WHEN => PHPFHIRConstants::TYPE_CLASS_ORDER_DOT_WHEN,
        PHPFHIRConstants::TYPE_NAME_ORDER_RESPONSE => PHPFHIRConstants::TYPE_CLASS_ORDER_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_ORDER_STATUS => PHPFHIRConstants::TYPE_CLASS_ORDER_STATUS,
        PHPFHIRConstants::TYPE_NAME_ORDER_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_ORDER_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_ORGANIZATION => PHPFHIRConstants::TYPE_CLASS_ORGANIZATION,
        PHPFHIRConstants::TYPE_NAME_ORGANIZATION_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_ORGANIZATION_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_PARAMETERS => PHPFHIRConstants::TYPE_CLASS_PARAMETERS,
        PHPFHIRConstants::TYPE_NAME_PARAMETERS_DOT_PARAMETER => PHPFHIRConstants::TYPE_CLASS_PARAMETERS_DOT_PARAMETER,
        PHPFHIRConstants::TYPE_NAME_PARTICIPANT_REQUIRED => PHPFHIRConstants::TYPE_CLASS_PARTICIPANT_REQUIRED,
        PHPFHIRConstants::TYPE_NAME_PARTICIPANT_REQUIRED_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PARTICIPANT_REQUIRED_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_PARTICIPANT_STATUS => PHPFHIRConstants::TYPE_CLASS_PARTICIPANT_STATUS,
        PHPFHIRConstants::TYPE_NAME_PARTICIPANT_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PARTICIPANT_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_PARTICIPATION_STATUS => PHPFHIRConstants::TYPE_CLASS_PARTICIPATION_STATUS,
        PHPFHIRConstants::TYPE_NAME_PARTICIPATION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PARTICIPATION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_PATIENT => PHPFHIRConstants::TYPE_CLASS_PATIENT,
        PHPFHIRConstants::TYPE_NAME_PATIENT_DOT_ANIMAL => PHPFHIRConstants::TYPE_CLASS_PATIENT_DOT_ANIMAL,
        PHPFHIRConstants::TYPE_NAME_PATIENT_DOT_COMMUNICATION => PHPFHIRConstants::TYPE_CLASS_PATIENT_DOT_COMMUNICATION,
        PHPFHIRConstants::TYPE_NAME_PATIENT_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_PATIENT_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_PATIENT_DOT_LINK => PHPFHIRConstants::TYPE_CLASS_PATIENT_DOT_LINK,
        PHPFHIRConstants::TYPE_NAME_PAYMENT_NOTICE => PHPFHIRConstants::TYPE_CLASS_PAYMENT_NOTICE,
        PHPFHIRConstants::TYPE_NAME_PAYMENT_RECONCILIATION => PHPFHIRConstants::TYPE_CLASS_PAYMENT_RECONCILIATION,
        PHPFHIRConstants::TYPE_NAME_PAYMENT_RECONCILIATION_DOT_DETAIL => PHPFHIRConstants::TYPE_CLASS_PAYMENT_RECONCILIATION_DOT_DETAIL,
        PHPFHIRConstants::TYPE_NAME_PAYMENT_RECONCILIATION_DOT_NOTE => PHPFHIRConstants::TYPE_CLASS_PAYMENT_RECONCILIATION_DOT_NOTE,
        PHPFHIRConstants::TYPE_NAME_PERIOD => PHPFHIRConstants::TYPE_CLASS_PERIOD,
        PHPFHIRConstants::TYPE_NAME_PERSON => PHPFHIRConstants::TYPE_CLASS_PERSON,
        PHPFHIRConstants::TYPE_NAME_PERSON_DOT_LINK => PHPFHIRConstants::TYPE_CLASS_PERSON_DOT_LINK,
        PHPFHIRConstants::TYPE_NAME_POSITIVE_INT => PHPFHIRConstants::TYPE_CLASS_POSITIVE_INT,
        PHPFHIRConstants::TYPE_NAME_POSITIVE_INT_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_POSITIVE_INT_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_PRACTITIONER => PHPFHIRConstants::TYPE_CLASS_PRACTITIONER,
        PHPFHIRConstants::TYPE_NAME_PRACTITIONER_DOT_PRACTITIONER_ROLE => PHPFHIRConstants::TYPE_CLASS_PRACTITIONER_DOT_PRACTITIONER_ROLE,
        PHPFHIRConstants::TYPE_NAME_PRACTITIONER_DOT_QUALIFICATION => PHPFHIRConstants::TYPE_CLASS_PRACTITIONER_DOT_QUALIFICATION,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE => PHPFHIRConstants::TYPE_CLASS_PROCEDURE,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_DOT_FOCAL_DEVICE => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_DOT_FOCAL_DEVICE,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_DOT_PERFORMER => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_DOT_PERFORMER,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_REQUEST => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_REQUEST,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_REQUEST_PRIORITY => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_REQUEST_PRIORITY,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_REQUEST_PRIORITY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_REQUEST_PRIORITY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_REQUEST_STATUS => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_REQUEST_STATUS,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_REQUEST_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_REQUEST_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_STATUS => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_STATUS,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_PROCESS_REQUEST => PHPFHIRConstants::TYPE_CLASS_PROCESS_REQUEST,
        PHPFHIRConstants::TYPE_NAME_PROCESS_REQUEST_DOT_ITEM => PHPFHIRConstants::TYPE_CLASS_PROCESS_REQUEST_DOT_ITEM,
        PHPFHIRConstants::TYPE_NAME_PROCESS_RESPONSE => PHPFHIRConstants::TYPE_CLASS_PROCESS_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_PROCESS_RESPONSE_DOT_NOTES => PHPFHIRConstants::TYPE_CLASS_PROCESS_RESPONSE_DOT_NOTES,
        PHPFHIRConstants::TYPE_NAME_PROPERTY_REPRESENTATION => PHPFHIRConstants::TYPE_CLASS_PROPERTY_REPRESENTATION,
        PHPFHIRConstants::TYPE_NAME_PROPERTY_REPRESENTATION_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PROPERTY_REPRESENTATION_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE => PHPFHIRConstants::TYPE_CLASS_PROVENANCE,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE_DOT_AGENT => PHPFHIRConstants::TYPE_CLASS_PROVENANCE_DOT_AGENT,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE_DOT_ENTITY => PHPFHIRConstants::TYPE_CLASS_PROVENANCE_DOT_ENTITY,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE_DOT_RELATED_AGENT => PHPFHIRConstants::TYPE_CLASS_PROVENANCE_DOT_RELATED_AGENT,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE_ENTITY_ROLE => PHPFHIRConstants::TYPE_CLASS_PROVENANCE_ENTITY_ROLE,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE_ENTITY_ROLE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_PROVENANCE_ENTITY_ROLE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_QUANTITY => PHPFHIRConstants::TYPE_CLASS_QUANTITY,
        PHPFHIRConstants::TYPE_NAME_QUANTITY_COMPARATOR => PHPFHIRConstants::TYPE_CLASS_QUANTITY_COMPARATOR,
        PHPFHIRConstants::TYPE_NAME_QUANTITY_COMPARATOR_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_QUANTITY_COMPARATOR_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_DOT_GROUP => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_DOT_GROUP,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_DOT_QUESTION => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_DOT_QUESTION,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_RESPONSE => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_RESPONSE_DOT_ANSWER => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_RESPONSE_DOT_ANSWER,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_RESPONSE_DOT_GROUP => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_RESPONSE_DOT_GROUP,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_RESPONSE_DOT_QUESTION => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_RESPONSE_DOT_QUESTION,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_RESPONSE_STATUS => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_RESPONSE_STATUS,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_RESPONSE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_RESPONSE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_STATUS => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_STATUS,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RANGE => PHPFHIRConstants::TYPE_CLASS_RANGE,
        PHPFHIRConstants::TYPE_NAME_RATIO => PHPFHIRConstants::TYPE_CLASS_RATIO,
        PHPFHIRConstants::TYPE_NAME_REFERENCE => PHPFHIRConstants::TYPE_CLASS_REFERENCE,
        PHPFHIRConstants::TYPE_NAME_REFERRAL_REQUEST => PHPFHIRConstants::TYPE_CLASS_REFERRAL_REQUEST,
        PHPFHIRConstants::TYPE_NAME_REFERRAL_STATUS => PHPFHIRConstants::TYPE_CLASS_REFERRAL_STATUS,
        PHPFHIRConstants::TYPE_NAME_REFERRAL_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_REFERRAL_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RELATED_PERSON => PHPFHIRConstants::TYPE_CLASS_RELATED_PERSON,
        PHPFHIRConstants::TYPE_NAME_REMITTANCE_OUTCOME => PHPFHIRConstants::TYPE_CLASS_REMITTANCE_OUTCOME,
        PHPFHIRConstants::TYPE_NAME_REMITTANCE_OUTCOME_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_REMITTANCE_OUTCOME_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RESOURCE => PHPFHIRConstants::TYPE_CLASS_RESOURCE,
        PHPFHIRConstants::TYPE_NAME_RESOURCE_CONTAINER => PHPFHIRConstants::TYPE_CLASS_RESOURCE_CONTAINER,
        PHPFHIRConstants::TYPE_NAME_RESOURCE_VERSION_POLICY => PHPFHIRConstants::TYPE_CLASS_RESOURCE_VERSION_POLICY,
        PHPFHIRConstants::TYPE_NAME_RESOURCE_VERSION_POLICY_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_RESOURCE_VERSION_POLICY_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RESPONSE_TYPE => PHPFHIRConstants::TYPE_CLASS_RESPONSE_TYPE,
        PHPFHIRConstants::TYPE_NAME_RESPONSE_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_RESPONSE_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RESTFUL_CONFORMANCE_MODE => PHPFHIRConstants::TYPE_CLASS_RESTFUL_CONFORMANCE_MODE,
        PHPFHIRConstants::TYPE_NAME_RESTFUL_CONFORMANCE_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_RESTFUL_CONFORMANCE_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_RISK_ASSESSMENT => PHPFHIRConstants::TYPE_CLASS_RISK_ASSESSMENT,
        PHPFHIRConstants::TYPE_NAME_RISK_ASSESSMENT_DOT_PREDICTION => PHPFHIRConstants::TYPE_CLASS_RISK_ASSESSMENT_DOT_PREDICTION,
        PHPFHIRConstants::TYPE_NAME_SAMPLED_DATA => PHPFHIRConstants::TYPE_CLASS_SAMPLED_DATA,
        PHPFHIRConstants::TYPE_NAME_SAMPLED_DATA_DATA_TYPE => PHPFHIRConstants::TYPE_CLASS_SAMPLED_DATA_DATA_TYPE,
        PHPFHIRConstants::TYPE_NAME_SAMPLED_DATA_DATA_TYPE_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_SAMPLED_DATA_DATA_TYPE_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_SCHEDULE => PHPFHIRConstants::TYPE_CLASS_SCHEDULE,
        PHPFHIRConstants::TYPE_NAME_SEARCH_ENTRY_MODE => PHPFHIRConstants::TYPE_CLASS_SEARCH_ENTRY_MODE,
        PHPFHIRConstants::TYPE_NAME_SEARCH_ENTRY_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SEARCH_ENTRY_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SEARCH_MODIFIER_CODE => PHPFHIRConstants::TYPE_CLASS_SEARCH_MODIFIER_CODE,
        PHPFHIRConstants::TYPE_NAME_SEARCH_MODIFIER_CODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SEARCH_MODIFIER_CODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SEARCH_PARAMETER => PHPFHIRConstants::TYPE_CLASS_SEARCH_PARAMETER,
        PHPFHIRConstants::TYPE_NAME_SEARCH_PARAMETER_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_SEARCH_PARAMETER_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_SEARCH_PARAM_TYPE => PHPFHIRConstants::TYPE_CLASS_SEARCH_PARAM_TYPE,
        PHPFHIRConstants::TYPE_NAME_SEARCH_PARAM_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SEARCH_PARAM_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SIGNATURE => PHPFHIRConstants::TYPE_CLASS_SIGNATURE,
        PHPFHIRConstants::TYPE_NAME_SIMPLE_QUANTITY => PHPFHIRConstants::TYPE_CLASS_SIMPLE_QUANTITY,
        PHPFHIRConstants::TYPE_NAME_SLICING_RULES => PHPFHIRConstants::TYPE_CLASS_SLICING_RULES,
        PHPFHIRConstants::TYPE_NAME_SLICING_RULES_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SLICING_RULES_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SLOT => PHPFHIRConstants::TYPE_CLASS_SLOT,
        PHPFHIRConstants::TYPE_NAME_SLOT_STATUS => PHPFHIRConstants::TYPE_CLASS_SLOT_STATUS,
        PHPFHIRConstants::TYPE_NAME_SLOT_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SLOT_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN => PHPFHIRConstants::TYPE_CLASS_SPECIMEN,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN_DOT_COLLECTION => PHPFHIRConstants::TYPE_CLASS_SPECIMEN_DOT_COLLECTION,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN_DOT_CONTAINER => PHPFHIRConstants::TYPE_CLASS_SPECIMEN_DOT_CONTAINER,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN_DOT_TREATMENT => PHPFHIRConstants::TYPE_CLASS_SPECIMEN_DOT_TREATMENT,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN_STATUS => PHPFHIRConstants::TYPE_CLASS_SPECIMEN_STATUS,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SPECIMEN_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_STRING => PHPFHIRConstants::TYPE_CLASS_STRING,
        PHPFHIRConstants::TYPE_NAME_STRING_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_STRING_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_STRUCTURE_DEFINITION => PHPFHIRConstants::TYPE_CLASS_STRUCTURE_DEFINITION,
        PHPFHIRConstants::TYPE_NAME_STRUCTURE_DEFINITION_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_STRUCTURE_DEFINITION_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_STRUCTURE_DEFINITION_DOT_DIFFERENTIAL => PHPFHIRConstants::TYPE_CLASS_STRUCTURE_DEFINITION_DOT_DIFFERENTIAL,
        PHPFHIRConstants::TYPE_NAME_STRUCTURE_DEFINITION_DOT_MAPPING => PHPFHIRConstants::TYPE_CLASS_STRUCTURE_DEFINITION_DOT_MAPPING,
        PHPFHIRConstants::TYPE_NAME_STRUCTURE_DEFINITION_DOT_SNAPSHOT => PHPFHIRConstants::TYPE_CLASS_STRUCTURE_DEFINITION_DOT_SNAPSHOT,
        PHPFHIRConstants::TYPE_NAME_STRUCTURE_DEFINITION_KIND => PHPFHIRConstants::TYPE_CLASS_STRUCTURE_DEFINITION_KIND,
        PHPFHIRConstants::TYPE_NAME_STRUCTURE_DEFINITION_KIND_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_STRUCTURE_DEFINITION_KIND_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SUBSCRIPTION => PHPFHIRConstants::TYPE_CLASS_SUBSCRIPTION,
        PHPFHIRConstants::TYPE_NAME_SUBSCRIPTION_DOT_CHANNEL => PHPFHIRConstants::TYPE_CLASS_SUBSCRIPTION_DOT_CHANNEL,
        PHPFHIRConstants::TYPE_NAME_SUBSCRIPTION_CHANNEL_TYPE => PHPFHIRConstants::TYPE_CLASS_SUBSCRIPTION_CHANNEL_TYPE,
        PHPFHIRConstants::TYPE_NAME_SUBSCRIPTION_CHANNEL_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SUBSCRIPTION_CHANNEL_TYPE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SUBSCRIPTION_STATUS => PHPFHIRConstants::TYPE_CLASS_SUBSCRIPTION_STATUS,
        PHPFHIRConstants::TYPE_NAME_SUBSCRIPTION_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SUBSCRIPTION_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SUBSTANCE => PHPFHIRConstants::TYPE_CLASS_SUBSTANCE,
        PHPFHIRConstants::TYPE_NAME_SUBSTANCE_DOT_INGREDIENT => PHPFHIRConstants::TYPE_CLASS_SUBSTANCE_DOT_INGREDIENT,
        PHPFHIRConstants::TYPE_NAME_SUBSTANCE_DOT_INSTANCE => PHPFHIRConstants::TYPE_CLASS_SUBSTANCE_DOT_INSTANCE,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_DELIVERY => PHPFHIRConstants::TYPE_CLASS_SUPPLY_DELIVERY,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_DELIVERY_STATUS => PHPFHIRConstants::TYPE_CLASS_SUPPLY_DELIVERY_STATUS,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_DELIVERY_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SUPPLY_DELIVERY_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_REQUEST => PHPFHIRConstants::TYPE_CLASS_SUPPLY_REQUEST,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_REQUEST_DOT_WHEN => PHPFHIRConstants::TYPE_CLASS_SUPPLY_REQUEST_DOT_WHEN,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_REQUEST_STATUS => PHPFHIRConstants::TYPE_CLASS_SUPPLY_REQUEST_STATUS,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_REQUEST_STATUS_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SUPPLY_REQUEST_STATUS_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_SYSTEM_RESTFUL_INTERACTION => PHPFHIRConstants::TYPE_CLASS_SYSTEM_RESTFUL_INTERACTION,
        PHPFHIRConstants::TYPE_NAME_SYSTEM_RESTFUL_INTERACTION_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_SYSTEM_RESTFUL_INTERACTION_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_ACTION => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_ACTION,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_ACTION_1 => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_ACTION_1,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_ACTION_2 => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_ACTION_2,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_ASSERT => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_ASSERT,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_CAPABILITY => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_CAPABILITY,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_FIXTURE => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_FIXTURE,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_LINK => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_LINK,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_METADATA => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_METADATA,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_OPERATION => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_OPERATION,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_REQUEST_HEADER => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_REQUEST_HEADER,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_SETUP => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_SETUP,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_TEARDOWN => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_TEARDOWN,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_TEST => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_TEST,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT_DOT_VARIABLE => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT_DOT_VARIABLE,
        PHPFHIRConstants::TYPE_NAME_TIME => PHPFHIRConstants::TYPE_CLASS_TIME,
        PHPFHIRConstants::TYPE_NAME_TIME_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_TIME_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_TIMING => PHPFHIRConstants::TYPE_CLASS_TIMING,
        PHPFHIRConstants::TYPE_NAME_TIMING_DOT_REPEAT => PHPFHIRConstants::TYPE_CLASS_TIMING_DOT_REPEAT,
        PHPFHIRConstants::TYPE_NAME_TRANSACTION_MODE => PHPFHIRConstants::TYPE_CLASS_TRANSACTION_MODE,
        PHPFHIRConstants::TYPE_NAME_TRANSACTION_MODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_TRANSACTION_MODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_TYPE_RESTFUL_INTERACTION => PHPFHIRConstants::TYPE_CLASS_TYPE_RESTFUL_INTERACTION,
        PHPFHIRConstants::TYPE_NAME_TYPE_RESTFUL_INTERACTION_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_TYPE_RESTFUL_INTERACTION_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_UNITS_OF_TIME => PHPFHIRConstants::TYPE_CLASS_UNITS_OF_TIME,
        PHPFHIRConstants::TYPE_NAME_UNITS_OF_TIME_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_UNITS_OF_TIME_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_UNKNOWN_CONTENT_CODE => PHPFHIRConstants::TYPE_CLASS_UNKNOWN_CONTENT_CODE,
        PHPFHIRConstants::TYPE_NAME_UNKNOWN_CONTENT_CODE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_UNKNOWN_CONTENT_CODE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_UNSIGNED_INT => PHPFHIRConstants::TYPE_CLASS_UNSIGNED_INT,
        PHPFHIRConstants::TYPE_NAME_UNSIGNED_INT_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_UNSIGNED_INT_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_URI => PHPFHIRConstants::TYPE_CLASS_URI,
        PHPFHIRConstants::TYPE_NAME_URI_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_URI_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_USE => PHPFHIRConstants::TYPE_CLASS_USE,
        PHPFHIRConstants::TYPE_NAME_USE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_USE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_UUID => PHPFHIRConstants::TYPE_CLASS_UUID,
        PHPFHIRConstants::TYPE_NAME_UUID_HYPHEN_PRIMITIVE => PHPFHIRConstants::TYPE_CLASS_UUID_HYPHEN_PRIMITIVE,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET => PHPFHIRConstants::TYPE_CLASS_VALUE_SET,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_CODE_SYSTEM => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_CODE_SYSTEM,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_COMPOSE => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_COMPOSE,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_CONCEPT => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_CONCEPT,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_CONCEPT_1 => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_CONCEPT_1,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_CONTACT => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_CONTACT,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_CONTAINS => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_CONTAINS,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_DESIGNATION => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_DESIGNATION,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_EXPANSION => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_EXPANSION,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_FILTER => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_FILTER,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_INCLUDE => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_INCLUDE,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET_DOT_PARAMETER => PHPFHIRConstants::TYPE_CLASS_VALUE_SET_DOT_PARAMETER,
        PHPFHIRConstants::TYPE_NAME_VISION_BASE => PHPFHIRConstants::TYPE_CLASS_VISION_BASE,
        PHPFHIRConstants::TYPE_NAME_VISION_BASE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_VISION_BASE_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_VISION_EYES => PHPFHIRConstants::TYPE_CLASS_VISION_EYES,
        PHPFHIRConstants::TYPE_NAME_VISION_EYES_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_VISION_EYES_HYPHEN_LIST,
        PHPFHIRConstants::TYPE_NAME_VISION_PRESCRIPTION => PHPFHIRConstants::TYPE_CLASS_VISION_PRESCRIPTION,
        PHPFHIRConstants::TYPE_NAME_VISION_PRESCRIPTION_DOT_DISPENSE => PHPFHIRConstants::TYPE_CLASS_VISION_PRESCRIPTION_DOT_DISPENSE,
        PHPFHIRConstants::TYPE_NAME_XPATH_USAGE_TYPE => PHPFHIRConstants::TYPE_CLASS_XPATH_USAGE_TYPE,
        PHPFHIRConstants::TYPE_NAME_XPATH_USAGE_TYPE_HYPHEN_LIST => PHPFHIRConstants::TYPE_CLASS_XPATH_USAGE_TYPE_HYPHEN_LIST,
    ];

    /**
     * This is the list of resource types that are allowed to be contained within a ResourceContainer type
     * @var array
     */
    private static $_containableTypes = [
        PHPFHIRConstants::TYPE_NAME_ACCOUNT => PHPFHIRConstants::TYPE_CLASS_ACCOUNT,
        PHPFHIRConstants::TYPE_NAME_ALLERGY_INTOLERANCE => PHPFHIRConstants::TYPE_CLASS_ALLERGY_INTOLERANCE,
        PHPFHIRConstants::TYPE_NAME_APPOINTMENT => PHPFHIRConstants::TYPE_CLASS_APPOINTMENT,
        PHPFHIRConstants::TYPE_NAME_APPOINTMENT_RESPONSE => PHPFHIRConstants::TYPE_CLASS_APPOINTMENT_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_AUDIT_EVENT => PHPFHIRConstants::TYPE_CLASS_AUDIT_EVENT,
        PHPFHIRConstants::TYPE_NAME_BASIC => PHPFHIRConstants::TYPE_CLASS_BASIC,
        PHPFHIRConstants::TYPE_NAME_BINARY => PHPFHIRConstants::TYPE_CLASS_BINARY,
        PHPFHIRConstants::TYPE_NAME_BODY_SITE => PHPFHIRConstants::TYPE_CLASS_BODY_SITE,
        PHPFHIRConstants::TYPE_NAME_BUNDLE => PHPFHIRConstants::TYPE_CLASS_BUNDLE,
        PHPFHIRConstants::TYPE_NAME_CARE_PLAN => PHPFHIRConstants::TYPE_CLASS_CARE_PLAN,
        PHPFHIRConstants::TYPE_NAME_CLAIM => PHPFHIRConstants::TYPE_CLASS_CLAIM,
        PHPFHIRConstants::TYPE_NAME_CLAIM_RESPONSE => PHPFHIRConstants::TYPE_CLASS_CLAIM_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_CLINICAL_IMPRESSION => PHPFHIRConstants::TYPE_CLASS_CLINICAL_IMPRESSION,
        PHPFHIRConstants::TYPE_NAME_COMMUNICATION => PHPFHIRConstants::TYPE_CLASS_COMMUNICATION,
        PHPFHIRConstants::TYPE_NAME_COMMUNICATION_REQUEST => PHPFHIRConstants::TYPE_CLASS_COMMUNICATION_REQUEST,
        PHPFHIRConstants::TYPE_NAME_COMPOSITION => PHPFHIRConstants::TYPE_CLASS_COMPOSITION,
        PHPFHIRConstants::TYPE_NAME_CONCEPT_MAP => PHPFHIRConstants::TYPE_CLASS_CONCEPT_MAP,
        PHPFHIRConstants::TYPE_NAME_CONDITION => PHPFHIRConstants::TYPE_CLASS_CONDITION,
        PHPFHIRConstants::TYPE_NAME_CONFORMANCE => PHPFHIRConstants::TYPE_CLASS_CONFORMANCE,
        PHPFHIRConstants::TYPE_NAME_CONTRACT => PHPFHIRConstants::TYPE_CLASS_CONTRACT,
        PHPFHIRConstants::TYPE_NAME_COVERAGE => PHPFHIRConstants::TYPE_CLASS_COVERAGE,
        PHPFHIRConstants::TYPE_NAME_DATA_ELEMENT => PHPFHIRConstants::TYPE_CLASS_DATA_ELEMENT,
        PHPFHIRConstants::TYPE_NAME_DETECTED_ISSUE => PHPFHIRConstants::TYPE_CLASS_DETECTED_ISSUE,
        PHPFHIRConstants::TYPE_NAME_DEVICE => PHPFHIRConstants::TYPE_CLASS_DEVICE,
        PHPFHIRConstants::TYPE_NAME_DEVICE_COMPONENT => PHPFHIRConstants::TYPE_CLASS_DEVICE_COMPONENT,
        PHPFHIRConstants::TYPE_NAME_DEVICE_METRIC => PHPFHIRConstants::TYPE_CLASS_DEVICE_METRIC,
        PHPFHIRConstants::TYPE_NAME_DEVICE_USE_REQUEST => PHPFHIRConstants::TYPE_CLASS_DEVICE_USE_REQUEST,
        PHPFHIRConstants::TYPE_NAME_DEVICE_USE_STATEMENT => PHPFHIRConstants::TYPE_CLASS_DEVICE_USE_STATEMENT,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_ORDER => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_ORDER,
        PHPFHIRConstants::TYPE_NAME_DIAGNOSTIC_REPORT => PHPFHIRConstants::TYPE_CLASS_DIAGNOSTIC_REPORT,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_MANIFEST => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_MANIFEST,
        PHPFHIRConstants::TYPE_NAME_DOCUMENT_REFERENCE => PHPFHIRConstants::TYPE_CLASS_DOCUMENT_REFERENCE,
        PHPFHIRConstants::TYPE_NAME_ELIGIBILITY_REQUEST => PHPFHIRConstants::TYPE_CLASS_ELIGIBILITY_REQUEST,
        PHPFHIRConstants::TYPE_NAME_ELIGIBILITY_RESPONSE => PHPFHIRConstants::TYPE_CLASS_ELIGIBILITY_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_ENCOUNTER => PHPFHIRConstants::TYPE_CLASS_ENCOUNTER,
        PHPFHIRConstants::TYPE_NAME_ENROLLMENT_REQUEST => PHPFHIRConstants::TYPE_CLASS_ENROLLMENT_REQUEST,
        PHPFHIRConstants::TYPE_NAME_ENROLLMENT_RESPONSE => PHPFHIRConstants::TYPE_CLASS_ENROLLMENT_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_EPISODE_OF_CARE => PHPFHIRConstants::TYPE_CLASS_EPISODE_OF_CARE,
        PHPFHIRConstants::TYPE_NAME_EXPLANATION_OF_BENEFIT => PHPFHIRConstants::TYPE_CLASS_EXPLANATION_OF_BENEFIT,
        PHPFHIRConstants::TYPE_NAME_FAMILY_MEMBER_HISTORY => PHPFHIRConstants::TYPE_CLASS_FAMILY_MEMBER_HISTORY,
        PHPFHIRConstants::TYPE_NAME_FLAG => PHPFHIRConstants::TYPE_CLASS_FLAG,
        PHPFHIRConstants::TYPE_NAME_GOAL => PHPFHIRConstants::TYPE_CLASS_GOAL,
        PHPFHIRConstants::TYPE_NAME_GROUP => PHPFHIRConstants::TYPE_CLASS_GROUP,
        PHPFHIRConstants::TYPE_NAME_HEALTHCARE_SERVICE => PHPFHIRConstants::TYPE_CLASS_HEALTHCARE_SERVICE,
        PHPFHIRConstants::TYPE_NAME_IMAGING_OBJECT_SELECTION => PHPFHIRConstants::TYPE_CLASS_IMAGING_OBJECT_SELECTION,
        PHPFHIRConstants::TYPE_NAME_IMAGING_STUDY => PHPFHIRConstants::TYPE_CLASS_IMAGING_STUDY,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION,
        PHPFHIRConstants::TYPE_NAME_IMMUNIZATION_RECOMMENDATION => PHPFHIRConstants::TYPE_CLASS_IMMUNIZATION_RECOMMENDATION,
        PHPFHIRConstants::TYPE_NAME_IMPLEMENTATION_GUIDE => PHPFHIRConstants::TYPE_CLASS_IMPLEMENTATION_GUIDE,
        PHPFHIRConstants::TYPE_NAME_LIST => PHPFHIRConstants::TYPE_CLASS_LIST,
        PHPFHIRConstants::TYPE_NAME_LOCATION => PHPFHIRConstants::TYPE_CLASS_LOCATION,
        PHPFHIRConstants::TYPE_NAME_MEDIA => PHPFHIRConstants::TYPE_CLASS_MEDIA,
        PHPFHIRConstants::TYPE_NAME_MEDICATION => PHPFHIRConstants::TYPE_CLASS_MEDICATION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ADMINISTRATION => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ADMINISTRATION,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_DISPENSE => PHPFHIRConstants::TYPE_CLASS_MEDICATION_DISPENSE,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_ORDER => PHPFHIRConstants::TYPE_CLASS_MEDICATION_ORDER,
        PHPFHIRConstants::TYPE_NAME_MEDICATION_STATEMENT => PHPFHIRConstants::TYPE_CLASS_MEDICATION_STATEMENT,
        PHPFHIRConstants::TYPE_NAME_MESSAGE_HEADER => PHPFHIRConstants::TYPE_CLASS_MESSAGE_HEADER,
        PHPFHIRConstants::TYPE_NAME_NAMING_SYSTEM => PHPFHIRConstants::TYPE_CLASS_NAMING_SYSTEM,
        PHPFHIRConstants::TYPE_NAME_NUTRITION_ORDER => PHPFHIRConstants::TYPE_CLASS_NUTRITION_ORDER,
        PHPFHIRConstants::TYPE_NAME_OBSERVATION => PHPFHIRConstants::TYPE_CLASS_OBSERVATION,
        PHPFHIRConstants::TYPE_NAME_OPERATION_DEFINITION => PHPFHIRConstants::TYPE_CLASS_OPERATION_DEFINITION,
        PHPFHIRConstants::TYPE_NAME_OPERATION_OUTCOME => PHPFHIRConstants::TYPE_CLASS_OPERATION_OUTCOME,
        PHPFHIRConstants::TYPE_NAME_ORDER => PHPFHIRConstants::TYPE_CLASS_ORDER,
        PHPFHIRConstants::TYPE_NAME_ORDER_RESPONSE => PHPFHIRConstants::TYPE_CLASS_ORDER_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_ORGANIZATION => PHPFHIRConstants::TYPE_CLASS_ORGANIZATION,
        PHPFHIRConstants::TYPE_NAME_PARAMETERS => PHPFHIRConstants::TYPE_CLASS_PARAMETERS,
        PHPFHIRConstants::TYPE_NAME_PATIENT => PHPFHIRConstants::TYPE_CLASS_PATIENT,
        PHPFHIRConstants::TYPE_NAME_PAYMENT_NOTICE => PHPFHIRConstants::TYPE_CLASS_PAYMENT_NOTICE,
        PHPFHIRConstants::TYPE_NAME_PAYMENT_RECONCILIATION => PHPFHIRConstants::TYPE_CLASS_PAYMENT_RECONCILIATION,
        PHPFHIRConstants::TYPE_NAME_PERSON => PHPFHIRConstants::TYPE_CLASS_PERSON,
        PHPFHIRConstants::TYPE_NAME_PRACTITIONER => PHPFHIRConstants::TYPE_CLASS_PRACTITIONER,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE => PHPFHIRConstants::TYPE_CLASS_PROCEDURE,
        PHPFHIRConstants::TYPE_NAME_PROCEDURE_REQUEST => PHPFHIRConstants::TYPE_CLASS_PROCEDURE_REQUEST,
        PHPFHIRConstants::TYPE_NAME_PROCESS_REQUEST => PHPFHIRConstants::TYPE_CLASS_PROCESS_REQUEST,
        PHPFHIRConstants::TYPE_NAME_PROCESS_RESPONSE => PHPFHIRConstants::TYPE_CLASS_PROCESS_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_PROVENANCE => PHPFHIRConstants::TYPE_CLASS_PROVENANCE,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE,
        PHPFHIRConstants::TYPE_NAME_QUESTIONNAIRE_RESPONSE => PHPFHIRConstants::TYPE_CLASS_QUESTIONNAIRE_RESPONSE,
        PHPFHIRConstants::TYPE_NAME_REFERRAL_REQUEST => PHPFHIRConstants::TYPE_CLASS_REFERRAL_REQUEST,
        PHPFHIRConstants::TYPE_NAME_RELATED_PERSON => PHPFHIRConstants::TYPE_CLASS_RELATED_PERSON,
        PHPFHIRConstants::TYPE_NAME_RISK_ASSESSMENT => PHPFHIRConstants::TYPE_CLASS_RISK_ASSESSMENT,
        PHPFHIRConstants::TYPE_NAME_SCHEDULE => PHPFHIRConstants::TYPE_CLASS_SCHEDULE,
        PHPFHIRConstants::TYPE_NAME_SEARCH_PARAMETER => PHPFHIRConstants::TYPE_CLASS_SEARCH_PARAMETER,
        PHPFHIRConstants::TYPE_NAME_SLOT => PHPFHIRConstants::TYPE_CLASS_SLOT,
        PHPFHIRConstants::TYPE_NAME_SPECIMEN => PHPFHIRConstants::TYPE_CLASS_SPECIMEN,
        PHPFHIRConstants::TYPE_NAME_STRUCTURE_DEFINITION => PHPFHIRConstants::TYPE_CLASS_STRUCTURE_DEFINITION,
        PHPFHIRConstants::TYPE_NAME_SUBSCRIPTION => PHPFHIRConstants::TYPE_CLASS_SUBSCRIPTION,
        PHPFHIRConstants::TYPE_NAME_SUBSTANCE => PHPFHIRConstants::TYPE_CLASS_SUBSTANCE,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_DELIVERY => PHPFHIRConstants::TYPE_CLASS_SUPPLY_DELIVERY,
        PHPFHIRConstants::TYPE_NAME_SUPPLY_REQUEST => PHPFHIRConstants::TYPE_CLASS_SUPPLY_REQUEST,
        PHPFHIRConstants::TYPE_NAME_TEST_SCRIPT => PHPFHIRConstants::TYPE_CLASS_TEST_SCRIPT,
        PHPFHIRConstants::TYPE_NAME_VALUE_SET => PHPFHIRConstants::TYPE_CLASS_VALUE_SET,
        PHPFHIRConstants::TYPE_NAME_VISION_PRESCRIPTION => PHPFHIRConstants::TYPE_CLASS_VISION_PRESCRIPTION,
    ];

    /**
     * Get fully qualified class name for FHIR Type name.  Returns null if type not found
     * @param string $typeName
     * @return string|null
     */
    public static function getTypeClass($typeName) {
        return (is_string($typeName) && isset(self::$_typeMap[$typeName])) ? self::$_typeMap[$typeName] : null;
    }

    /**
     * Returns the full internal class map
     * @return array
     */
    public static function getMap() {
        return self::$_typeMap;
    }

    /**
     * Returns the full list of containable resource types
     * @return array
     */
    public static function getContainableTypes() {
        return self::$_containableTypes;
    }

    /**
     * @param string $typeName Name of FHIR object reference by ResourceContainer
     * @return string|null Name of class as string or null if type is not contained in map
     */
    public static function getContainedTypeClassName($typeName)
    {
        return (is_string($typeName) && isset(self::$_containableTypes[$typeName])) ? self::$_containableTypes[$typeName] : null;
    }

    /**
     * Will attempt to determine if the provided value is or describes a containable resource type
     * @param object|string|array $type
     * @return bool
     * @throws \InvalidArgumentException
     */
    public static function isContainableResource($type) {
        $tt = gettype($type);
        if ('object' === $tt) {
            if ($type instanceof PHPFHIRTypeInterface) {
                return in_array('\\'.get_class($type), self::$_containableTypes, true);
            }
            if ($type instanceof \SimpleXMLElement) {
                return isset(self::$_containableTypes[$type->getName()]);
            }
            throw new \InvalidArgumentException(sprintf(
                'Expected "$type" to be instance of "\DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTypeInterface" or "%s", saw "%s"',
                '\\SimpleXMLElement',
                get_class($type)
            ));
        }
        if ('string' === $tt) {
            return isset(self::$_containableTypes[$type]) || in_array('\\'.ltrim($type, '\\'), self::$_containableTypes, true);
        }
        if ('array' === $tt) {
            if (isset($type[PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE])) {
                return isset(self::$_containableTypes[$type[PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE]]);
            }
            return false;
        }

        throw new \InvalidArgumentException(sprintf(
            'Unable to process input of type "%s"',
            gettype($type)
        ));
    }

    /**
     * @param \SimpleXMLElement $sxe Parent element containing inline resource
     * @return \DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRContainedTypeInterface|null
     */
    public static function getContainedTypeFromXML(\SimpleXMLElement $sxe)
    {
        $typeName = $sxe->getName();
        $className = self::getContainedTypeClassName($typeName);
        if (null === $className) {
            throw self::createdInvalidContainedTypeException($typeName);
        }
        /** @var \DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRContainedTypeInterface $className */
        return $className::xmlUnserialize($sxe);
    }

    /**
     * @param array|null $data
     * @return \DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRContainedTypeInterface|null
     */
    public static function getContainedTypeFromArray($data)
    {
        if (null === $data) {
            return null;
        }
        if (!is_array($data)) {
            throw new \InvalidArgumentException(sprintf(
                '$data must be either an array or null, %s seen.',
                gettype($data)
            ));
        }
        if ([] === $data) {
            return null;
        }
        $resourceType = isset($data[PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE]) ? $data[PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE] : null;
        if (null === $resourceType) {
            throw new \DomainException(sprintf(
                'Unable to determine contained Resource type from input (missing "%s" key).  Keys: ["%s"]',
                PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE,
                implode('","', array_keys($data))
            ));
        }
        unset($data[PHPFHIRConstants::JSON_FIELD_RESOURCE_TYPE]);
        $className = self::getContainedTypeClassName($resourceType);
        if (null === $className) {
            throw self::createdInvalidContainedTypeException($resourceType);
        }
        return new $className($data);
    }

    /**
     * @param string $typeName
     * @return \UnexpectedValueException
     */
    private static function createdInvalidContainedTypeException($typeName) {
        return new \UnexpectedValueException(sprintf(
            'Type "%s" is not among the list of types allowed within a ResourceContainer',
            $typeName
        ));
    }
}
